### ISSUE TITLE
The citation url / link only shows the root domain 

### ISSUE THREAD

**Issue by KingSolomun79** [assafelovic/gpt-researcher#1000]
**Describe the bug**
Whenever i run the researcher the urls of the citations dont return the ful path , so it only links to Forbes.Com but not to the actual page with the information 

**To Reproduce**

**Expected behavior**
i would expect that the URL linsk to the exact path of where the researcher got his information 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] windows 11
 - Browser [e.g. chrome, safari] Chrome 

this is the markdown of a report as example : 

The evolution of experiential retail marks a significant transformation in the retail industry, driven by the need to differentiate physical stores from the convenience of e-commerce. Historically, retail has progressed from department stores and shopping malls to the current trend of experiential retail, which emphasizes creating memorable and engaging shopping experiences. This approach leverages interactive technology, personalized services, and community-building events to foster deeper emotional connections with consumers. Key elements such as augmented reality (AR), virtual reality (VR), and data analytics are integral to crafting these experiences, enhancing customer loyalty, and increasing foot traffic in physical stores ([Forbes](https://www.forbes.com/), [Retail Dive](https://www.retaildive.com/)).

The impact of experiential retail on consumer behavior is profound, as it shifts consumer expectations towards more meaningful and personalized interactions. By engaging consumers emotionally and through sensory stimulation, retailers can create lasting memories that drive brand loyalty and repeat purchases. The integration of technology plays a crucial role in this transformation, enabling retailers to offer personalized and interactive experiences that resonate with modern consumers. As the retail landscape continues to evolve, businesses must embrace emerging technologies and align with cultural and ethical trends to remain competitive. The future of experiential retail will likely be shaped by advancements in AI, IoT, and data analytics, offering new opportunities for innovation and differentiation in a dynamic market ([McKinsey](https://www.mckinsey.com/), [Harvard Business Review](https://hbr.org/)).

**Comment by ElishaKay** [comment]
2 ideas:

a) Try the [multi_agents option](https://github.com/assafelovic/gpt-researcher/tree/master/multi_agents) - also available on localhost 3000 when you run via Docker

b) Add a [custom_logs_handler](https://docs.gptr.dev/docs/gpt-researcher/gptr/handling-logs-as-they-stream) when you run a report - that should provide you with the live links of sources as they stream
