### ISSUE TITLE
Weasyprint

### ISSUE THREAD

**Issue by James-William-Kincaid-III** [assafelovic/gpt-researcher#101]
For Windows 10 users Weasyprint is highly problematic.  I eventually gave up on the install and ended up using the Gregdrizz's md2pdf pull request version to get it running.

"update: if you are having issues with weasyprint, please visit their website and follow the installation instructions: https://doc.courtbouillon.org/weasyprint/stable/first_steps.html"  From the installation instructions there, "Only Windows 11 64-bit is supported."

**Comment by gregdrizz** [comment]
Glad my PR helped you solve this problem(I'm still using it since my pc won't let Weasyprint work correctly for some reason).

Maybe we should make it a permanent solution
