### ISSUE TITLE
strategic LLM max_tokens

### ISSUE THREAD

**Issue by winsonluk** [assafelovic/gpt-researcher#1022]
Hi, setting strategic LLMs for Anthropic models is broken because its langchain doesn't support `max_tokens = None`. Other langchains still work with `max_tokens = None`, just not Anthropic.

```
Dec 13 17:58:10 ubuntu[57441]: Error with strategic LLM: 1 validation error for ChatAnthropic
Dec 13 17:58:10 ubuntu[57441]: max_tokens
Dec 13 17:58:10 ubuntu[57441]:   Input should be a valid integer [type=int_type, input_value=None, input_type=NoneType]
Dec 13 17:58:10 ubuntu[57441]:     For further information visit https://errors.pydantic.dev/2.9/v/int_type. Falling back to smart LLM.
```

Relevant lines in gpt-researcher are here:

https://github.com/assafelovic/gpt-researcher/blob/c7b18fdd185652380333a24eb6e2ac28892cc5d4/gpt_researcher/actions/query_processing.py#L61
```
    try:
        response = await create_chat_completion(
            model=cfg.strategic_llm_model,
            messages=[{"role": "user", "content": gen_queries_prompt}],
            temperature=1,
            llm_provider=cfg.strategic_llm_provider,
            max_tokens=None,
            llm_kwargs=cfg.llm_kwargs,
            cost_callback=cost_callback,
        )
    except Exception as e:
        logger.warning(f"Error with strategic LLM: {e}. Falling back to smart LLM.")
        response = await create_chat_completion(
            model=cfg.smart_llm_model,
            messages=[{"role": "user", "content": gen_queries_prompt}],
            temperature=cfg.temperature,
            max_tokens=cfg.smart_token_limit,
            llm_provider=cfg.smart_llm_provider,
            llm_kwargs=cfg.llm_kwargs,
            cost_callback=cost_callback,
        )
```

All that happens is strategic LLM always fails and falls back to smart LLM. The easiest fix would be setting a new default config value for `strategic_token_limit`.

I'm opening this as a bug since it's probably up for discussion what a good default for `strategic_token_limit` would be.

**Comment by winsonluk** [comment]
@assafelovic any thoughts on whether we should add `strategic_token_limit`, and what a good default would be?

**Comment by assafelovic** [comment]
Hey @winsonluk I think we should tackle it a bit differently. The real problem with not passing token limits is because of `gpt-o1` We can add a hack to check for that model, and if it's different than to pass the cfg.max_tokens param

**Comment by winsonluk** [comment]
@assafelovic Oh interesting, is this right that `max_tokens` is replaced with `max_completion_tokens`? https://community.openai.com/t/why-was-max-tokens-changed-to-max-completion-tokens/938077/4

If so, a check for o1 should work I guess, unless there's a more elegant way to ensure forwards compatibility. Would setting `max_tokens == max_completion_tokens == MAX_INT` be ok, or is there an approximate token number you had in mind?

**Comment by assafelovic** [comment]
@winsonluk 4k should probably do it but if you think there’s a better default then go for it!

**Comment by winsonluk** [comment]
Addressing this in https://github.com/assafelovic/gpt-researcher/pull/1032
