### ISSUE TITLE
Unexpected keyword argument 'language'

### ISSUE THREAD

**Issue by winsonluk** [assafelovic/gpt-researcher#1034]
@assafelovic now that https://github.com/assafelovic/gpt-researcher/pull/1029 and https://github.com/assafelovic/gpt-researcher/pull/1033 have been fixed, would it be possible to re-release the latest when you get a chance?

I think gpt-researcher 0.10.8 (Dec 18, 2024) may be completely broken for most users. I've had to revert back to gpt-researcher==0.10.5

```
TypeError: generate_custom_report_prompt() got an unexpected keyword argument 'language'
```

Thank you!

**Comment by assafelovic** [comment]
@winsonluk just pushed a new PIP version can you check?

**Comment by winsonluk** [comment]
@assafelovic Working again for me, thank you so much!!!
