### ISSUE TITLE
There is no such driver (chromedriver)

### ISSUE THREAD

**Issue by beddows** [assafelovic/gpt-researcher#105]
Thank you for creating a great application! It was working perfectly at first, but since last night I've been getting the error:

`There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_115.0.5790`

Seeing this error for every web page. My version of chrome driver is 115.0.5790.102.

I haven't been able to replicate this on your hosted beta, so it's some type of local config issue I assume.

Also, from what I gather, "chromedriver.storage.googleapis.com" only supports chrome driver up to version 114.

**Comment by rotemweiss57** [comment]
Hi @beddows we have made a small change that suppose to handle this. Can you update the project and try running again? Please update me if it works.

**Comment by rotemweiss57** [comment]
Also, please check the new troubleshooting on the README file in case you're still experiencing issues.
