### ISSUE TITLE
gpt-4 access End of July

### ISSUE THREAD

**Issue by sauadwaya** [assafelovic/gpt-researcher#115]
Running into this error:  The model `gpt-4` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.

According to the article: "We plan to open up access to new developers by the end of July 2023". 
It is August now. Is there anything else I need to do to get permission? Any way we can reach out to OpenAI support for this?

**Comment by leowill01** [comment]
openai admins have said on their forums they are rolling our gpt-4 api access to everyone its just going slowly. all we can do is be patient and wait.

**Comment by assafelovic** [comment]
While some are waiting for gpt4 access you can modify the models in this file: https://github.com/assafelovic/gpt-researcher/blob/master/config/config.py
Simply change it from gpt4 to gpt-3.5-turbo or similar
