### ISSUE TITLE
Is it possible to change for a different OpenAI model, while gpt-4 is not accessible?

### ISSUE THREAD

**Issue by andresolerc** [assafelovic/gpt-researcher#117]

**Comment by sauadwaya** [comment]
I just used 3.5 for the fast api

**Comment by JannikSchneider12** [comment]
How can I change the used model?

**Comment by assafelovic** [comment]
@Mitchell-xiyunfeng yes you can. You can change the models in this file: https://github.com/assafelovic/gpt-researcher/blob/master/config/config.py
