### ISSUE TITLE
Error installing with Docker

### ISSUE THREAD

**Issue by basemaly** [assafelovic/gpt-researcher#122]
Hello again. I tried using the Docker install method but got an error related to Chrome. I'm using an M2 MacbookPro and tried downgrading to an earlier version of Chrome as your documentation suggested, but I keep getting the following error: 

```
 => ERROR [gpt-researcher  7/18] RUN dpkg -i google-chrome-stable_114.0.5735.198-1_amd64.deb                                              0.1s
------
 > [gpt-researcher  7/18] RUN dpkg -i google-chrome-stable_114.0.5735.198-1_amd64.deb:
0.110 dpkg: error processing archive google-chrome-stable_114.0.5735.198-1_amd64.deb (--install):
0.110  package architecture (amd64) does not match system (arm64)
0.116 Errors were encountered while processing:
0.116  google-chrome-stable_114.0.5735.198-1_amd64.deb
------
failed to solve: process "/bin/sh -c dpkg -i google-chrome-stable_114.0.5735.198-1_amd64.deb" did not complete successfully: exit code: 1
```

**Comment by kshitijyad** [comment]
I have the same issue

**Comment by jonathanhawleypeters** [comment]
On an M1 mac, I solved this by adding `platform: linux/amd64` in docker-compose.yml:

```iml
version: '3'
services:
  gpt-researcher:
    image: assafelovic/gpt-researcher
    platform: linux/amd64
    build: ./
    environment: 
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - 8000:8000
  ```

**Comment by rotemweiss57** [comment]
Hi @basemaly and @kshitijyad were you able to solve it?

**Comment by ill-yes** [comment]
> 

This didn't work either :(

```
#0 224.3 Setting up chromium-driver (115.0.5790.170-1~deb11u1) ...
#0 224.3 Setting up termit (3.1-1) ...
#0 224.4 update-alternatives: using /usr/bin/termit to provide /usr/bin/x-terminal-emulator (x-terminal-emulator) in auto mode
#0 224.4 update-alternatives: warning: skip creation of /usr/share/man/man1/x-terminal-emulator.1.gz because associated file /usr/share/man/man1/termit.1.gz (of link group x-terminal-emulator) doesn't exist
#0 224.4 Setting up system-config-printer (1.5.14-1) ...
#0 225.7 Setting up liblwp-protocol-https-perl (6.10-1) ...
#0 225.7 Setting up libwww-perl (6.52-1) ...
#0 225.7 Setting up libxml-parser-perl:amd64 (2.46-2) ...
#0 225.8 Setting up libxml-twig-perl (1:3.52-1) ...
#0 225.8 Setting up libnet-dbus-perl (1.2.0-1+b1) ...
#0 225.8 Processing triggers for libc-bin (2.31-13+deb11u6) ...
#0 225.8 Processing triggers for dbus (1.12.24-0+deb11u1) ...
#0 225.9 Processing triggers for libgdk-pixbuf-2.0-0:amd64 (2.42.2+dfsg-1+deb11u1) ...
#0 226.3 Error: Can't open display: 
------
failed to solve: process "/bin/sh -c apt-get update     && apt-get satisfy -y     \"chromium, chromium-driver (>= 115.0)\"     && chromium --version && chromedriver --version" did not complete successfully: exit code: 1
```

**Comment by assafelovic** [comment]
@ill-yes we've released a new version with improved docker. Can you pull and try again?

**Comment by ill-yes** [comment]
> @ill-yes we've released a new version with improved docker. Can you pull and try again?

Fixed, thanks!
But now I'm facing this issue: https://github.com/assafelovic/gpt-researcher/issues/127

**Comment by TypsyDanger** [comment]
I'm having the same problem in a non-related project, and this thread came up in a google search.  I wonder if you would be willing to share what the solution was?

**Comment by assafelovic** [comment]
Can you please try and pull latest version and try again?

**Comment by assafelovic** [comment]
Closing this for now due to inactivity. Please let us know if you continue to run into this issue.

**Comment by aberhamm** [comment]
> On an M1 mac, I solved this by adding `platform: linux/amd64` in docker-compose.yml:
> 
> version: '3'
> services:
>   gpt-researcher:
>     image: assafelovic/gpt-researcher
>     platform: linux/amd64
>     build: ./
>     environment: 
>       OPENAI_API_KEY: ${OPENAI_API_KEY}
>     ports:
>       - 8000:8000

Worked for me on m3 mac on latest GPTResearcher and Docker. Added `platform: linux/amd64` to each of the services. Thanks!
