### ISSUE TITLE
Error after install

### ISSUE THREAD

**Issue by bbecausereasonss** [assafelovic/gpt-researcher#139]
Followed instructions>

Just get a bunch of errors then this in the pdf.

I'm sorry, but the errors provided above indicate issues with launching the Chrome browser for
web scraping using Selenium WebDriver. As such, the errors do not give relevant information on
quantifying deep work. I am unable to create a detailed report on this topic based on the provided
information. Instead, I would suggest finding and providing relevant information or sources on
the topic of quantifying deep work, so I could provide an in-depth research report based on that
data.

**Comment by bbecausereasonss** [comment]
Could be related to this error I get on launch. Win11

(process:21576): GLib-GIO-WARNING **: 17:40:24.209: Unexpectedly, UWP app `Microsoft.ScreenSketch_11.2306.43.0_x64__8wekyb3d8bbwe' (AUMId `Microsoft.ScreenSketch_8wekyb3d8bbwe!App') supports 29 extensions but has no verbs

**Comment by bbecausereasonss** [comment]
Just get a massive string of these errors:

An error occurred while processing the url https://timelyapp.com/blog/what-is-deep-work: Message: unknown error: Chrome failed to start: was killed.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location C:\Program Files\Google\Chrome\Application\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
Backtrace:
        GetHandleVerifier [0x00007FF697064A62+57106]
        (No symbol) [0x00007FF696FDCF52]
        (No symbol) [0x00007FF696EAE2CB]
        (No symbol) [0x00007FF696ED581B]
        (No symbol) [0x00007FF696ED30AA]
        (No symbol) [0x00007FF696F0E3F7]
        (No symbol) [0x00007FF696F0DF60]
        (No symbol) [0x00007FF696F06793]
        (No symbol) [0x00007FF696EDCE81]
        (No symbol) [0x00007FF696EDE064]
        GetHandleVerifier [0x00007FF697314222+2873042]
        GetHandleVerifier [0x00007FF697366590+3209792]
        GetHandleVerifier [0x00007FF69735F3AF+3180639]
        GetHandleVerifier [0x00007FF6970F5F25+652245]
        (No symbol) [0x00007FF696FE8618]
        (No symbol) [0x00007FF696FE47C4]
        (No symbol) [0x00007FF696FE48BC]
        (No symbol) [0x00007FF696FD4C33]
        BaseThreadInitThunk [0x00007FFF1D6F26AD+29]
        RtlUserThreadStart [0x00007FFF1E60AA78+40]

**Comment by assafelovic** [comment]
Have you tried running with the docker installation? @bbecausereasonss

**Comment by bbecausereasonss** [comment]
To be honest no. I don't use docker.

**Comment by TC23345** [comment]
Just finished working out the weasyprint errors with 'gobject', thank you for the GTK instructions, I'm trying docker now! Will report back! Thanks for the start @assafelovic

**Comment by gregdrizz** [comment]
@0rangeAppl3 @bbecausereasonss 
The issue in a chromedriver version issue, please refer to the "chromedriver downgrade" section in the readme

**Comment by assafelovic** [comment]
Closing due to staleness. If not resolved please reopen.
