### ISSUE TITLE
Web app doesn't work

### ISSUE THREAD

**Issue by bartzokas** [assafelovic/gpt-researcher#149]
https://app.tavily.com/ doesn't seem to work. 
Stays at this point for hours.
Tried it 3 times with API key

![Screenshot 2023-08-23 at 15 24 21](https://github.com/assafelovic/gpt-researcher/assets/1484737/18f33b54-7e7b-4f08-9023-ec82ee30d4b0)

**Comment by smach** [comment]
I tried 2 different questions and it said it couldn't access some of the data and so couldn't write a report. Maybe too many people are using it after it was promoted by LangChain?

**Comment by gregdrizz** [comment]
Looking into it, will give you an update soon

**Comment by assafelovic** [comment]
Should be fixed now. Let us know if still persists @smach @bartzokas

**Comment by bartzokas** [comment]
unfortunately still not working.
I gave it the following prompt

I want to explore business opportunities in AI filmmaking. I am a filmmaker
and marketeer targeting hotels and I am looking to leverage this technology
for generating income. identify the specific needs and pain points in the
industry and suggest ideas

I asked for research report

https://app.tavily.com/#form



Vassilis


Στις Παρ 1 Σεπ 2023 στις 10:51 π.μ., ο/η Assaf Elovic <
***@***.***> έγραψε:
