### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by juniorbonner** [assafelovic/gpt-researcher#15]
[GPT Researcher.txt](https://github.com/assafelovic/gpt-researcher/files/12008727/GPT.Researcher.txt)

Think I followed instructions fully.

**Comment by rotemweiss57** [comment]
Thank you for the logs! This is a known issue, we are working on it. In the meanwhile, please try to reinstall weasyprint.

https://doc.courtbouillon.org/weasyprint/stable/first_steps.html

**Comment by juniorbonner** [comment]
That has fixed it thanks
