### ISSUE TITLE
openai.error.InvalidRequestError: The model `gpt-4` does not exist or you do not have access to it.

### ISSUE THREAD

**Issue by resonates7** [assafelovic/gpt-researcher#153]
Hi,

I'm getting an 'openai.error.InvalidRequestError: The model `gpt-4` does not exist or you do not have access to it.' error. I haven't made any changes to this code. I contacted OpenAI support and they confirmed I'm using the right API key. Although, OpenAI did say there're different chatgpt instances.

Any idea how I can fix this? Can anyone confirm how to make sure I'm using the right API key?

**Comment by premjha9625** [comment]
Hi @resonates7 , have you get solution to this error ?

**Comment by assafelovic** [comment]
gpt4 is not yet available for all. Feel free to change from gpt4 to gpt3.5-turbo in config/config.py file.

**Comment by kamranayub** [comment]
You can also set this in `.env` or environment variable:

```
SMART_LLM_MODEL=gpt-3.5-turbo
```

**Comment by resonates7** [comment]
Thanks! Changing the Smart LLM Model setting in the config.py file to 'gpt-3.5-turbo' fixed the issue.
