### ISSUE TITLE
OSError: cannot load library 'pango-1.0-0'

### ISSUE THREAD

**Issue by goggledefogger** [assafelovic/gpt-researcher#16]
Hi, thanks for creating this project, I'm very interested in trying it. i followed the instructions to clone the repo and install the python packages, but then when trying to run the application I get an `OSError: cannot load library 'pango-1.0-0'` error. I searched the web for answers on that and found one link that said since I'm on a Mac to try `brew install pango` but that didn't fix it. I also tried switching to different versions of python but 3.10 and 3.11 didn't work when trying to install the python packages, I got through that with python 3.8.5

Any ideas on what would fix it on my M1 Mac? Thanks!

here are some relevant sections from the output:

> macbook:gpt-researcher $ uvicorn main:app --reload
> INFO:     Will watch for changes in these directories: ['...']
> INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
> INFO:     Started reloader process [16032] using StatReload
> 
> -----
> 
> WeasyPrint could not import some external libraries. Please carefully follow the installation steps before reporting an issue:
> https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#installation
> https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#troubleshooting 
> 
> -----
> 
> Process SpawnProcess-1:
> Traceback (most recent call last):
>   File "python3.8/multiprocessing/process.py", line 315, in _bootstrap
>     self.run()
>   File "python3.8/multiprocessing/process.py", line 108, in run
>     self._target(*self._args, **self._kwargs)
>   
> ...
> 
>   File "/.pyenv/versions/3.8.5/lib/python3.8/site-packages/uvicorn/config.py", line 473, in load
>     self.loaded_app = import_from_string(self.app)
>   File "/.pyenv/versions/3.8.5/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
>     module = importlib.import_module(module_str)
>   File "/.pyenv/versions/3.8.5/lib/python3.8/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
>  
> ...
> 
>   File "/.pyenv/versions/3.8.5/lib/python3.8/site-packages/cffi/api.py", line 832, in _make_ffi_library
>     backendlib = _load_backend_lib(backend, libname, flags)
>   File "/.pyenv/versions/3.8.5/lib/python3.8/site-packages/cffi/api.py", line 827, in _load_backend_lib
>     raise OSError(msg)
> OSError: cannot load library 'pango-1.0-0': dlopen(pango-1.0-0, 0x0002): tried: 'pango-1.0-0' (no such file), '/System/Volumes/Preboot/Cryptexes/OSpango-1.0-0' (no such file), '/usr/lib/pango-1.0-0' (no such file, not in dyld cache), 'pango-1.0-0' (no such file), '/usr/local/lib/pango-1.0-0' (no such file), '/usr/lib/pango-1.0-0' (no such file, not in dyld cache).  Additionally, ctypes.util.find_library() did not manage to locate a library called 'pango-1.0-0'
>

**Comment by rotemweiss57** [comment]
Thank you for the logs! This is a known issue, we are working on it. In the meanwhile, please try to install python 11 using homebrew. after that, redo the process using pip3 and also run 'pip3 install weasyprint'. please update us if it solved it!

hope it helps

**Comment by assafelovic** [comment]
@goggledefogger can you update if the solution works for you?

**Comment by ifuchs** [comment]
pango problem reported above persists. Haven't gotten this to work.

**Comment by rotemweiss57** [comment]
Please follow these instructions:

1. create a new conda env: 'conda create -n py311 python=3.11'
2. run: 'conda activate py311'
3. clone the repo: git clone https://github.com/assafelovic/gpt-researcher.git
4. go to directory: cd gpt-researcher
5. run: 'pip install -r requirements.txt'
6. run: 'conda install -c conda-forge weasyprint'
7. run: 'export OPENAI_API_KEY={Your API Key here}'
8. run: 'uvicorn main:app --reload'


Please update me if that worked for you!

**Comment by isichan0501** [comment]
> Please follow these instructions:
> 
> 1. create a new conda env: 'conda create -n py311 python=3.11'
> 2. run: 'conda activate py311'
> 3. clone the repo: git clone https://github.com/assafelovic/gpt-researcher.git
> 4. go to directory: cd gpt-researcher
> 5. run: 'pip install -r requirements.txt'
> 6. run: 'conda install -c conda-forge weasyprint'
> 7. run: 'export OPENAI_API_KEY={Your API Key here}'
> 8. run: 'uvicorn main:app --reload'
> 
> Please update me if that worked for you!

Thanks. I ran this on centos7 (amazonlinux2) and it ran fine, still can't run it on windows.

**Comment by nathanael** [comment]
Worked like a charm for me. Same exact problem. 

> Please follow these instructions:
> 
> 1. create a new conda env: 'conda create -n py311 python=3.11'
> 2. run: 'conda activate py311'
> 3. clone the repo: git clone https://github.com/assafelovic/gpt-researcher.git
> 4. go to directory: cd gpt-researcher
> 5. run: 'pip install -r requirements.txt'
> 6. run: 'conda install -c conda-forge weasyprint'
> 7. run: 'export OPENAI_API_KEY={Your API Key here}'
> 8. run: 'uvicorn main:app --reload'
> 
> Please update me if that worked for you!

**Comment by ifuchs** [comment]
Followed the "recipe" above and got this error:

`OSError: cannot load library 'gobject-2.0-0': dlopen(gobject-2.0-0, 0x0002): tried: 'gobject-2.0-0' (no such file), '/System/Volumes/Preboot/Cryptexes/OSgobject-2.0-0' (no such file), '/opt/anaconda3/envs/py311/bin/../lib/gobject-2.0-0' (no such file), '/usr/lib/gobject-2.0-0' (no such file, not in dyld cache), 'gobject-2.0-0' (no such file), '/usr/local/lib/gobject-2.0-0' (no such file), '/usr/lib/gobject-2.0-0' (no such file, not in dyld cache).  Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0-0'`

**Comment by izxle** [comment]
> Please follow these instructions:
> 
> 1. create a new conda env: 'conda create -n py311 python=3.11'
> 2. run: 'conda activate py311'
> 3. clone the repo: git clone https://github.com/assafelovic/gpt-researcher.git
> 4. go to directory: cd gpt-researcher
> 5. run: 'pip install -r requirements.txt'
> 6. run: 'conda install -c conda-forge weasyprint'
> 7. run: 'export OPENAI_API_KEY={Your API Key here}'
> 8. run: 'uvicorn main:app --reload'
> 
> Please update me if that worked for you!

This resolved the pongo problem, but I now get another error:

```
[...]
  File ".../miniconda3/envs/py311/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'
```
