### ISSUE TITLE
API Error with Docker Installation

### ISSUE THREAD

**Issue by wrzacherjr** [assafelovic/gpt-researcher#161]
Hi All,

I'm sure I'm missing something simple but I keep getting this error when I try to run the application. It's only throwing the error in Docker and not in VSCode. I don't know how to solve it. 

I have a .env file in VSCode that has export OPENAI_API_KEY=my API key from OPENAI

How do I solve this error?

![Screenshot 2023-09-02 at 1 21 28 PM (2)](https://github.com/assafelovic/gpt-researcher/assets/143898977/dfeb0c7f-c57e-43fb-a095-0bc9fda01945)

**Comment by assafelovic** [comment]
Have you tried running it with CLI? Simply in the directory you're running it `export OPENAI_API_KEY=sk-xxx...`

**Comment by wrzacherjr** [comment]
@assafelovic Yes, I've tried running it in the environment as well. It doesn't throw an error until I try utilize the local:8000 webpage

**Comment by assafelovic** [comment]
@wrzacherjr can you try this? `echo "export OPENAI_API_KEY={YOUR API KEY}`
