### ISSUE TITLE
Problem (and solution) with weasyprint and GTK+3 for Windows 10 pro

### ISSUE THREAD

**Issue by fftgit** [assafelovic/gpt-researcher#166]
While installing weasyprint on my windows 10 pro computer, I followed the instructions here : 
https://doc.courtbouillon.org/weasyprint/stable/first_steps.html

But the last command `python -m weasyprint --info` returned an error (beware that this command can also be `python3 -m weasyprint --info` depending on your Python installation, which is v3.11 for me by the way)
"_WeasyPrint could not import some external libraries._"

And the output log displayed in the end :
```
…/…
OSError: cannot load library 'gobject-2.0-0': error 0x7e. Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0-0'
```
The (undocumented) solution is that GTK+3, needed for weasyprint to work (https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer/releases) does not install this library with this name but instead 'libgobject-2.0-0.dll' in the folder (by default) : C:\Program Files\GTK3-Runtime Win64\bin\

So the only thing to do is to copy `libgobject-2.0-0.dll` in the same folder, and rename it to `gobject-2.0-0.dll`, restart your computer (important) and it will work !

```
# python -m weasyprint --info
WeasyPrint version: 59.0
Python version: 3.11.4
Pydyf version: 0.7.0
Pango version: 15003
```

**Comment by assafelovic** [comment]
This is great @fftgit thank you for the resolution! I'll keep this opened for others to see.

**Comment by jrocktorrens** [comment]
This solution saved me! I spent a lot of time trying to figure this out, and your fix did the trick. It's so effective that I believe it should definitely be added to the installation instructions. Big thanks!

**Comment by melund** [comment]
I am using the conda/conda-forge package manager, and hit the same issue with missing "gobject". For me this was fixed by installing version 4 of gtk+. This is the ["gtk4" package here](https://anaconda.org/conda-forge/gtk4).

**Comment by poppykode** [comment]
OSError: cannot load library 'pango-1.0-0': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'pango-1.0-0'

I get this errorr

**Comment by robertobalestri** [comment]
Installed gtk3 for windows like suggested, renamed the library libcairo-gobject-2.dll to gobject-2.0-0.dll. Now it finds it BUT i get this error:
AttributeError: function/symbol 'g_type_init' not found in library 'C:\Program Files\GTK3-Runtime Win64\bin\gobject-2.0-0.dll': error 0x7f

Please help ç_ç
