### ISSUE TITLE
Add books and scientific papers as sources 

### ISSUE THREAD

**Issue by Di3mex** [assafelovic/gpt-researcher#172]
So from my understanding GPT-Researcher does what I would do when I try research a brand new topic -> Google it. However, gpt-researcher goes a few steps further than me by coming up with more varied google search queries and digesting more websites. All this saves me lots of time and I highly enjoy reading the research report that focuses on the things that interest me. 

Now wouldn't it be great to go from 2nd/3rd... hand to the original source material? Because that is what websites are, compilations/remixes of the source material (books, papers, etc...). Lets say we can get access to books/papers in PDF / epub form. Could we incorporate that into the search report? Basically search the book as if it was google for the answer?

All of this AI stuff is way over my head, but could one create embeddings of books and search them for relevant content and have that added as context. Alternatively let the AI agent ingest the book bit by bit with one or two questions in mind to see if an answer is in the text? 

I can also imagine having a corpus of research papers on topics that I am deeply invested in as a permanent additional source of knowledge that the GPT-Researcher agents can query for relevant papers.

**Comment by assafelovic** [comment]
100% @Di3mex this is definitely the next steps we envision. Eventually we'd like GPT Researcher to be agnostic to the data sources (meaning it can potentially research PDFs, books, online articles, datasets, etc) and then finally write and conclude research results in a final paper. Since we're currently understaffed and mostly working to stabilize the current solution, we're still some time before implementing, but we'd love the extra hands! :)

**Comment by Di3mex** [comment]
Have you gotten any concrete plans or ideas on how to implement this feature? With some guidance I might be able to at least start experimenting with adding documents as an additional source.

**Comment by assafelovic** [comment]
@Di3mex The high level idea would be to select the sources before triggering the research question. So for example, you can select both online search + include local sources by importing them for example. On the other hand, we could integrate with additional public online sources. Both directions sound good and valuable and I know some open sources exist at least for the "chat with your data" option. What do you think? What direction were you considering?

**Comment by Di3mex** [comment]
I would probably first try regular RAG. I read something about generating a placeholder answer first and then searching for text that matches it. Maybe the books could be queried like that. 
Ideally one could train a model on new data, but it seems like that is not available to mere mortals.

**Comment by Ethan-Otto** [comment]
Would this only be for only local sources? Or are you imagining having a list of papers websites or APIs that are each searched? So we have a button for "papers sources only" that exclusively use those websites. Does Tavily have a site search option like how google has "site:apple.com"? That could make this much easier.  

A general white list / black list of websites could have many applications. Only being able to research git repos for example.

**Comment by rawwerks** [comment]
for folks who already have a RAG pipeline, you could add Tavily upstream of that, then use the tavily results in addition to your "local sources".

(and +1 for this feature on app.tavily.com/chat to make it easy to use.)

**Comment by VCSinc** [comment]
> @Di3mex The high level idea would be to select the sources before triggering the research question. So for example, you can select both online search + include local sources by importing them for example. On the other hand, we could integrate with additional public online sources. Both directions sound good and valuable and I know some open sources exist at least for the "chat with your data" option. What do you think? What direction were you considering?

Has there been any progress or a rough timeline for this? I would be very interested in such a feature I've been roughly implementing similar features on my own through various libraries and SDKs I've had the most success with Microsoft/Autogen for creating research agents to process information in a group and iterate on it.

Ideally, I would provide scientific papers in PDF format to "Research GPT" and then have a report generated based on web results and the submitted papers.

**Comment by rawwerks** [comment]
i think this would be a really cool option to have. 

two examples (in addition to my idea above about local sources)
- for some of my questions, i'd really like to not have it use information from company websites (only academic articles) - it would be great to be able to "reject" the references i don't trust before it writes the summary. instead of having to rewrite the summary later. 
- for other questions i'd like to use wikipedia as a source, but i don't really want to have to go into the code and rewrite a new agent, then hope that my question triggers that particular agent (for example: materials science agent + wikipedia)

**Comment by assafelovic** [comment]
@rawwerks have you tried only including the source of wikipedia for the research run? Generally you can include multiple domains. And agree we should aim for hybrid search of both public and internal information.
