### ISSUE TITLE
Chromedriver not working

### ISSUE THREAD

**Issue by gururise** [assafelovic/gpt-researcher#187]
It seems in the latest release, the chromedriver is not working.

Followed the quickstart guide to install. (pip install -r requirements.txt)

**Research Question:** Most liked desktop direct-to-film printers under $5000

The report is generated at the end, but contains no useful data because nothing can be pulled from the web.
```
Error processing the url https://sublimationhub.org/5-best-dtf-printers/: Message: disconnected: unable to connect to renderer
Stacktrace:
#0 0x55af3f9e6693 <unknown>
#1 0x55af3f6bc1e7 <unknown>
#2 0x55af3f6f3a39 <unknown>
#3 0x55af3f6eef28 <unknown>
#4 0x55af3f6eb69c <unknown>
#5 0x55af3f72e23a <unknown>
#6 0x55af3f724e93 <unknown>
#7 0x55af3f6f7934 <unknown>
#8 0x55af3f6f871e <unknown>
#9 0x55af3f9abc98 <unknown>
#10 0x55af3f9afbd0 <unknown>
#11 0x55af3f9ba17c <unknown>
#12 0x55af3f9b07e8 <unknown>
#13 0x55af3f97d25f <unknown>
#14 0x55af3f9d4e68 <unknown>
#15 0x55af3f9d5039 <unknown>
#16 0x55af3f9e5823 <unknown>
#17 0x7fa286a8c9eb <unknown>

Error processing the url https://geekbitz.com/dtf-printer/: Message: disconnected: unable to connect to renderer
Stacktrace:
#0 0x5583962f4693 <unknown>
#1 0x558395fca1e7 <unknown>
#2 0x558396001a39 <unknown>
#3 0x558395ffcf28 <unknown>
#4 0x558395ff969c <unknown>
#5 0x55839603c23a <unknown>
#6 0x558396032e93 <unknown>
#7 0x558396005934 <unknown>
#8 0x55839600671e <unknown>
#9 0x5583962b9c98 <unknown>
#10 0x5583962bdbd0 <unknown>
#11 0x5583962c817c <unknown>
#12 0x5583962be7e8 <unknown>
#13 0x55839628b25f <unknown>
#14 0x5583962e2e68 <unknown>
#15 0x5583962e3039 <unknown>
#16 0x5583962f3823 <unknown>
#17 0x7f259aa8c9eb <unknown>

Error processing the url https://www.silhouetteschoolblog.com/2022/08/prestige-a3-dtf-printer-review-pros-and.html: Message: disconnected: unable to connect to renderer
Stacktrace:
#0 0x5622d7f4f693 <unknown>
#1 0x5622d7c251e7 <unknown>
#2 0x5622d7c5ca39 <unknown>
#3 0x5622d7c57f28 <unknown>
#4 0x5622d7c5469c <unknown>
#5 0x5622d7c9723a <unknown>
#6 0x5622d7c8de93 <unknown>
#7 0x5622d7c60934 <unknown>
#8 0x5622d7c6171e <unknown>
#9 0x5622d7f14c98 <unknown>
#10 0x5622d7f18bd0 <unknown>
#11 0x5622d7f2317c <unknown>
#12 0x5622d7f197e8 <unknown>
#13 0x5622d7ee625f <unknown>
#14 0x5622d7f3de68 <unknown>
#15 0x5622d7f3e039 <unknown>
#16 0x5622d7f4e823 <unknown>
#17 0x7feec988c9eb <unknown>
```

**Comment by dmitrijsk** [comment]
Same issue here.

**Comment by minhhung123** [comment]
Same issue here

**Comment by mspublic** [comment]
Here as well. Running on Mac M2.

**Comment by notvicent3** [comment]
Hello, I had the same issue with Ubuntu in WSL, Windows 11 and Google Colab. I reach the solution (idk how) let me some time to develop and research what i touched for put it working again (because is about the chrome driver or libraries) and i will be back with what worked for me. <3

**Comment by notvicent3** [comment]
This https://stackoverflow.com/questions/46807596/webdrivererror-disconnected-unable-to-connect-to-renderer helped for another users. If you want a further support you can join to our discord and I try to solve all your questions <3 
https://discord.gg/dvNtxXGH47
Happy Weekend =)

**Comment by notvicent3** [comment]
This can be closed @assafelovic  with the update of the https://github.com/assafelovic/gpt-researcher/commit/40e93166eb92f4d10d1c6ab651d8e48545345684 is solved the issue.

**Comment by Iamtheoldman** [comment]
same issue nothing seems to work

**Comment by notvicent3** [comment]
> same issue nothing seems to work

Hi brother, I encourage you to jump into our https://discord.gg/dvNtxXGH47 we're reaching the best solution for this as soon as posible. We love to understand what isn't working in your envirorment for create a fast and good solution for this :)

**Comment by Iamtheoldman** [comment]
@notvicent3 I joined today I hope we can figure out this chrome driver issue

**Comment by cryolite-ai** [comment]
Is this a live issue or a dead one? At one point in the above thread it looks like it's been addressed, yet below there appear to be others saying not..

**Comment by assafelovic** [comment]
Removed chromedriver
