### ISSUE TITLE
Local Execution Support for LLM Models

### ISSUE THREAD

**Issue by vinicioslc** [assafelovic/gpt-researcher#188]
Hello,

I am writing to inquire about the potential addition of support for locally executed LLM models, similar to the text-generation-webui which has an API compatible with OpenAI’s ChatGPT.

The GPT Researcher project is an impressive tool for comprehensive online research. However, the ability to execute LLM models locally could provide additional flexibility and control for users.

Looking forward to hearing about any plans in this regard.

Best, Vinny

**Comment by assafelovic** [comment]
Hey, you can see an example of leveraging open source models here: https://github.com/assafelovic/gpt-researcher/pull/150
