### ISSUE TITLE
Errors while running

### ISSUE THREAD

**Issue by pranath** [assafelovic/gpt-researcher#189]
Hi there,
So i downloaded the latest version today and installed the requirements. The web interface starts fine, when I put in a query it starts crawling the web. However it seems to get stuck at a certain point and throw various errors - any idea why? See attached screenshot. Thanks !

![Screenshot 2023-09-17 at 13 58 28](https://github.com/assafelovic/gpt-researcher/assets/12702133/6fc8f4e3-a913-44bf-be34-42da6d0ac424)

**Comment by notvicent3** [comment]
Hi @pranath maybe we can meet all here https://github.com/assafelovic/gpt-researcher/issues/187
Same errors =)
