### ISSUE TITLE
ERROR: Cannot find Chrome binary

### ISSUE THREAD

**Issue by 2b3pro** [assafelovic/gpt-researcher#19]
This error kept repeating with every url. 

`"An error occurred while processing the url https://xxxxx/: Message: unknown error: cannot find Chrome binary"`

Later:

`streaming response...
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 254, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
`
etc. etc. etc.

Running in python virtual environment on MacOS 10.15 (Catalina/Intel), python 3.11.

----Versions installed:
Requirement already satisfied: asyncio==3.4.3 in ./lib/python3.11/site-packages (from -r requirements.txt (line 2)) (3.4.3)
Requirement already satisfied: beautifulsoup4==4.9.3 in ./lib/python3.11/site-packages (from -r requirements.txt (line 3)) (4.9.3)
Requirement already satisfied: colorama==0.4.6 in ./lib/python3.11/site-packages (from -r requirements.txt (line 4)) (0.4.6)
Requirement already satisfied: duckduckgo_search==3.0.2 in ./lib/python3.11/site-packages (from -r requirements.txt (line 5)) (3.0.2)
Requirement already satisfied: md2pdf==1.0.1 in ./lib/python3.11/site-packages (from -r requirements.txt (line 6)) (1.0.1)
Requirement already satisfied: openai~=0.27.0 in ./lib/python3.11/site-packages (from -r requirements.txt (line 7)) (0.27.8)
Requirement already satisfied: playwright==1.35.0 in ./lib/python3.11/site-packages (from -r requirements.txt (line 8)) (1.35.0)
Requirement already satisfied: python-dotenv~=0.21.0 in ./lib/python3.11/site-packages (from -r requirements.txt (line 9)) (0.21.1)
Requirement already satisfied: pyyaml==6.0 in ./lib/python3.11/site-packages (from -r requirements.txt (line 10)) (6.0)
Requirement already satisfied: selenium==4.10.0 in ./lib/python3.11/site-packages (from -r requirements.txt (line 11)) (4.10.0)
Requirement already satisfied: webdriver-manager==3.8.6 in ./lib/python3.11/site-packages (from -r requirements.txt (line 12)) (3.8.6)
Requirement already satisfied: flask in ./lib/python3.11/site-packages (from -r requirements.txt (line 13)) (2.3.2)
Requirement already satisfied: uvicorn in ./lib/python3.11/site-packages (from -r requirements.txt (line 14)) (0.22.0)
Requirement already satisfied: pydantic in ./lib/python3.11/site-packages (from -r requirements.txt (line 15)) (2.0.2)
Requirement already satisfied: fastapi in ./lib/python3.11/site-packages (from -r requirements.txt (line 16)) (0.100.0)
Requirement already satisfied: python-multipart in ./lib/python3.11/site-packages (from -r requirements.txt (line 17)) (0.0.6)
Requirement already satisfied: markdown in ./lib/python3.11/site-packages (from -r requirements.txt (line 18)) (3.4.3)
Requirement already satisfied: soupsieve>1.2 in ./lib/python3.11/site-packages (from beautifulsoup4==4.9.3->-r requirements.txt (line 3)) (2.4.1)
Requirement already satisfied: click>=8.1.3 in ./lib/python3.11/site-packages (from duckduckgo_search==3.0.2->-r requirements.txt (line 5)) (8.1.4)
Requirement already satisfied: requests>=2.30.0 in ./lib/python3.11/site-packages (from duckduckgo_search==3.0.2->-r requirements.txt (line 5)) (2.31.0)
Requirement already satisfied: markdown2 in ./lib/python3.11/site-packages (from md2pdf==1.0.1->-r requirements.txt (line 6)) (2.4.9)
Requirement already satisfied: docopt in ./lib/python3.11/site-packages (from md2pdf==1.0.1->-r requirements.txt (line 6)) (0.6.2)
Requirement already satisfied: WeasyPrint in ./lib/python3.11/site-packages (from md2pdf==1.0.1->-r requirements.txt (line 6)) (59.0)
Requirement already satisfied: greenlet==2.0.2 in ./lib/python3.11/site-packages (from playwright==1.35.0->-r requirements.txt (line 8)) (2.0.2)
Requirement already satisfied: pyee==9.0.4 in ./lib/python3.11/site-packages (from playwright==1.35.0->-r requirements.txt (line 8)) (9.0.4)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in ./lib/python3.11/site-packages (from selenium==4.10.0->-r requirements.txt (line 11)) (2.0.3)
Requirement already satisfied: trio~=0.17 in ./lib/python3.11/site-packages (from selenium==4.10.0->-r requirements.txt (line 11)) (0.22.1)
Requirement already satisfied: trio-websocket~=0.9 in ./lib/python3.11/site-packages (from selenium==4.10.0->-r requirements.txt (line 11)) (0.10.3)
Requirement already satisfied: certifi>=2021.10.8 in ./lib/python3.11/site-packages (from selenium==4.10.0->-r requirements.txt (line 11)) (2023.5.7)
Requirement already satisfied: tqdm in ./lib/python3.11/site-packages (from webdriver-manager==3.8.6->-r requirements.txt (line 12)) (4.65.0)
Requirement already satisfied: packaging in ./lib/python3.11/site-packages (from webdriver-manager==3.8.6->-r requirements.txt (line 12)) (23.1)
Requirement already satisfied: typing-extensions in ./lib/python3.11/site-packages (from pyee==9.0.4->playwright==1.35.0->-r requirements.txt (line 8)) (4.7.1)
Requirement already satisfied: aiohttp in ./lib/python3.11/site-packages (from openai~=0.27.0->-r requirements.txt (line 7)) (3.8.4)
Requirement already satisfied: Werkzeug>=2.3.3 in ./lib/python3.11/site-packages (from flask->-r requirements.txt (line 13)) (2.3.6)
Requirement already satisfied: Jinja2>=3.1.2 in ./lib/python3.11/site-packages (from flask->-r requirements.txt (line 13)) (3.1.2)
Requirement already satisfied: itsdangerous>=2.1.2 in ./lib/python3.11/site-packages (from flask->-r requirements.txt (line 13)) (2.1.2)
Requirement already satisfied: blinker>=1.6.2 in ./lib/python3.11/site-packages (from flask->-r requirements.txt (line 13)) (1.6.2)
Requirement already satisfied: h11>=0.8 in ./lib/python3.11/site-packages (from uvicorn->-r requirements.txt (line 14)) (0.14.0)
Requirement already satisfied: annotated-types>=0.4.0 in ./lib/python3.11/site-packages (from pydantic->-r requirements.txt (line 15)) (0.5.0)
Requirement already satisfied: pydantic-core==2.1.2 in ./lib/python3.11/site-packages (from pydantic->-r requirements.txt (line 15)) (2.1.2)
Requirement already satisfied: starlette<0.28.0,>=0.27.0 in ./lib/python3.11/site-packages (from fastapi->-r requirements.txt (line 16)) (0.27.0)
Requirement already satisfied: MarkupSafe>=2.0 in ./lib/python3.11/site-packages (from Jinja2>=3.1.2->flask->-r requirements.txt (line 13)) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in ./lib/python3.11/site-packages (from requests>=2.30.0->duckduckgo_search==3.0.2->-r requirements.txt (line 5)) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in ./lib/python3.11/site-packages (from requests>=2.30.0->duckduckgo_search==3.0.2->-r requirements.txt (line 5)) (3.4)
Requirement already satisfied: anyio<5,>=3.4.0 in ./lib/python3.11/site-packages (from starlette<0.28.0,>=0.27.0->fastapi->-r requirements.txt (line 16)) (3.7.1)
Requirement already satisfied: attrs>=20.1.0 in ./lib/python3.11/site-packages (from trio~=0.17->selenium==4.10.0->-r requirements.txt (line 11)) (23.1.0)
Requirement already satisfied: sortedcontainers in ./lib/python3.11/site-packages (from trio~=0.17->selenium==4.10.0->-r requirements.txt (line 11)) (2.4.0)
Requirement already satisfied: outcome in ./lib/python3.11/site-packages (from trio~=0.17->selenium==4.10.0->-r requirements.txt (line 11)) (1.2.0)
Requirement already satisfied: sniffio in ./lib/python3.11/site-packages (from trio~=0.17->selenium==4.10.0->-r requirements.txt (line 11)) (1.3.0)
Requirement already satisfied: exceptiongroup in ./lib/python3.11/site-packages (from trio-websocket~=0.9->selenium==4.10.0->-r requirements.txt (line 11)) (1.1.2)
Requirement already satisfied: wsproto>=0.14 in ./lib/python3.11/site-packages (from trio-websocket~=0.9->selenium==4.10.0->-r requirements.txt (line 11)) (1.2.0)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in ./lib/python3.11/site-packages (from urllib3[socks]<3,>=1.26->selenium==4.10.0->-r requirements.txt (line 11)) (1.7.1)
Requirement already satisfied: multidict<7.0,>=4.5 in ./lib/python3.11/site-packages (from aiohttp->openai~=0.27.0->-r requirements.txt (line 7)) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in ./lib/python3.11/site-packages (from aiohttp->openai~=0.27.0->-r requirements.txt (line 7)) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in ./lib/python3.11/site-packages (from aiohttp->openai~=0.27.0->-r requirements.txt (line 7)) (1.9.2)
Requirement already satisfied: frozenlist>=1.1.1 in ./lib/python3.11/site-packages (from aiohttp->openai~=0.27.0->-r requirements.txt (line 7)) (1.3.3)
Requirement already satisfied: aiosignal>=1.1.2 in ./lib/python3.11/site-packages (from aiohttp->openai~=0.27.0->-r requirements.txt (line 7)) (1.3.1)
Requirement already satisfied: pydyf>=0.6.0 in ./lib/python3.11/site-packages (from WeasyPrint->md2pdf==1.0.1->-r requirements.txt (line 6)) (0.7.0)
Requirement already satisfied: cffi>=0.6 in ./lib/python3.11/site-packages (from WeasyPrint->md2pdf==1.0.1->-r requirements.txt (line 6)) (1.15.1)
Requirement already satisfied: html5lib>=1.1 in ./lib/python3.11/site-packages (from WeasyPrint->md2pdf==1.0.1->-r requirements.txt (line 6)) (1.1)
Requirement already satisfied: tinycss2>=1.0.0 in ./lib/python3.11/site-packages (from WeasyPrint->md2pdf==1.0.1->-r requirements.txt (line 6)) (1.2.1)
Requirement already satisfied: cssselect2>=0.1 in ./lib/python3.11/site-packages (from WeasyPrint->md2pdf==1.0.1->-r requirements.txt (line 6)) (0.7.0)
Requirement already satisfied: Pyphen>=0.9.1 in ./lib/python3.11/site-packages (from WeasyPrint->md2pdf==1.0.1->-r requirements.txt (line 6)) (0.14.0)
Requirement already satisfied: Pillow>=9.1.0 in ./lib/python3.11/site-packages (from WeasyPrint->md2pdf==1.0.1->-r requirements.txt (line 6)) (10.0.0)
Requirement already satisfied: fonttools[woff]>=4.0.0 in ./lib/python3.11/site-packages (from WeasyPrint->md2pdf==1.0.1->-r requirements.txt (line 6)) (4.40.0)
Requirement already satisfied: pycparser in ./lib/python3.11/site-packages (from cffi>=0.6->WeasyPrint->md2pdf==1.0.1->-r requirements.txt (line 6)) (2.21)
Requirement already satisfied: webencodings in ./lib/python3.11/site-packages (from cssselect2>=0.1->WeasyPrint->md2pdf==1.0.1->-r requirements.txt (line 6)) (0.5.1)
Requirement already satisfied: zopfli>=0.1.4 in ./lib/python3.11/site-packages (from fonttools[woff]>=4.0.0->WeasyPrint->md2pdf==1.0.1->-r requirements.txt (line 6)) (0.2.2)
Requirement already satisfied: brotli>=1.0.1 in ./lib/python3.11/site-packages (from fonttools[woff]>=4.0.0->WeasyPrint->md2pdf==1.0.1->-r requirements.txt (line 6)) (1.0.9)
Requirement already satisfied: six>=1.9 in ./lib/python3.11/site-packages (from html5lib>=1.1->WeasyPrint->md2pdf==1.0.1->-r requirements.txt (line 6)) (1.16.0)

**Comment by rotemweiss57** [comment]
can you try 'pip install --upgrade webdriver_manager' and run it again?

**Comment by 2b3pro** [comment]
- I uninstalled it, and then reinstalled it, as upgrading didn't do anything.
- I deleted the "outputs" folder and started again.
=> Same errors concerning Chrome binary for every attempt to scrape.

Also, fails at 
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Volumes/XXX/Projects/gpt-researcher/lib/python3.11/site-packages/uvicorn/protocols/websockets/wsproto_impl.py", line 249, in run_asgi
    result = await self.app(self.scope, self.receive, self.send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by 2b3pro** [comment]
I have solved the problem. Google Chrome wasn't installed on my system. I wasn't aware that it needed to be.
