### ISSUE TITLE
Research vs Resource vs Outline report

### ISSUE THREAD

**Issue by ryanshrott** [assafelovic/gpt-researcher#191]
What's the difference between these?

**Comment by notvicent3** [comment]
![image](https://github.com/assafelovic/gpt-researcher/assets/132854638/a99409d0-7c58-4adc-a691-53d224ba4c41)

**Comment by assafelovic** [comment]
Thanks @notvicent3 for this. More generally @ryanshrott each solve a different use case. Research provides a comprehensive report for the given query while Resource helps with emphasizing on reflecting the best resources to answer the question. It depends on your goal. Some seek answers while others want to write the report themselves but get help finding valuable resources. Lmk if this answers your question.
