### ISSUE TITLE
Error processing zip file

### ISSUE THREAD

**Issue by 2b3pro** [assafelovic/gpt-researcher#20]
There were a few odd errors:

Error processing the url https://www.psychologytoday.com/us/blog/small-social-systems/201011/keeping-your-commitments-yourself: **File is not a zip file**
Error processing the url https://www.verywellmind.com/what-is-the-rule-of-commitment-2795890: **File is not a zip file**

Why is it expecting a zip file from scraping a page?

**Comment by assafelovic** [comment]
Hi @2b3pro sometimes Selenium fails scraping certain sites. Have you tried running it again?

**Comment by 2b3pro** [comment]
I'll give it a shot.
