### ISSUE TITLE
Old data?

### ISSUE THREAD

**Issue by stevenbaert** [assafelovic/gpt-researcher#202]
Love the project, but it is looking for old data? What makes GPT useless, since code asistants in 2021 were nowhere at all back then.

Example:

Query = looking for AI code assistants.
--- GPT Research ---
Searching with query Top AI code assistants in 2021...

Scraping url https://clickup.com/blog/ai-code-tools/ with question Top AI code assistants in 2021
Scraping url https://www.developer.com/project-management/ai-code-assistants/ with question Top AI code assistants in 2021

**Comment by assafelovic** [comment]
Hey @stevenbaert this is a great catch. Can you pull the latest and try again? The issue was that when generating content the LLM did not take into consideration what is the current date so it fell back to 2021 which is its last knowledge. After adding the current date in the query generation this should be resolved. LMK looking forward!

**Comment by stevenbaert** [comment]
Thank you for your swift reply! The project is shaping up nicely, although it's not quite there yet. Below are some areas for improvement and questions I have:

- Clarification on Options: The GUI offers options like Research, Output, and Outline Report. Could you add tooltips or labels to clarify what each option entails?

- Configuration Flexibility: The current setup lacks some customization options. For instance, I'd like to use Azure OpenAI instead of ChatGPT. Additionally, I'd prefer more output formats beyond PDF and a detailed analysis of the tools, including their pros and cons, perhaps in a table format.

- Input Limitations: The input field is restricted to a single line. It would be beneficial to have access to a system prompt or more explicit instructions on what kind of input is expected and how it should be formatted.

- Feature Request: For example, I'm interested in writing a Python script that scans LinkedIn profiles of specific colleagues in a particular country and then summarizes their professional history. It would be great if your tool could facilitate this.
So f.e. look op Steven Baert on LinkedIn he should have in his profile he is from Belgium and working for Telenet (to filter), then also look for his colleagues named ... make a summary in a table. If you would find some other fun facts about these people, also add it into a table below with reference but make sure they are the same people and refer why they are.
All the data which you are looking for is on the Internet, so GPTResearcher is just automating/facilitating the job.
Though the output for now isn't really usable. To little, to general. I'd want something like this per subject: https://www.stevenbaert.ai/open-interpreter-shaping-the-future-of-how-we-interact-with-computers/

- Documentation and Code Extension: I haven't delved into your code yet, but I recommend using an open interpreter for documentation. It can scan your folder and generate a Markdown file, and even assist in code extension.

- Command-Line Usage: Is there a way to run your code via the command line, bypassing the GUI?

By the way, I recently used an open interpreter for documentation in an AI-generated newsletter I shared: [AI-NewsAggregator on GitHub](https://github.com/stevenbaert/AI-NewsAggregator).
---
Final summary length:  885
The text does not provide specific information about the performance and user reviews of AI tools like Open Interpreter, Chat DEV, AutoGen, and GitHub Copilot.
Searching with query Latest updates and features of AI-driven coding assistance technologies 2023...
Scraping url https://sourceforge.net/software/ai-coding-assistants/ with question Latest updates and features of AI-driven coding assistance technologies 2023
Scraping url https://www.forbes.com/sites/bernardmarr/2023/09/18/the-10-most-important-ai-trends-for-2024-everyone-must-be-ready-for-now/ with question Latest updates and features of AI-driven coding assistance technologies 2023
Scraping url https://www.forbes.com/sites/bernardmarr/2022/10/10/the-5-biggest-artificial-intelligence-ai-trends-in-2023/ with question Latest updates and features of AI-driven coding assistance technologies 2023

**Comment by notvicent3** [comment]
As an user of gpt-researcher for 3 months, I think that the dates are a problem in most cases, since the blogs and the "SEO" guys are dedicated to altering the dates of the publications to obtain better results with users' search inputs.

**Comment by assafelovic** [comment]
@stevenbaert thank you for the super valuable feedback! We'd love your help to contribute on any of them if you're interested. We'll definitely add these to our backlog.
