### ISSUE TITLE
Privacy Concern: API Key Exposure in Traffic Monitoring

### ISSUE THREAD

**Issue by cometothed4rkside** [assafelovic/gpt-researcher#203]
I have noticed a privacy concern when using the service, as it seems to send requests directly to OpenAI services. This behavior exposes the API key when traffic is monitored.

I kindly request that the development team investigates this issue and implements necessary measures to protect the confidentiality of the API key during transmission. This could include using encryption or other secure practices to ensure that the API key remains private.

Please let me know if there are any updates or if further information is needed to address this issue effectively. Thank you for your attention to this matter.

**Comment by parsh78** [comment]
Hello @cometothed4rkside , if understand your concern corretly, wouldn't the API key be sent over https to OpenAI?

**Comment by ivarprudnikov** [comment]
> This behavior exposes the API key when traffic is monitored

Could you provide an example of how this gets exposed? It should be encrypted when in transit.

As far as I see [the code is using](https://github.com/assafelovic/gpt-researcher/blob/master/agent/llm_utils.py#L18) regular authentication mechanism documented in the OpenAI docs https://platform.openai.com/docs/api-reference/authentication

**Comment by assafelovic** [comment]
Thanks everyone for your comments. There should be no security concerns using the API KEY. It is only saved locally and is not passed anywhere but to OpenAI via https and using their official API endpoint.

**Comment by cryolite-ai** [comment]
If this has been checked and there isn't any known leakage (e.g. no packetdump from a current version of the app), then this should perhaps be closed (please @assafelovic ). 

The fewer issues that are live at any one time, the easier it is to spot any meaningful ones when reviewing them. Thank you.
