### ISSUE TITLE
duckduckgo 3.9.1 cannot be resolved

### ISSUE THREAD

**Issue by ivarprudnikov** [assafelovic/gpt-researcher#204]
Just tried installing locally and it failed when trying to find duckduckgo_search v3.9.1

```
python3 -m venv venv 
source venv/bin/activate
pip install -r requirements.txt 
...
...
ERROR: Could not find a version that satisfies the requirement duckduckgo_search==3.9.1 (from versions: 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.9.5, 1.0, 1.1, 1.2, 1.3, 1.3.5, 1.4, 1.5, 1.5.1, 1.5.2, 1.6, 1.6.2, 1.7.1, 1.8, 1.8.1, 1.8.2, 2.0.2, 2.1.3, 2.2.0, 2.2.2, 2.3.0, 2.3.1, 2.4.0, 2.5.0, 2.6.0, 2.6.1, 2.7.0, 2.8.0, 2.8.1, 2.8.3, 2.8.4, 2.8.5, 2.8.6, 2.9.0, 2.9.1, 2.9.2, 2.9.3, 2.9.4, 2.9.5, 3.0.2, 3.1.1, 3.2.0, 3.3.0, 3.4.1, 3.5.0, 3.6.0, 3.7.0, 3.7.1, 3.8.0, 3.8.1, 3.8.2, 3.8.3, 3.8.4, 3.8.5, 3.8.6, 3.9.3)
ERROR: No matching distribution found for duckduckgo_search==3.9.1
```

Almost like it was removed from index if looking into pypi https://pypi.org/project/duckduckgo-search/#history

Maybe replacing the current constraint with something like `duckduckgo_search~=3.9` (https://peps.python.org/pep-0440/#compatible-release) in [requirements.txt ](https://github.com/assafelovic/gpt-researcher/blob/master/requirements.txt) might be a safer option to avoid such issue (given patch versions should not include breaking changes)?

**Comment by ivarprudnikov** [comment]
haha, dependabot opened a PR automatically  #207

**Comment by assafelovic** [comment]
Thanks for raising this issue. Updated to 3.9.3.
