### ISSUE TITLE
Parsing error from markdown file during conversion to pdf

### ISSUE THREAD

**Issue by proy9714** [assafelovic/gpt-researcher#213]
Most of the times I am getting an error from the **write_md_to_pdf** function : 

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 1093: invalid start byte

**Comment by proy9714** [comment]
The error is occurring in the md_to_pdf() function in text.py. My best guess is that the library is failing to parse unknown characters from the markdown. I have solved the error locally, using weasyprint. Converting the markdown text to an html object and then writing to pdf. This seems to work better!

    `# Convert Markdown to HTML
    html = markdown.markdown(markdown_text)

    # Create a WeasyPrint HTML object
    html_obj = HTML(string=html)

    # Generate the PDF file
    html_obj.write_pdf(f"{file_path}.pdf")`

**Comment by assafelovic** [comment]
Hey @proy9714 can you submit a PR for this?
