### ISSUE TITLE
Bug: broken threading with chromium webdriver

### ISSUE THREAD

**Issue by ArtemPt239** [assafelovic/gpt-researcher#226]
Currently, when running GPT Researcher with chrome browser, text returned from `scrape_text_with_selenium` in [this line](https://github.com/assafelovic/gpt-researcher/blob/c2b60483e393af9ad1f30005bcc0e338b1e78292/actions/web_scrape.py#L61) is the same for each thread despite receiving different URLs. 

After extensive testing, I believe the problem is somewhere within chromium webdriver (each thread spawns a new WebDriver object and  a new browser process - and the code matches working examples of selenium threading I found on the web, but the [page_source](https://github.com/assafelovic/gpt-researcher/blob/c2b60483e393af9ad1f30005bcc0e338b1e78292/actions/web_scrape.py#L165) is assigned the same value in each thread nevertheless)

However, switching to using firefox seems to fix this problem.

Just wanted to let you know - it is easy to miss this behavior, especially because generated [summary_text](https://github.com/assafelovic/gpt-researcher/blob/c2b60483e393af9ad1f30005bcc0e338b1e78292/actions/web_scrape.py#L65) looks a bit different despite receiving the same `text` input in each thread.

How to reproduce:
1. Add `print(text)` after [this line](https://github.com/assafelovic/gpt-researcher/blob/c2b60483e393af9ad1f30005bcc0e338b1e78292/actions/web_scrape.py#L61)
2. Run GPT researcher and check the logs

**Comment by ArtemPt239** [comment]
For those wishing to fix this by using firefox it may be useful to see this issue: #227 and this pull request: #228, as running with `USE_WEB_BROWSER=firefox` does not work out of the box for now

**Comment by assafelovic** [comment]
Thank you @ArtemPt239 for your fix and raising this issue. Closing this thread
