### ISSUE TITLE
Bug: can't run with firefox as selenium browser

### ISSUE THREAD

**Issue by ArtemPt239** [assafelovic/gpt-researcher#227]
There are two issues when running GPT researcher with `USE_WEB_BROWSER=firefox`:

1) Firefox is not installed in the dockerfile
2) Accessing GeckoDriver via `webdriver_manager` in each thread quickly overwhelms the github API rate limit of 60 requests per hour - it seems that `webdriver_manager` performs github API requests with each call to `GeckoDriverManager().install()`, even when accessing GeckoDriver from cache, without downloading

I created a pull request that fixes both of these issues: #228

**Comment by assafelovic** [comment]
Hey @ArtemPt239 , thank you very much for your contribution, we'll take a look at the PR. Indeed we did not support Firefox until now. Thank you!
