### ISSUE TITLE
Feature Request: Token usage

### ISSUE THREAD

**Issue by shyamsantoki** [assafelovic/gpt-researcher#229]
Any plans on adding OpenAI token usage?

**Comment by assafelovic** [comment]
Hey @shyamsantoki , can you please explain more in details what's missing and what you're looking to use with the token usage?

**Comment by shyamsantoki** [comment]
How can I get to know about the OpenAI token usage? (tokens used to generate the report)

**Comment by assafelovic** [comment]
Got it @shyamsantoki , we'll add it to our roadmap!

**Comment by badcom** [comment]
+1 to this

**Comment by assafelovic** [comment]
Hey updating that since we're agnostic to LLMs and providing now more options for additional LLMs this would not be achievable just for OpenAI so closing request for now.
