### ISSUE TITLE
Module missing?

### ISSUE THREAD

**Issue by ifuchs** [assafelovic/gpt-researcher#23]
File "/opt/anaconda3/lib/python3.9/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 19, in <module>
    from websockets.datastructures import Headers
ModuleNotFoundError: No module named 'websockets.datastructures'

**Comment by assafelovic** [comment]
@ifuchs can you try running `pip install -U websockets` and try again?

**Comment by ifuchs** [comment]
Done. Now I get:
File "/Users/ihf/gpt-researcher/main.py", line 1, in <module>
    from fastapi import FastAPI, Request, WebSocket, WebSocketDisconnect
ImportError: cannot import name 'WebSocketDisconnect' from 'fastapi' (/opt/anaconda3/lib/python3.9/site-packages/fastapi/__init__.py)

**Comment by ifuchs** [comment]
I tried `pip install --upgrade fastapi` and now I get:
OSError: cannot load library 'pango-1.0-0': dlopen(pango-1.0-0, 0x0002): tried: 'pango-1.0-0' (no such file), '/System/Volumes/Preboot/Cryptexes/OSpango-1.0-0' (no such file), '/opt/anaconda3/lib/python3.9/site-packages/../../pango-1.0-0' (no such file), '/opt/anaconda3/bin/../lib/pango-1.0-0' (no such file), '/usr/lib/pango-1.0-0' (no such file, not in dyld cache), 'pango-1.0-0' (no such file), '/usr/local/lib/pango-1.0-0' (no such file), '/usr/lib/pango-1.0-0' (no such file, not in dyld cache).  Additionally, ctypes.util.find_library() did not manage to locate a library called 'pango-1.0-0'

**Comment by tedydaniel** [comment]
I solved this by restarting the terminal, probably some env issues.

**Comment by rotemweiss57** [comment]
Thanks for the update!
