### ISSUE TITLE
Enhance Report Depth and Incorporate Significance-Based Search Results

### ISSUE THREAD

**Issue by shkao** [assafelovic/gpt-researcher#238]
Hi @assafelovic,

I've been exploring the GPT Researcher and its capabilities. It's an excellent tool, and I have some suggestions that could potentially enhance its functionality, especially after the release of gpt-4-1106-preview:

**1. Increasing Report Depth**: Currently, the reports generated seem to cap at around 1,200 words. For more comprehensive research tasks, it would be beneficial to have the option to extend the depth to at least 2,500 words. This could involve:

* Adjusting the summarization process to retain more detail from the scraped resources.
* Modifying the planner agent to allow for the generation of more extensive research questions that could lead to longer, more detailed reports.
* Providing an option in the configuration to set the desired word count for the final report.

**2. Incorporating Importance in Search Results**: The current model seems to prioritize recency in its search results. While this is useful, it might overlook seminal works or highly cited papers that are fundamental to a topic. I suggest:

* Integrating a metric for "importance" or "influence" that could be factored into the search algorithm. This might include the number of citations or the impact factor of the source.
* Allowing users to specify the weight of recency versus significance in their search query to better tailor the results to their research needs.

These enhancements could further the mission of the GPT Researcher to provide accurate, unbiased, and factual information by improving the depth and relevance of the research reports.

Thank you for considering these suggestions.

**Comment by assafelovic** [comment]
Dear @shkao, thank you very much for this detailed feedback, it's exactly what helps us take gpt-researcher to the next level. We've updated our roadmap (see To-Do) much thanks to it: https://trello.com/b/3O7KBePw/gpt-researcher-roadmap

If you're interested in collaborating or helping us test for feedback please reach out at our Discord channel! Thank you!

**Comment by shkao** [comment]
Great, thank you very much for your response.
