### ISSUE TITLE
DevToolsActivePort file doesn't exist

### ISSUE THREAD

**Issue by msantoro14** [assafelovic/gpt-researcher#24]
Running on Windows.  Getting this error:

An error occurred while processing the url https://en.wikipedia.org/wiki/John_Calvin: Message: unknown error: Chrome failed to start: was killed.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location C:\Program Files\Google\Chrome\Application\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

**Comment by CasparTrost** [comment]
Exact same issue for me. Tried different arguments for chromeOptions but couldnt find a solution so far.

**Comment by TashaSkyUp** [comment]
Same issue for me
Chrome : Version 114.0.5735.199 (Official Build) (64-bit)
but tried brave and  firefox as well no luck

**Comment by rotemweiss57** [comment]
Looking into that. Did any of you found a solution?

**Comment by msantoro14** [comment]
> 

Negative.

**Comment by CasparTrost** [comment]
Tried pretty much all fixes I could find online. Issue still exists.

**Comment by ckiefer** [comment]
Same here.

**Comment by Drawwork** [comment]
perfectly the same problem. anybody to downgrade chrome?

**Comment by assafelovic** [comment]
Is this issue still happening? I understand should be resolved by now

**Comment by CasparTrost** [comment]
@assafelovic Yes. Still happening.

**Comment by best2160187** [comment]
@msantoro14 
I am trying to running the code on windows 10 but can't find a solution to the error "OSError: cannot load library 'gobject-2.0-0': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0-0'".
I installed GTK+3 following the instruction from the link in the troubling shoot but it didn't work.
I suppose you already solved this error.
How kind of you if you give me the solution.

**Comment by msantoro14** [comment]
I didn't have this error.  I've been using the test environment as a
workaround.

**Comment by CasparTrost** [comment]
I`m still running into the mentioned issue.
