### ISSUE TITLE
Issue in adding multiple domains to include domain

### ISSUE THREAD

**Issue by Pooja-narasimhan** [assafelovic/gpt-researcher#248]
While using GPT-Researcher, I encountered an issue when attempting to narrow down my searches by specifying multiple domains in the include_domain attribute. The search results still included domains that were not explicitly mentioned. However, when I tested with only one domain specified, the results were more closely aligned with that particular domain.

It seems that the inclusion of multiple domains might not be functioning as expected, as the search outcomes extend beyond the specified domains.

**Comment by assafelovic** [comment]
Hey @Pooja-narasimhan there is a limit of around 12 multiple domains. Can you please share more details on both your input and output logs?

**Comment by norrisp90** [comment]
Where/how is the include_domain attribute used? I need what i think it offers but can't find any ref to it?

**Comment by assafelovic** [comment]
Hey @norrisp90 you can check out the latest release that allows referring to specific domains here: https://github.com/assafelovic/gpt-researcher/discussions/321
