### ISSUE TITLE
error  gobject-2.0-0'

### ISSUE THREAD

**Issue by OumYacout** [assafelovic/gpt-researcher#25]
any issue for this error ???

OSError: cannot load library 'gobject-2.0-0': dlopen(gobject-2.0-0, 0x0002): tried: 'gobject-2.0-0' (no such file), '/usr/lib/gobject-2.0-0' (no such file), '/Users/mac/Downloads/gpt-researcher-master/gobject-2.0-0' (no such file), '/usr/lib/gobject-2.0-0' (no such file).  Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0-0'

**Comment by OumYacout** [comment]
Solved by just correctly installing  weasyprint. 
I use this comand : brew install weasyprint

**Comment by OumYacout** [comment]
Solved by just correctly installing weasyprint.
I use this comand : brew install weasyprint

**Comment by TashaSkyUp** [comment]
E:\git\gpt-researcher\venv\Scripts\python.exe -Xfrozen_modules=off E:\git\gpt-researcher\main.py 
-----
WeasyPrint could not import some external libraries. Please carefully follow the installation steps before reporting an issue:
https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#installation
https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#troubleshooting 

-----

E:\git\gpt-researcher\processing\text.py:19: UserWarning: md2pdf import failed: cannot load library 'gobject-2.0-0': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0-0'

Yeah same problem on windows, need to install a crud ton of stuff by hand that I normally don't use to get it working. 

Can you move to some other package?

**Comment by sarkaramitabh300** [comment]
if anyone using conda, you should install use these commands
conda install -c conda-forge weasyprint
conda install -c "conda-forge/label/cf202003" weasyprint
