### ISSUE TITLE
Copy paste contain $

### ISSUE THREAD

**Issue by jeff0723** [assafelovic/gpt-researcher#252]
Your copy paste in the document all contain $.

for example: `$ pip install -r requirements.txt`

Will be good to remove it.

**Comment by notvicent3** [comment]
There's a reason behind the "$". I encourage you to research about that "$" and what it means when we talk about Terminal.

**Comment by assafelovic** [comment]
Hey @jeff0723 , thanks for this. $ is a standard for cli commands.
