### ISSUE TITLE
Markdown to PDF  Chinese font view exception

### ISSUE THREAD

**Issue by devon-ye** [assafelovic/gpt-researcher#264]
<img width="901" alt="image" src="https://github.com/assafelovic/gpt-researcher/assets/20877600/76d4f55e-7876-4bc0-a79c-3b4fc73624fd">

**Comment by assafelovic** [comment]
Hey this is due to the library we're using for Markdown. The issue should be raised in [md2pdf](https://github.com/jmaupetit/md2pdf)

**Comment by devon-ye** [comment]
> Hey this is due to the library we're using for Markdown. The issue should be raised in [md2pdf](https://github.com/jmaupetit/md2pdf)

thank you
