### ISSUE TITLE
Error when using OPEN AI API

### ISSUE THREAD

**Issue by tstanek390** [assafelovic/gpt-researcher#278]
I have an issue with running the client with open ai API, tried to export the key as shown and stated in docs, tried to create .env file, reinstalled the whole repo and deps several times, but I'm still getting this:

  File "/Users/admin/miniforge3/envs/research/lib/python3.11/site-packages/openai/_base_client.py", line 885, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.AuthenticationError: Error code: 401 - {'error': {'message': 'Incorrect API key provided: {sk-IvWw*****************************************gl9}. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}

The API key is working with all other services and tasks, but GPT-researcher, tried a dozen of newly generated keys too, with different companies. All without a success.
What could cause the issue?
Cheers

**Comment by assafelovic** [comment]
Great to hear!
