### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by IvanaRadicJean** [assafelovic/gpt-researcher#28]
Hi, I am very new, but I really like your project gpt-researcher and would like to install it. 

However, just when I start, with the line git clone https://github.com/assafelovic/gpt-researcher.git I get an error SyntaxError: invalid syntax and c in the word clone is highlighted. 

I appreciate your help.

**Comment by rotemweiss57** [comment]
Can you share a screenshot? i'll help you install it. using mac or windows?

**Comment by Ciaovic** [comment]
Hi, I'm experiencing the same issue - I'm using Windows.
I'm also a complete and utter novice re: coding, zero knowledge or experience.

<img width="730" alt="image" src="https://github.com/assafelovic/gpt-researcher/assets/139561494/a53f8524-58af-4565-9d9b-ef4d13d6d529">

**Comment by rotemweiss57** [comment]
Hi @Ciaovic and @IvanaRadicJean , please refer to this on how to clone: https://www.jcchouinard.com/clone-github-repository-on-windows/ 

In the meanwhile, feel free to try the beta version on our website: https://tavily.com/
