### ISSUE TITLE
permchain_agents example issue

### ISSUE THREAD

**Issue by VCSinc** [assafelovic/gpt-researcher#282]
Hello,

I've been having an issue when trying to run the "permchain_agents" example Python script. I've tried creating an "venv" with the requirements.txt modules installed as well as running the script in the "docker container." Both of them yield a similar error when trying to access the "permchain.connection_inmemory".

The following is the printout to the PowerShell in VS Code; I'm running Python 3.12.0 I receive the error both in venv and Docker

![image](https://github.com/assafelovic/gpt-researcher/assets/149602802/7b2e337a-2826-4143-85d4-68a6212cc414)

![image](https://github.com/assafelovic/gpt-researcher/assets/149602802/e6fc84a0-305a-4f4a-8fa7-eb297c3319ae)

**Comment by jeremi** [comment]
I'm having the same issue on Mac:
```
python test.py
Traceback (most recent call last):
  File "/Users/xxx/Projects/138-ai/gpt-researcher/examples/permchain_agents/test.py", line 5, in <module>
    from examples.permchain_agents.researcher import Researcher
  File "/Users/xxx/Projects/138-ai/gpt-researcher/examples/permchain_agents/researcher.py", line 1, in <module>
    from permchain.connection_inmemory import InMemoryPubSubConnection
ModuleNotFoundError: No module named 'permchain.connection_inmemory'
```

**Comment by jeremi** [comment]
It seems this class was removed from permchain

**Comment by assafelovic** [comment]
Hey thanks for raising it we'll look into it soon. If you can help or find the problem in the mean it'd be super appreciated!

**Comment by assafelovic** [comment]
Removed legacy permchain example from repo
