### ISSUE TITLE
Error in app.tavily.com (Uncaught (in promise) TypeError: Error in input stream)

### ISSUE THREAD

**Issue by vikram-s-narayan** [assafelovic/gpt-researcher#288]
Often I get the following error - "Uncaught (in promise) TypeError: Error in input stream".

To reproduce:
1. Use Firefox
2. On https://app.tavily.com/chat run a search like so: "Efficacy and safety of PRP (Platelet Rich Plasma) therapy on knee osteoarthritis"

Task never completes and we see the error.

See attached screenshot for further potential clues.

<img width="915" alt="Screenshot 2023-12-04 at 12 21 34 PM" src="https://github.com/assafelovic/gpt-researcher/assets/5373305/57699afd-b482-433a-99bf-2d1280babd31">

**Comment by assafelovic** [comment]
Thanks for raising this @vikram-s-narayan we're looking into. Probably due to a disconnection from the streaming. We'll verify and fix the issue asap!
