### ISSUE TITLE
unstable api.tavily.com/search

### ISSUE THREAD

**Issue by jeremi** [assafelovic/gpt-researcher#290]
Over the last hour I have been trying  
[gpt-researcher](https://github.com/assafelovic/gpt-researcher) but it seems the tavily is quite unstable. it sometimes return results, but so far, I have not been able to finish a research. There is always a search that fail. Should retry be implemented? Is there is a way to restart a research that has been interrupted?

Here is an example when it fail:
```
  File "/Users/xx/.virtualenvs/gpt-researcher/lib/python3.11/site-packages/tavily/tavily.py", line 47, in search
    return self._search(query, search_depth=search_depth, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xx/.virtualenvs/gpt-researcher/lib/python3.11/site-packages/tavily/tavily.py", line 41, in _search
    response.raise_for_status()  # Raises a HTTPError if the HTTP request returned an unsuccessful status code
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xx/.virtualenvs/gpt-researcher/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://api.tavily.com/search
```

**Comment by assafelovic** [comment]
Hey @jeremi due to high volumes we had some slow response times. After scaling up it should be better now, can you check?

**Comment by samgoodman** [comment]
EchoingTristandiscorder, this seems to be persistent

**Comment by garmanwu** [comment]
File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://api.tavily.com/search

I have the same problem.

**Comment by sameigen** [comment]
This is consistently happening to me as well, @assafelovic maybe worth reopening? Not sure if there is another issue open for this

**Comment by SimonB97** [comment]
Yep, same. @assafelovic this should be re-opened.

**Comment by seanmavley** [comment]
Can't even ping the API endpoint at the moment. Not sure what's happening with tavily. Yet it was working earlier the other day. 😓😮‍💨

It's kinda unstable since it's failure breaks the AI chain

🤦🏾‍♂️

**Comment by AryanPadmanabhan** [comment]
Happening to me as well. It works once and then breaks the next time. @assafelovic

**Comment by evangriffiths** [comment]
Also getting `requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://api.tavily.com/search`. Please re-open. I get this when using both a free and paid-for API key.

**Comment by nmcross** [comment]
Having the same issue. 
Error: 400 Client Error: Bad Request for url: https://api.tavily.com/search                                                                                                                                                                         
ERROR:    Exception in ASGI application

**Comment by randomclicks** [comment]
HTTPError: 502 Server Error: Bad Gateway for url: https://api.tavily.com/search

hey guys, u all keep getting this ?

**Comment by seanmavley** [comment]
@randomclicks Yep, randomly

**Comment by krunaln** [comment]
@randomclicks, Yes i am also facing this issue.

**Comment by ayushmore** [comment]
Same

**Comment by assafelovic** [comment]
Hey everyone, for Tavily issues please reach out at support@tavily.com. 
I'll update here if I know anything

**Comment by ArturNiklewicz** [comment]
I am facing the same issue. The first two times I tried to query with Tavily I got this error.

**Comment by zer0Tokens** [comment]
Same
