### ISSUE TITLE
Remote (non localhost) address support

### ISSUE THREAD

**Issue by shon** [assafelovic/gpt-researcher#30]
If one hosts it on public IP / address, then it throws the error `WebSocket connection to 'ws://localhost:8000/ws' failed:`
Changing `client/scripts.js` localhost value to my host's IP worked but obviously, it won't work for next update.
I started the app `uvicorn main:app --reload --host 0.0.0.0`
Can we support remote addresses please?

**Comment by jortegac** [comment]
Can you try with the following?

`uvicorn main:app --host 0.0.0.0 --port 8000`

**Comment by rotemweiss57** [comment]
Hi @shon it is in my backlog. feel free to work on it and add a pull request!

**Comment by shon** [comment]
> Hi @shon it is in my backlog. feel free to work on it and add a pull request!

Done. Have a look https://github.com/assafelovic/gpt-researcher/pull/63
And thanks for this amazing tool
