### ISSUE TITLE
Finetuning research: output length, type of report(?)

### ISSUE THREAD

**Issue by stevenbaert** [assafelovic/gpt-researcher#301]
Hi,

Love the project! Though I would like to make GPTResearcher to have a longer output and do more in depth research. Also I like to influence the way of outputting. Not sure what the output formats exactly mean, didn't find documentation (difference research/resource/outline report) on them yet(?)

Tried to ask GPTResearcher to give me that answer, but it couldn't give me that yet :-)

Thanks!
Steven

**Comment by assafelovic** [comment]
Hey @stevenbaert ! You can change the "report_format" in the config.py file to any format you'd like. It's set to APA by default. Check the doc here for more info: https://docs.tavily.com/docs/gpt-researcher/config

**Comment by stevenbaert** [comment]
Thanks! But if I use the pypi package install, then where is that config file?

**Comment by assafelovic** [comment]
You can add a path to your own JSON file
