### ISSUE TITLE
Exception in ASGI application and TimeoutError

### ISSUE THREAD

**Issue by gkgo** [assafelovic/gpt-researcher#303]
Hello, I have the following problem with gpt4, the connection timeout occurs when I turn off the proxy and turn on the proxy, what should I do to solve it?
![Uploading bug.png…]()

**Comment by assafelovic** [comment]
Hey @gkgo can you resend the bug image? Isn't downloaded properly.

**Comment by gkgo** [comment]
ok
![bug](https://github.com/assafelovic/gpt-researcher/assets/91817417/da99792b-edfa-45a6-b710-cce6294921a8)

**Comment by assafelovic** [comment]
Staleness
