### ISSUE TITLE
agen.run issue

### ISSUE THREAD

**Issue by scooter7** [assafelovic/gpt-researcher#31]
Hi,

When trying to run the app, I get the following message in my command prompt:

 line 8, in <module>
    from agent.run import WebSocketManager
ModuleNotFoundError: No module named 'agent.run'; 'agent' is not a package

Thanks!

**Comment by rotemweiss57** [comment]
Hi @scooter7, can you provide a screenshot of how you executed the script?

**Comment by scooter7** [comment]
Hi @rotemweiss57 ,

After exporting/setting my openai key, I ran uvicorn main:app --reload and received the following:

![Screenshot 2023-07-14 095257](https://github.com/assafelovic/gpt-researcher/assets/114838/54cda518-13d5-4e21-914b-dfc443d1034b)

Thanks!

**Comment by scooter7** [comment]
Hi @rotemweiss57 ,

I cloned again and encountered the exact same error.

I have pasted in some warnings that I received upon installation that might shed some light on what is happening.

Thanks!
![Screenshot 2023-07-18 084425](https://github.com/assafelovic/gpt-researcher/assets/114838/29ea2696-08ce-48a3-a60f-358f3e395eb9)

**Comment by assafelovic** [comment]
Hi @scooter7 is this still happening or have you resolved it?
