### ISSUE TITLE
(Version Error) duckduckgo_search.exceptions.duckduckgosearchexception: _get_url() 

### ISSUE THREAD

**Issue by datafyresearcher** [assafelovic/gpt-researcher#316]
Error: `duckduckgo_search.exceptions.DuckDuckGoSearchException: _get_url()  https://links.duckduckgo.com/d.js ratelimitexception: _get_url() https://links.duckduckgo.com/d.js ratelimiterror: resp.status_code==202`

Installed Package: `duckduckgo_search==3.9.8`

To resolve this issue on Windows 11 Pro or any operating system, update the `duckduckgo_search` package to version 4.1.1 or higher. E.g. Run this `python -m pip duckduckgo_search==4.1.1` script in terminal. This update should automatically address the mentioned error.

**Comment by datafyresearcher** [comment]
![image](https://github.com/assafelovic/gpt-researcher/assets/142796870/b0dac6c7-c42f-41bf-931b-1b4e05e2f49a)

**Comment by assafelovic** [comment]
Thanks for raising this @datafyresearcher . I've updated DDGo to latest version
