### ISSUE TITLE
Support OpenAI API proxy

### ISSUE THREAD

**Issue by Plus-xu** [assafelovic/gpt-researcher#317]
Dear Contributors,
Due to some countries being unable to directly access the OpenAI API or use self-hosted reverse-engineered ChatGPT proxies, there is a desire to support the use of a custom OpenAI API URL. 
Thank you!

**Comment by assafelovic** [comment]
Hey @Plus-xu , you can check out other alternatives to OpenAI via the Langchain Adapter we support. See here for more details: https://python.langchain.com/docs/integrations/adapters/openai
