### ISSUE TITLE
Provide other planner agents

### ISSUE THREAD

**Issue by lrq3000** [assafelovic/gpt-researcher#318]
Currently the implemented planner agent(s) aim to weight equally all 20 sources and more or less averages them if I understood correctly, the idea being that "The more sites we scrape the less chances of incorrect data. We are scraping 20 per research, the chances that they are all wrong is extremely low." because "In research, people also tend towards biases as most have already opinions on the topics they research about. This tool scrapes many opinions and will evenly explain diverse views that a biased person would never have read."

This assumption is clearly a bias of the [argument to moderation](https://en.m.wikipedia.org/wiki/Argument_to_moderation) more commonly known in journalism as the [view from nobody](https://en.m.wikipedia.org/wiki/Journalistic_objectivity#View_from_nowhere). Here's a relevant excerpt:

> Journalism scholars and media critics have used the term view from nowhere to criticize journalists' attempt to adopt a neutral and objective point of view in reporting, as if reporting "from nobody's point of view". Jay Rosen has argued that journalists may thereby disinform their audience by creating the impression that they have an authoritative impartiality between conflicting positions on an issue.[30][31] Jeremy Iggers quoted Richard S. Salant, former president of CBS News, who stated: "Our reporters do not cover stories from their point of view. They are presenting them from nobody's point of view."[32] Iggers called Salant's assertion "plainly incoherent, as is the notion of observations untouched by interpretation".[32] Rosen has used the term to criticize journalists who hide behind the appearance of journalistic objectivity so as to gain an unearned position of authority or trust with their audience; he advocates for transparency as a better way of legitimately earning trust.[30][31] (...) Writer Elias Isquith argues in a 2014 article for Salon that "the view from nowhere not only leads to sloppy thinking but actually leaves the reader less informed than she would be had she simply read an unapologetically ideological source or even, in some cases, nothing at all".[34]

Case in point, I am a researcher specialized in clinical and neurocomputational consciousness and AI research, and I can guess what the model will likely output, and how wrong it will be. I'm pretty sure this will be "worse than nothing at all" as Elias Isquith put it. Because for cutting edge research topics which are not mainstream, the most accurate info is rarely on websites, and it's even worse for some topics that tend to stimulate the imagination of crowds such as consciousness.

But this is also true for any research topic. I don't know a single topic in clinical research where you won't find an aberrant info on the first results you will get on google. What I mean is that for any of these topics, I am pretty sure to find an info in the top search results that is actually the opposite of what should be done according to the latest evidence or guidelines.

So with the current planner algo, this project is doomed to always provide only superficial overviews that are no better than what an intern would be able to do (and that's the best case scenario imho).

This is because it seems the project's author(s) have a limited experience and likely no training in research. This i think this issue may be fixable to some extent by working in partnershig with some researchers (not me, i don't have time). Because it seems clear there is a misconception about what research entails, and the current project does nothing of the sort.

I would suggest to read more about the [scientific method(s)](https://en.m.wikipedia.org/wiki/Scientific_method). There are many different criteria, such as verifiability, which is what you already implemented. Another is reproducibility. What this project is trying to achieve more specifically is a literature review, and there are several proposed methods for that, so i think you will find very interesting algos if you search for heuristics and algorithms for scientific reviews (scholar.google.com is a great aggregator). Also there is the whole field of metascience. 

Anyway the bottom line is that there is no unbiased data source, and then any processing at any point in the chain (not you, i mean all the analyses done by scientists, the choice to publish ie file drawer bias, and even the choice of hypotheses to investigate are biased by fundings and publish or perish incentives) adds further biases. So I think this project can grow a lot in usefulness if it changes from a perpective of trying to reach an impossible objectivity, to instead aim for methodological systematic research with the angle chosen by the user.

Hopefully my input can be useful, I certainly hope this project to be successful, it has a lot of potential, and it's awesome it is opensource.

**Comment by assafelovic** [comment]
Hey @lrq3000 thanks for this comprehensive feedback! To be clear, research in the context of GPT Researcher does not refer to academic research. It refers to many kinds of online research such travel, finance, marketing, business analysis, etc. For example "top hotels in NYC" or "Top stocks to buy in the semiconductor industry". The idea of GPT Researcher is to do the **online research** for you. Imagine wanting to learn about a political topic. GPT Researcher's claim is to aggregate from many sources so that the final report would be less biased than reading the first 3 articles on Google. With that said, GPT Researcher can also be used by passing specific source URLs which can be better used for academic research assuming academic sources.

**Comment by lrq3000** [comment]
Thank you for your reply assafelovic. It seems the API changed since the first announcements on [reddit](https://www.reddit.com/r/learnmachinelearning/comments/14vvtqf/excited_to_introduce_gptresearcher/) where there was an "Academic Research Agent", it seems it is not present anymore.

Anyway I am not sure I understand the concept of "academic research". If you mean by that the inclusion of academic sources in search results, then yes I would be favorable but that's not my suggestion, it's the suggestion of someone else in another issue.

My suggestion here is that researching, which can also be reframed as a problem of information pertinence ranking, is a well studied problem scientifically and I'm sure you can find more advanced algorithms published in papers that can drastically improve the effectiveness of your tool.

**Comment by lrq3000** [comment]
Edit: yes I suggested the scientific method indeed so that's likely what you refer to. I wasn't clear enough in my initial suggestion, sorry, I am now reframing it more clearly. I was suggesting this as a methodological/algorithmic inspiration but not to make this tool an academic only research tool. There are other approaches of course.
