### ISSUE TITLE
Getting ImportError when building docker image

### ISSUE THREAD

**Issue by mikkelkrogsholm** [assafelovic/gpt-researcher#320]
ImportError: cannot import name 'tracing_enabled' from 'langchain_core.tracers.context' (/usr/local/lib/python3.11/site-packages/langchain_core/tracers/context.py)

**Comment by assafelovic** [comment]
Thanks for raising it @mikkelkrogsholm let us take it with our partners and Langchain and update asap!

**Comment by assafelovic** [comment]
Fixed with Langchain
