### ISSUE TITLE
error while accessing app.tavily.com

### ISSUE THREAD

**Issue by xysDavid** [assafelovic/gpt-researcher#324]
<img width="777" alt="image" src="https://github.com/assafelovic/gpt-researcher/assets/2630813/483d969e-2a1e-490b-84ea-219c5fc3eb25">

**Comment by assafelovic** [comment]
Hey @xysDavid can you please share more information about where are you opening the app and whether you've tried other browsers?

**Comment by xysDavid** [comment]
1. Where I am open this app: China
2. Other browsers: Safari, still not work.

**Comment by xysDavid** [comment]
Could you please let me know if there has been any progress or if there is any additional information you need from me?

Thank you for your time and help with this issue.

**Comment by assafelovic** [comment]
Hey, not sure why this isn't working in China since we can't reproduce here. We've tested in several browsers and geolocations using proxies.
