### ISSUE TITLE
openai.error.InvalidRequestError: The model: `gpt-4` does not exist

### ISSUE THREAD

**Issue by neoOpus** [assafelovic/gpt-researcher#34]
I thought this will work with GPT-3.5 and also thought that OpenAI made it possible to anyone to use GPT-4 API but after several hours tinkering with this I am not able to get it to work, I see the webpage but it keeps throwing an error after another (fixed them all) but I am unable to make it work because of this error

**Comment by thinkJD** [comment]
I have the same problem.

**Comment by wwzeng1** [comment]
Hi! I’m one of the founders of Sweep, a github app that solves issues(like small bugs) by writing pull requests. 
This looks like a good issue for Sweep https://github.com/sweepai/sweep to try. It might need more details from the maintainers though.
We have onboarding [instructions here](https://github.com/sweepai/sweep/blob/main/README.md#-getting-started), I’m also happy to help you onboard directly :)

**Comment by bcgit2023** [comment]
I have the same error "openai.error.InvalidRequestError: The model: `gpt-4` does not exist" just stopped.

**Comment by jortegac** [comment]
The model is configured here

https://github.com/assafelovic/gpt-researcher/blob/master/config/config.py#L25

By accessing an enviroment variable
`self.smart_llm_model = os.getenv("SMART_LLM_MODEL", "gpt-4")`

If you are having issues with access to `gpt-4`, you can set an environment variable with a model name that you do have access to e.g. `gpt-3.5-turbo`

For example:
`export  SMART_LLM_MODEL="gpt-3.5-turbo"`

**Comment by madiha1ahmed** [comment]
Hi!

By making the following modifications, I was able to resolve the issue:

1. In **gpt-researcher/config/config.py**, substitute in line 25 **"gpt-4"** with **"gpt-3.5-turbo-16k"**
2. In **gpt-researcher/config/config.py**, substitute in line 27: **8000** with **4000**

![Screenshot (1008)](https://github.com/assafelovic/gpt-researcher/assets/56754113/0e90c4a0-80c0-46cb-8a3f-4adf3dec62bf)

Upon executing this modified script, I encountered another error: "**json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 58)**". So, if you also get the same error, all you need to do is:

In **gpt-researcher/agent/research_agent.py** line 92, substitute **"return json.loads(result)"** with **" return result"**. This avoids the double-parsing as result itself is a JSON Object.

Hope this helps!

**Comment by bcgit2023** [comment]
@madiha1ahmed I did it your way and it worked. thanks!

**Comment by OumYacout** [comment]
It works for me now. Thanks
