### ISSUE TITLE
[Documentation]: Change 'PermChain' to 'LangGraph'

### ISSUE THREAD

**Issue by SimonB97** [assafelovic/gpt-researcher#344]
Hi,

just wanted to mention that I saw on [this](https://docs.tavily.com/docs/gpt-researcher/agent_frameworks) docs-page that you call the 'LangGraph'-prject 'PermChain'.
I guess this is because it got re-named in the meantime. The link to the LangGraph-repo is correct though.

P.S.: thanks for your cool projects !

**Comment by assafelovic** [comment]
Thanks we've removed the project for now until we rebuild it using the proper LangGraph new architecture
