### ISSUE TITLE
Seperate Token Limit for Inferencing & Writing

### ISSUE THREAD

**Issue by murtaza-nasir** [assafelovic/gpt-researcher#356]
I want the smart model (GPT 4 in my case) to be able to read large amounts of text ( > 4096 tokens), but the model has a limit of 4096 tokens for output. Can we get separate token limits for these? Since to get it to work, I have to set the smart token limit to 4096. My apologies if the smart model isn't used to read anything, in which case please disregard this message.

**Comment by assafelovic** [comment]
Hey @murtaza-nasir can you further elaborate on this? We use gpt4 for writing but it needs to use inference for context + generating the final output.

**Comment by murtaza-nasir** [comment]
My apologies, I believe I didn't really think this message through. For some reasons it made sense to me at the time, since I was getting an error that gpt4 can only support 4096 output tokens. But I believe to have gpt4 do most of the reading all I have to do is assign it as the fast model too in the config file. Not sure why I didn't do this at that time.
