### ISSUE TITLE
Enable editing the api-keys not from the env-vars

### ISSUE THREAD

**Issue by uripeled2** [assafelovic/gpt-researcher#359]
Sometimes, it is useful to enter the API key into the method explicitly; for example, it can enable the app to use multiple API keys and every time use a different API key.
I am referring to the OpenAI API key, Tvaily API key, etc.

**Comment by assafelovic** [comment]
Thanks we've added it to our roadmap

**Comment by uripeled2** [comment]
Why did you close it and mark it as completed?
