### ISSUE TITLE
Move to pypdf

### ISSUE THREAD

**Issue by TashaSkyUp** [assafelovic/gpt-researcher#36]
because of #22 #25 #16
suggestion:
- Drop md2pdf and use this insead
- https://github.com/py-pdf/pypdf

**Comment by rotemweiss57** [comment]
Hi, did you try running it with this library? While examining some options I have tried, but it wasn't so stable as well. 

anyway I'll dig into that, thank you!

**Comment by TashaSkyUp** [comment]
Thank you @rotemweiss57 sorry I have not been able to test it!
