### ISSUE TITLE
Feature Request - Implementation of Follow-Up Question Functionality

### ISSUE THREAD

**Issue by magedhelmy1** [assafelovic/gpt-researcher#366]
Inquiring about the possibility of adding a feature that allows for follow-up questions to be asked for clarification or to obtain detailed information on specific parts of the report or start a new report.
This feature is aimed at enhancing the user's ability to interact more dynamically and acquire precise information.

#### Key Feature Requests:
1. **Follow-Up Question Prompt:** After the initial report, the system should prompt the user if they need further clarification or have additional questions related to the initial query.
2. **Contextual Recognition:** The system should maintain context between the initial query and the follow-up question to provide relevant and accurate responses.

### Use Case Scenario:
1. A user queries a software-related report.
2. The system provides an initial report.
3. The user is then prompted if they need further clarification or have more questions regarding the report.
4. The user submits a follow-up question that is contextually tied to the original report.
5. The system recognizes the context and provides a relevant and detailed follow-up response.

**Comment by jenochs** [comment]
Thought son implementation options for issue:

1. Follow-Up Question (Ask a Question)
    - Implementation option 1 (use innerhtml as context - copy to clip board logic)
       -This would grab the report txt as input into a custom report
    - Implementation option 2 (use url to pdf as context)
       -This would pass the url of the pdf report generated to custom report.
     - Add button (Ask a question)
2. Follow-Up Question (Update Research)
      - Implementation option (use pdf url and report references to regenerate report with new query)
      - pass pdf url along with reference urls to report generator to update research and maintain context
<img width="971" alt="Screenshot 2024-02-26 at 7 49 04 PM" src="https://github.com/assafelovic/gpt-researcher/assets/28722390/313a6cd3-e7ac-4784-be50-d88dbb59096b">

**Comment by assafelovic** [comment]
@jenochs this is awesome. how about creating a PR for this?

**Comment by renzit** [comment]
nice feature, I need this, 
before I start doing it I wanted to know if it is already advanced in any way? @jenochs 
thank you

**Comment by assafelovic** [comment]
Hey would love a PR for this. Very much needed!

**Comment by mdlmarkham** [comment]
Excellent - ideally there would be a robust follow-up / critique that could lead to a re-generation of the output.

**Comment by ElishaKay** [comment]
Now available when running the full-stack app with NextJS 🥳

You can follow [these guidelines to run locally](https://docs.gptr.dev/docs/gpt-researcher/frontend/frontend#run-the-nextjs-react-app-with-docker)
