### ISSUE TITLE
Loosen requirements

### ISSUE THREAD

**Issue by martolini** [assafelovic/gpt-researcher#367]
The requirements are very strict, any chance you need exactly uvicorn==0.24.0.post1? Would love to use this together with some other packages, but it's quite difficult with these requirements.

Thanks!

**Comment by assafelovic** [comment]
@martolini done! Pull latest version

**Comment by martolini** [comment]
Fantastic! Will this make its way to pypi, too? :)

**Comment by assafelovic** [comment]
@martolini it's right here: https://pypi.org/project/gpt-researcher/ :)
