### ISSUE TITLE
customize the OpenAI API URL

### ISSUE THREAD

**Issue by stan1233** [assafelovic/gpt-researcher#378]
Hello,

May I ask if there is a simple way to customize the OpenAI API URL, as some regions cannot access OpenAI services?
like this:

export OPENAI_BASE_URL={XXX}

Or add to config.py

Thank you!

**Comment by assafelovic** [comment]
Hey @stan1233 can you please share more or an example of how you expect this to work? We're using Langchain for this

**Comment by assafelovic** [comment]
You should be able to achieve the same by passing the OPENAI_API_BASE env var. Lmk that it works for you

**Comment by virologist** [comment]
@stan1233 Hi, Luo, I got the same situtation with you. How did you customize the OpenAI URL with "https://xxxxx.com/v1"? Did you get it?
