### ISSUE TITLE
follow_up_questions is always "null"

### ISSUE THREAD

**Issue by EIKINAKAYAMA** [assafelovic/gpt-researcher#383]
Even I follow as your example query, follow_up_questions is still "null"

<img width="1138" alt="スクリーンショット 2024-03-09 19 38 48" src="https://github.com/assafelovic/gpt-researcher/assets/65437818/484bc583-02ca-4bda-a565-adf0fa37836f">

**Comment by EIKINAKAYAMA** [comment]
@assafelovic 
Hi, is there any update??

**Comment by assafelovic** [comment]
@EIKINAKAYAMA please reach out to rotem@tavily.com . This opensource is not related to the API
