### ISSUE TITLE
Tavily keeps getting back to me by saying "there are no search results for your question"

### ISSUE THREAD

**Issue by ArmanKabiri** [assafelovic/gpt-researcher#393]
It's been a couple of days I am not getting any correct response back no matter how simple the input query is. Here are some examples:

```
self.tavily_client.qna_search('when did russia war start?')
Response: 'Based on the data provided, there are no results available regarding the start date of a war involving Russia.'

self.tavily_client.qna_search('usa president')
Response: 'Based on the information available, there is no specific data provided regarding the current USA president.'
```

Any idea?

**Comment by proy9714** [comment]
Maybe try a different retriever? SerpAPI seems to work well for most use cases

**Comment by ArmanKabiri** [comment]
Ahh I see. I've installed Tavily through pip. Is there a way to change the config to use other retrievers in this case?

**Comment by proy9714** [comment]
You can add the SEARCH_RETRIEVER key in your env and point it to serp....and you also need to specify your SERP_API_KEY in that case.

(Please double check the proper env keys and values)

Looking at the config.py file and the retriever files  should give you an idea!

**Comment by assafelovic** [comment]
Tavily search should be back to normal
