### ISSUE TITLE
OSError: [Errno 22] Invalid argument:

### ISSUE THREAD

**Issue by Drehabaziz** [assafelovic/gpt-researcher#40]
OSError: [Errno 22] Invalid argument: './outputs/Diagnostic criteria for DKA/research-What is the diagnostic criteria for DKA?.txt'

**Comment by rotemweiss57** [comment]
Hi can you share a bit more details? at what point did you receive this?

**Comment by Drehabaziz** [comment]
I get this message which suggests that there is no txt file following the search and scraping functions are finished

  File "C:\gpt-researcher-master\agent\run.py", line 50, in run_agent
    await assistant.conduct_research()
  File "C:\gpt-researcher-master\agent\research_agent.py", line 138, in conduct_research
    research_result = await self.run_search_summary(query)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\gpt-researcher-master\agent\research_agent.py", line 123, in run_search_summary
    os.makedirs(os.path.dirname(f"./outputs/{self.directory_name}/research-{query}.txt"), exist_ok=True)
  File "<frozen os>", line 225, in makedirs
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: './outputs/What is the diagnostic criteria for DKA?'

**Comment by rotemweiss57** [comment]
Hi @Drehabaziz can you update the project to the latest commit and let me know if the problem persists?

**Comment by Drehabaziz** [comment]
Hi @rotemweiss57 It is resolved, Many thanks
