### ISSUE TITLE
ModuleNotFoundError: No module named 'gpt_researcher.retrievers.serpapi'

### ISSUE THREAD

**Issue by joaomnmoreira** [assafelovic/gpt-researcher#407]
Hi!

I've the following setup:
- Venv: _Python 3.10.12_
- PIP: _gpt-researcher             0.1.0_

And i obtain this error:
"ModuleNotFoundError: No module named 'gpt_researcher.retrievers.serpapi'"

Neither in https://pypi.org/project/gpt-researcher/ and https://github.com/assafelovic/gpt-researcher/blob/master/requirements.txt address any Google SERP package dependency.

I have tried installing: _pip install google-search-results_, but no good!

I can install gpt-researcher in a different project, but it's not the goal here.

Can you help?

PS - Congrats! Amazing product you built here!

Best,
João Moreira

**Comment by pedrorocha-net** [comment]
Just had the same issue, earlier today, but I guess it might be because the gpt-researcher pip package is outdated. The project is at 0.1.5 while package at 0.1.0, so some reference might had broken.

**Comment by JSantos1985** [comment]
It seems that the serpapi retriever is currently missing from the PyPi release, even though it references it. You can temporarily work around this getting this folder and its contents from the repo:
https://github.com/assafelovic/gpt-researcher/tree/master/gpt_researcher/retrievers/serpapi

And putting it in /gpt_researcher/retrievers/ in your venv's site-packages folder.

**Comment by joaomnmoreira** [comment]
I confirm it worked just like @JSantos1985 suggested. Thanks!
