### ISSUE TITLE
ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by R3habDroid** [assafelovic/gpt-researcher#41]
root@jk-prome:/home/gpt-researcher# uvicorn main:app --reload
INFO:     Will watch for changes in these directories: ['/home/gpt-researcher']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [1706093] using StatReload
INFO:     Started server process [1706095]
INFO:     Waiting for application startup.
INFO:     Application startup complete.

telnet 127.0.0.1:8000 works but no response when accessing pages on port 8000.

**Comment by rotemweiss57** [comment]
Hi can you share a screenshot?
