### ISSUE TITLE
 Invalid argument provided to Gemini: 400 API key not valid. 

### ISSUE THREAD

**Issue by ByteNestor** [assafelovic/gpt-researcher#410]
Hi,

 I obtained this error with v0.1.6 when using Gemini modle.

> File "gpt-researcher-v.0.1.6/.venv/lib/python3.12/site-packages/langchain_google_genai/chat_models.py", line 179, in _achat_with_retry
>     raise ChatGoogleGenerativeAIError(
> langchain_google_genai.chat_models.ChatGoogleGenerativeAIError: Invalid argument provided to Gemini: 400 API key not valid. Please pass a valid API key. [reason: "API_KEY_INVALID"
> domain: "googleapis.com"
> metadata {
>   key: "service"
>   value: "generativelanguage.googleapis.com"

I have checked the GEMINI_API_KEY with the following commands in the terminal and it worked successfully.

```
curl \
  -H 'Content-Type: application/json' \
  -d '{"contents":[{"parts":[{"text":"Write a story about a magic backpack"}]}]}' \
  -X POST 'https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key=YOUR_API_KEY'
```

the config.py was modified as follows:
```
        self.llm_provider = os.getenv('LLM_PROVIDER', "google")
        self.fast_llm_model = os.getenv('FAST_LLM_MODEL', "gemini-pro")
        self.smart_llm_model = os.getenv('SMART_LLM_MODEL', "gemini-pro")
```
Any help?

**Comment by assafelovic** [comment]
@proy9714 can you verify that the latest PR works as expected?

**Comment by proy9714** [comment]
Yes, the PR works as expected. I tried to run it again with my own GEMINI_API_KEY and setting llm_provider to "google" and it gave me the correct output.

![image](https://github.com/assafelovic/gpt-researcher/assets/37247296/9456fe92-004b-4db4-803d-b9bc5cbd9306)

**Comment by assafelovic** [comment]
Thanks @proy9714 closing this issue 🙏
