### ISSUE TITLE
How to filter by "search topic" in API request?

### ISSUE THREAD

**Issue by jpzhangvincent** [assafelovic/gpt-researcher#420]
It seems the API playground allows to filter by  "search topic", like filtering by news, which is more useful for my use case. But I didn't see it from the API documentation. Is it a new feature that would be added soon? Or I miss something..

**Comment by assafelovic** [comment]
Hey @jpzhangvincent topics are not support. Generally please reach out at support@tavily.com since this is not related to the opensource. thanks!

**Comment by jpzhangvincent** [comment]
Hmm @assafelovic so the filter is not supported as part of the API input? Is it a paid feature? And the documentation is missing - https://docs.tavily.com/docs/tavily-api/Topics/news
