### ISSUE TITLE
Error: TypeError - unsupported operand types

### ISSUE THREAD

**Issue by girithodu** [assafelovic/gpt-researcher#425]
Issue Description:
Encountering a TypeError with unsupported operand types while attempting to subtract an 'int' from 'simsimd.OutputDistances'. This error occurs right after executing the operation to retrieve relevant content based on the query "what team may win the NBA finals?".

Error Details:
Received error message:
TypeError: unsupported operand type(s) for -: 'int' and 'simsimd.OutputDistances'

Steps to Reproduce:

Execute the operation to retrieve relevant content based on the query "what team may win the NBA finals?".
Observe the TypeError mentioned above.
Expected Behavior:
No TypeError should occur, and the operation should execute successfully without any errors.

**Comment by assafelovic** [comment]
closing due to staleness
