### ISSUE TITLE
The examples on https://docs.tavily.com and examples/sample_report.py do not work anymore

### ISSUE THREAD

**Issue by Handschrift** [assafelovic/gpt-researcher#426]
In version 0.2.0 changes were made to the agents.py file.

the run() method was renamed to conduct_research() in [this commit](https://github.com/assafelovic/gpt-researcher/commit/5253bc67e255c3c2c5b5beb2824adcae12991461). 

Also the function doesn't return any kind of data anymore so that the variable "report" will be None in this example:

```python
    researcher = GPTResearcher(query=query, report_type=report_type, config_path=None)
    report = await researcher.run()
    return report
```

How do I run a detailed_report and write the contents of the report in a variable? I couldn't find any other kind of documentation about this on tavily.com or on the github repository.

**Comment by assafelovic** [comment]
Fixed here: https://github.com/assafelovic/gpt-researcher/pull/428

Thanks for raising!
