### ISSUE TITLE
AzureOpenAI Configuration Error

### ISSUE THREAD

**Issue by deb1305** [assafelovic/gpt-researcher#427]
I am trying to configure azure openai llm. After setting the config.py file, I am getting below error:

ERROR:    Exception in ASGI application

Can someone share the config.py with respect to azure openai llm

**Comment by assafelovic** [comment]
@norrisp90 can you give a hand here? I don't have an Azure account

**Comment by norrisp90** [comment]
@assafelovic Same issue as #422 . Will work on it in #422 .

**Comment by deb1305** [comment]
that passed through, but now i am getting below error 
raise DuckDuckGoSearchException(f"_get_url() {url} {type(ex).__name__}: {ex}")
duckduckgo_search.exceptions.DuckDuckGoSearchException: _get_url() https://duckduckgo.com RequestsError: Failed to perform, ErrCode: 60, Reason: 'SSL certificate problem: unable to get local issuer certificate'. This may be a libcurl error, See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Note: I am using Tavily api key

**Comment by norrisp90** [comment]
> that passed through, but now i am getting below error raise DuckDuckGoSearchException(f"_get_url() {url} {type(ex).**name**}: {ex}") duckduckgo_search.exceptions.DuckDuckGoSearchException: _get_url() https://duckduckgo.com RequestsError: Failed to perform, ErrCode: 60, Reason: 'SSL certificate problem: unable to get local issuer certificate'. This may be a libcurl error, See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
> 
> Note: I am using Tavily api key

@deb1305 This looks like a seperate issue. Suggest you open new issue for it.

**Comment by assafelovic** [comment]
Fixe here: https://github.com/assafelovic/gpt-researcher/pull/432
