### ISSUE TITLE
Question about the compressor library

### ISSUE THREAD

**Issue by djuillard** [assafelovic/gpt-researcher#430]
Hi,

I have used and then studied in details how GPT_researcher works, and I am impressed about the great job ! The architecture et the sequencing are really smart. Congratulations, this is SMART !!!

Now, I want to use GPT Researcher to establish a very precise market study, and to do so, I intend to increase the number of subqueries, et the number or scrapped_content_results coming from the scrape_sites_by_query. I already made a few tests, it works fine, it costs more API money, but that is understandable when you seek for accuracy (and better quality). Yet, there are some generated context that I do not understand well, especially when it comes to the langchain compression library (I am not familiar with langchain, and even if I tried to read the lanchain.retrievers.document_compressors doc, I must admit that I did not understand anything more !!!). If I am not mistaken, this compressor implementation is not really RAG; it is close to it but scrapped websites are not actually stored into a vector database. And the generated context is not made out of a RAG questioning, but it is made thanks to a vectorization of the scrapped_websites, which is then questioned by the Search API Retriever (Tavily in my case), and Tavily is then creating the output. Is that right ? 

Why did you choose to go for that direction ? I mean, I don't think the search API Retriever is not a good option (and it seems to work fine), but wouldn't it make sense to implement a real RAG architecture, which would enable us to enlarge the scope of scrapped websites, and get very precise context coming from each subqueries based on RAG ? 

That is a simple questions. Maybe there are obvious answers, and sorry for asking then. Maybe the reason is that each "Reseach" is supposed to be made on totally different topics, and in that case, implementing RAG maye have been considered as pointless because it  is just a "one-time" use for the purpose of each research, and then it can be deleted. 

Anyway, this compression thing seems for me to be the only concern in this whole project because it may reduce the accuracy of the final report in the end.

PS : having a vector DB could also be used at the same time to load proprietary document, as already mentioned here #379 .

Thanks in advance for your answers,

**Comment by assafelovic** [comment]
Hey @djuillard, thanks for bringing this up! Just to clarify, this IS a RAG architecture. And the compressor does use a vector DB logic. Basically we chunk all documents -> embed them -> retrieve only the relevant ones to the query. This is done to optimize for context with only the most relevant content. I do agree though that retrieval hit rate might be lower than simply passing most of the scraped content, and definitely requires more refinement. Happy to hear suggestions or PRs that can improve it! As for local documents, we're actually working on one here by the one and only @proy9714 : https://github.com/assafelovic/gpt-researcher/pull/429

**Comment by djuillard** [comment]
Thanks for your answer and for the clarification. OK, I understand better. This IS RAG, with vector logics, but not based on vector db at this stage, because not immediately necessary. 
I will check whether I can contribute, maybe while adding a vector DB like qdrant with asynchronous capabilities.
