### ISSUE TITLE
How to configure to use Tavily as Search Engine

### ISSUE THREAD

**Issue by deb1305** [assafelovic/gpt-researcher#434]
raise DuckDuckGoSearchException(f"_get_url() {url} {type(ex).name}: {ex}")
duckduckgo_search.exceptions.DuckDuckGoSearchException: _get_url() https://duckduckgo.com/ RequestsError: Failed to perform, ErrCode: 60, Reason: 'SSL certificate problem: unable to get local issuer certificate'. This may be a libcurl error, See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Though I have configures Tavily API Key, still DuckDuckgo search is being used

**Note: I am using Tavily api key**

**Comment by skalingclouds** [comment]
Similar issue, however i get rate limit. it should be using the Tavily key. I have it in the .env and in exported, seems to still use duck duck go

**Comment by assafelovic** [comment]
Ddgo is used as fallback if Tavily fails. Did you manage to validate that you can search queries with Tavily? If not, consider another search provider

**Comment by deb1305** [comment]
@assafelovic I am getting this error when i am trying my Mac.
Error: HTTPSConnectionPool(host='api.tavily.com', port=443): Max retries exceeded with url: /search (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')))

Why it is throwing SSL certificate error. Note I am running inside VPN

**Comment by deb1305** [comment]
Its working now.. Please close this issue.

**Comment by deb1305** [comment]
Tavily is working. Thanks @assafelovic
