### ISSUE TITLE
Possibility to exclude specific websites 

### ISSUE THREAD

**Issue by Handschrift** [assafelovic/gpt-researcher#436]
As far as I know there isn't an option to exclude websites from the research.

As a researcher I sometimes want to blacklist specific sources (e.g. Wikipedia.org) because of scientific requirements.

It is possible to pass source urls but they have to be specific and this is not applicable for my use case.

My proposal is to allow to blacklist websites:

```python
blacklist_urls = [
"https://wikipedia.org",
"https://nytimes.com"
"https://news.google.com"
]
```

So that during the research, search results from wikipedia, nytimes and google news will be ignored.

I think I saw that the tavily api already has a property to disallow websites. But I am unsure about the other search providers.

Would that be possible to implement?

**Comment by assafelovic** [comment]
Hey @Handschrift I assume most search APIs support it but GPT Researcher currently doesn't have that in the configuration to pass down to the search providers. We will put it on our roadmap but also happy to see contributions!

**Comment by seannetlife** [comment]
Another approach might be to allow for a custom search retriever to be provided.

**Comment by assafelovic** [comment]
That already exists @seannetlife . We have plenty of integrations as seen here: https://github.com/assafelovic/gpt-researcher/tree/master/gpt_researcher/retrievers
