### ISSUE TITLE
How to execute 'resource_report'?

### ISSUE THREAD

**Issue by Italosayan** [assafelovic/gpt-researcher#437]
Is there anyway of making the "resource report" available again? The detailed report provides more context and a structured story however, for me the main feature of the GPT researcher was the calification/rating of the source.

I have noticed that in utils enum.py the report is still available:

```
class ReportType(Enum):
    ResearchReport = 'research_report'
    ResourceReport = 'resource_report'
    OutlineReport = 'outline_report'
    CustomReport = 'custom_report'
    DetailedReport = 'detailed_report'
    SubtopicReport = 'subtopic_report'
```

**Comment by assafelovic** [comment]
Hey @Italosayan we've cleaned the UI but most functionality exists. I just added it to the UI so you can check it out by pulling latest version: https://github.com/assafelovic/gpt-researcher/commit/1675663dd228c5c31d6b36e93469358e177d3e53

**Comment by Italosayan** [comment]
Thanks!
