### ISSUE TITLE
Feature request: Copy to clipboard as markdown with sources

### ISSUE THREAD

**Issue by Xtrah** [assafelovic/gpt-researcher#438]
Copy to clipboard is currently just raw text, and without any references/sources.

Adding an option to copy as markdown, similarly styled to the PDF generated, could make it significantly more useful and readable. Considering this is a "researcher", references is essential.

**Comment by assafelovic** [comment]
Thanks for the feedback @Xtrah! This is a feature and not a bug :)
Many users copy from the UI to some external document and therefore markdown will not be optimal.
If you'd like to get the full markdown report you can try out the package. See example here: https://github.com/assafelovic/gpt-researcher/blob/master/examples/sample_report.py
To install the package simply run `pip install gpt-researcher`
