### ISSUE TITLE
如何使用Langchain Adapter 支持的开源模型，且并没有找到config/config.py文件

### ISSUE THREAD

**Issue by YinSonglin1997** [assafelovic/gpt-researcher#440]
由于特殊原因，无法使用OpenAI GPT，想使用开源llm进行测试？能否提供具体操作步骤呢？感谢！

**Comment by assafelovic** [comment]
English please? :)

**Comment by pratham-darooka** [comment]
Hi @YinSonglin1997, 

I am using Google Gemini Developer API (for free).

Here is what I changed: `LLM_PROVIDER` to `“google”` in `config/config.py`.

Line 14: `self.llm_provider = os.getenv('LLM_PROVIDER', "google”)`

**Comment by YinSonglin1997** [comment]
Thank you for your reply, I have solved this problem, but I have encountered a new network connection problem, I will open a new issue.
