### ISSUE TITLE
(process:65916): GLib-GObject-CRITICAL **: 21:17:43.023: g_object_ref: assertion '!object_already_finalized' failed

### ISSUE THREAD

**Issue by junxu-ai** [assafelovic/gpt-researcher#453]
it usually can complete the first task. However, it often fails in the second try. One error is as follows. 

(process:65916): GLib-GObject-CRITICAL **: 21:17:43.023: g_object_ref: assertion '!object_already_finalized' failed

**Comment by assafelovic** [comment]
This is strange and haven't seen it. Maybe this can help? https://stackoverflow.com/questions/71467756/glib-gobject-g-object-replace-qdata-error-with-weasyprint

**Comment by assafelovic** [comment]
Closing due to staleness
