### ISSUE TITLE
gobject library not found in mac 

### ISSUE THREAD

**Issue by viswanath27** [assafelovic/gpt-researcher#455]
`OSError: cannot load library 'gobject-2.0-0': dlopen(gobject-2.0-0, 0x0002): tried: '/gobject-2.0-0' (no such file), '/opt/homebrew/bin/gobject-2.0-0' (no such file), 'gobject-2.0-0' (no such file), '/System/Volumes/Preboot/Cryptexes/OSgobject-2.0-0' (no such file), '/Users/viswanathbarenkala/anaconda3/envs/gptresearcher/bin/../lib/gobject-2.0-0' (no such file), '/usr/lib/gobject-2.0-0' (no such file, not in dyld cache), 'gobject-2.0-0' (no such file), '/usr/local/lib/gobject-2.0-0' (no such file), '/usr/lib/gobject-2.0-0' (no such file, not in dyld cache).  Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0-0'`

seem above is the issue in my mac.

I also have corrected the newspaper folder and file name as this is conflicting with the package name in python, post which this error is showing up

**Comment by satishjasthi** [comment]
> Thanks @lubuwei001 for the reference! I'll keep this open for now so others can see it

Hi @assafelovic 
Shall I update the installation section in documentation to inform Mac users to install this library?

**Comment by kairoswealth** [comment]
```
brew install glib
brea install pango
```

Solved it for me

**Comment by assafelovic** [comment]
@satishjasthi that would be great! Can you please update it here: https://github.com/assafelovic/gpt-researcher/blob/master/docs/docs/gpt-researcher/troubleshooting.md

**Comment by satishjasthi** [comment]
Ya sure

**Comment by assafelovic** [comment]
Hey everyone, also updating that refined code to import problematic libraries so that it doesn't crash: https://github.com/assafelovic/gpt-researcher/commit/5f035b5fe4856b8016db59382011e0d5ff51b30a

Lmk if this resolves for you

**Comment by vanetreg** [comment]
> Hey everyone, also updating that refined code to import problematic libraries so that it doesn't crash: [5f035b5](https://github.com/assafelovic/gpt-researcher/commit/5f035b5fe4856b8016db59382011e0d5ff51b30a)
> 
> Lmk if this resolves for you

It fixed for me both on Win 10 Pro and Replit
( BTW it still doesn't work on Repit, so a template would be appreciated! :) )

**Comment by lxmn** [comment]
hello everyone, I have installed weasyprint via `brew install weasyprint ` then I am able to run this command from terminal `weasyprint https://weasyprint.org /tmp/weasyprint-website.pdf`, but after installing python `weasyprint = "^62.3"` lib via poetry or pip, it started failing with below error  
`OSError: cannot load library 'gobject-2.0-0': dlopen(gobject-2.0-0, 0x0002): tried: 'gobject-2.0-0' (no such file), '/System/Volumes/Preboot/Cryptexes/OSgobject-2.0-0' (no such file), '/usr/lib/gobject-2.0-0' (no such file, not in dyld cache), 'gobject-2.0-0' (no such file), '/usr/lib/gobject-2.0-0' (no such file, not in dyld cache).  Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0-0'`

**I have Mac M1.**

**Comment by arnaujc91** [comment]
Same here, Mac M1 too.
