### ISSUE TITLE
Latest Version download word，the path is concat error

### ISSUE THREAD

**Issue by lx1054331851** [assafelovic/gpt-researcher#457]
```
/outputs/7cdef185f30849d08185a783384aef06.docx.docx
```
There’s an extra .docx on the path.

**Comment by assafelovic** [comment]
Hey @lx1054331851 thanks for raising this! Fixed in latest hot fix: https://github.com/assafelovic/gpt-researcher/commit/72d52a01e4b5e68b85feac9f9e5831d1f0ee5123

Please pull latest version
