### ISSUE TITLE
No supported WebSocket library detected. 

### ISSUE THREAD

**Issue by nolandubeau** [assafelovic/gpt-researcher#458]
I followed the instructions to run the app using Docker.  The app starts up correctly, however, fails when I ask it to research something.  All requirements for uvicorn[standard], websockets, and wsproto are satisfied.  The error is:

] Running 0/1
 ⠋ Container gpt-researcher-gpt-researcher-1  Recreated                                                                                                                           0.1s
Attaching to gpt-researcher-1
gpt-researcher-1  | /usr/local/lib/python3.11/site-packages/langchain/_api/module_import.py:87: LangChainDeprecationWarning: Importing GuardrailsOutputParser from langchain.output_parsers is deprecated. Please replace the import with the following:
gpt-researcher-1  | from langchain_community.output_parsers.rail_parser import GuardrailsOutputParser
gpt-researcher-1  |   warnings.warn(
gpt-researcher-1  | INFO:     Started server process [1]
gpt-researcher-1  | INFO:     Waiting for application startup.
gpt-researcher-1  | INFO:     Application startup complete.
gpt-researcher-1  | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
gpt-researcher-1  | INFO:     192.168.65.1:26965 - "GET / HTTP/1.1" 200 OK
gpt-researcher-1  | WARNING:  Unsupported upgrade request.
gpt-researcher-1  | WARNING:  No supported WebSocket library detected. Please use "pip install 'uvicorn[standard]'", or install 'websockets' or 'wsproto' manually.
gpt-researcher-1  | INFO:     192.168.65.1:26983 - "GET /ws HTTP/1.1" 404 Not Found

**Comment by assafelovic** [comment]
@ElishaKay maybe related to the issue you discussed?

**Comment by assafelovic** [comment]
@ElishaKay 👆🏻

**Comment by ElishaKay** [comment]
Thanks for the heads up @nolandubeau 

Correct this error was fixed in [this commit which made it into Master 2 weeks ago](https://github.com/assafelovic/gpt-researcher/commit/3d33fd87b9e7ae4a6a76d02b739620fb8f3a51ad)

The fix was to add the websockets library to requirements.txt

Safe to close
