### ISSUE TITLE
HTTPError 400 Client Error Bad Request when using TavilySearchResults

### ISSUE THREAD

**Issue by x1337x1** [assafelovic/gpt-researcher#464]
Im having this error while using the method TavilySearchResults with langchain. while the issue only if the agent tries to execute the tavily method other then this my replies work but i need tavily to work : 

HTTPError('400 Client Error: Bad Request for url: https://api.tavily.com/search')

my code setup
    vector_store = pinecone_manager.get_vectorstore(namespace)
    prompt = ChatPromptTemplate.from_messages([
        ("system", "Answer the user's questions based on the context: {context}"),
        MessagesPlaceholder(variable_name="chat_history"),
        ("user", "{input}")
    ])
    retriever = vector_store.as_retriever() ## method that we use to get documents from pinecone
    retriever_tool = create_retriever_tool(retriever, "langsmith_search", "Search for information about LangSmith. For any questions about LangSmith, you must use this tool!")
    tools = [retriever_tool, search]
    agent_prompt = hub.pull("hwchase17/openai-functions-agent") ## prompt
    agent = create_openai_functions_agent(llm, tools, agent_prompt)
    agent_executor = AgentExecutor(agent=agent, tools=tools, verbose=True)
    return agent_executor

**Comment by assafelovic** [comment]
Did you add the env api key?

**Comment by x1337x1** [comment]
yes i added the env

**Comment by x1337x1** [comment]
fixed it by removing this line 
os.environ["TAVILY_API_KEYY"] = getpass.getpass()
