### ISSUE TITLE
Error 422 without details

### ISSUE THREAD

**Issue by guidorietbroek** [assafelovic/gpt-researcher#469]
I'm trying to implement a Tavily search tool in my LangGraph graph, but it gives me an 422 error. So I tried a very basic stand alone version, but I still get this error. Unfortunately I don't get any specific information and looking at the API docs I have the feeling nothing is wrong with the input data. Btw I also get this error when adding the api_key parameter, which is required together with the query.

```
import { TavilySearchResults } from "@langchain/community/tools/tavily_search";

//Load environment variables
import * as dotenv from "dotenv";
dotenv.config();

const tool = new TavilySearchResults();

async function main() {
    const docs = await tool.invoke({ 
        query: "what is the weather in wailea?" });
}

main();
```

**Comment by assafelovic** [comment]
@guidorietbroek please reach out to support@tavily.com with this. Thanks!
