### ISSUE TITLE
Add verbosity flag to remove print statements

### ISSUE THREAD

**Issue by 0xj7r** [assafelovic/gpt-researcher#472]
I would like the option to remove printing/logging when executing the researcher agent to reduce noise in production

**Comment by 0xj7r** [comment]
> @0xj7r Sounds good, I'll add it to the roadmap! May I ask how is your experience with it on production? Are you using the package or the LangGraph integration?

Thanks a lot! So far it has been great! For context, I am using the package itself - taking the outputs of the `resource_report` to provided a consolidated list of resources relevant to a user-inputted search query that can then be used downstream...

Main observations/feedback:
- For my use-case, I would ideally like to return a specific set of targeted articles/search results - I have observed that when the search query is more broad, the search results also tend to also be broad - e.g. inputting 'AI marketing news' will return a link to a site covering ai marketing news rather than specific interesting articles where that is the subject -- wonder whether there are additional configs/routes that can be added to enable this? 
- It would be great to have a step where the search results are returned without the need for a report - currently I am adding additional post-processing to extract the headline/overview/url of the results that are returned in the `resource_report`

Awesome work! Excited to see how this progresses

**Comment by assafelovic** [comment]
Hey @0xj7r , just for you :)
Check out the latest PR here: https://github.com/assafelovic/gpt-researcher/pull/485

Enjoy!
