### ISSUE TITLE
OSError: [Errno 36] File name too long

### ISSUE THREAD

**Issue by mike12432** [assafelovic/gpt-researcher#487]
Running in a MAC Docker Container at the end of researching I receive an error related to file name length.  

workaround is to make shorter quarries. 

ine 348, in app
                    gpt-researcher-1  |     await dependant.call(**values)
                    gpt-researcher-1  |   File "/usr/src/app/backend/server.py", line 58, in websocket_endpoint
                    gpt-researcher-1  |     md_path = await write_text_to_md(report, filename)
                    gpt-researcher-1  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                    gpt-researcher-1  |   File "/usr/src/app/backend/utils.py", line 32, in write_text_to_md
                    gpt-researcher-1  |     await write_to_file(file_path, text)
                    gpt-researcher-1  |   File "/usr/src/app/backend/utils.py", line 19, in write_to_file
                    gpt-researcher-1  |     async with aiofiles.open(filename, "w", encoding='utf-8') as file:
                    gpt-researcher-1  |   File "/usr/local/lib/python3.11/site-packages/aiofiles/base.py", line 98, in __aenter__
                    gpt-researcher-1  |     self._obj = await self._coro
                    gpt-researcher-1  |                 ^^^^^^^^^^^^^^^^
                    gpt-researcher-1  |   File "/usr/local/lib/python3.11/site-packages/aiofiles/threadpool/__init__.py", line 94, in _open
                    gpt-researcher-1  |     f = yield from loop.run_in_executor(executor, cb)
                    gpt-researcher-1  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                    gpt-researcher-1  |   File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
                    gpt-researcher-1  |     result = self.fn(*self.args, **self.kwargs)
                    gpt-researcher-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                    gpt-researcher-1  | OSError: [Errno 36] File name too long: 'outputs/task_1715258626_/this is my quarry which I have removed and replaced with this string that is still not as long as my quarry xxxxxxxxxx more xxxxxx you get the idea, this md file should be a file name that is not the same as the original quarry. .md'
                    gpt-researcher-1  | INFO:     connection closed

**Comment by assafelovic** [comment]
Hey @mike12432 have you pulled the latest release?

**Comment by mike12432** [comment]
yes, built fresh from source this morning.

**Comment by assafelovic** [comment]
@mike12432 fixed in latest version

**Comment by mike12432** [comment]
thanks!

**Comment by mike12432** [comment]
I pulled the latest repo, cleared out all images and files in Docker and rebuilt.  I am still having the issue on both the research and detailed reports, do I need to wait for the next release before this will work?

**Comment by smjure** [comment]
Same here, cloned the latest version, the too-long-file-name problem still present. It seems the research is finished but then cannot download the PDF file, which is eventually my intention.

**Comment by assafelovic** [comment]
@smjure can you please share the query and/or error log?

**Comment by smjure** [comment]
@assafelovic I've tried to reproduce it, but strangely cannot.... if it happens again, will post it here.

**Comment by klimentij** [comment]
![SCR-20240515-kri](https://github.com/assafelovic/gpt-researcher/assets/3247669/4e1c2fde-61d6-4eb4-94da-7c6cdf0f90f6)

Same here, all default settings, latest Docker

**Comment by assafelovic** [comment]
Hey all, fixed here: https://github.com/assafelovic/gpt-researcher/commit/bd75c9b6f04bc36ac026923e474e08a2b846672e

Please pull latest and try again. Should be good now!

**Comment by assafelovic** [comment]
@klimentij @smjure @mike12432 fyi

**Comment by mike12432** [comment]
Thank you, seems to be fixed.  But I noticed the print PDF button is not on the Detailed report page, not sure if it was ever there or the remediation removed it.  Anyway I wont open a ticket on it as its not a feature important to me.  Thanks for your work and thanks for updating to GPT-4o, total run of detailed report was 37 cents.
