### ISSUE TITLE
Goes on forever?

### ISSUE THREAD

**Issue by madiha1ahmed** [assafelovic/gpt-researcher#51]
I fed in my research topic as “AI for drug design”, and it’s been running for over 2 hours.

At some instances, the model seems to be scraping irrelevant websites. Moreover, the model also scrapes YouTube links and concludes that it has “no text to summarise”. I suggest that the YouTube scraping feature to be removed. This may be the reason why I find gpt-researcher extremely time consuming. 

May I know the average time this model takes to generate the report?

**Comment by madiha1ahmed** [comment]
To follow up with my previous comment: after hours of waiting, this is the error I get: 

![Uploading EB82BCCF-6CC6-4D92-A398-08BC31ECA509.jpeg…]()

**Comment by madiha1ahmed** [comment]
Another reason why this model takes up so much time and resources is that the model processes every character. 

![5593AC72-DF6B-4FFE-B127-1430BDE0F391](https://github.com/assafelovic/gpt-researcher/assets/56754113/446a36f5-f9c6-4bb5-b322-810eb0d4824e)

As you can see the queries: [“Sri Lanka…]. The model first looks up ‘[‘ and scrapes all the websites to understand the grammar behind ‘[‘. And then it does the same for the apostrophe, letter S and so on. I believe this is not how it should be done. 

As you can see in the image, it is learning about the letter I in “Sri”. 

![32DB1F33-102B-44A7-87EA-2191D10DA398](https://github.com/assafelovic/gpt-researcher/assets/56754113/99b93030-65df-428c-9cd0-19d7c9543a1c)

**Comment by rotemweiss57** [comment]
HI @madiha1ahmed, good catch on youtube scraping, we will prevent it.

Regarding your issue, are you using gpt 4 or 3.5? the json produced from the generate_queries function was bad - a known issue when using gpt-3.5. You should simply run it again. 
The avg time depends on many factors, computing power, internet access, latency, and openAI of course. However, longer than 10 minutes will indicate an issue.

Hope it helps
