### ISSUE TITLE
How to run repo on a mac with local folder?

### ISSUE THREAD

**Issue by Korayem** [assafelovic/gpt-researcher#516]
I am having trouble due to setup not complete so I did the following

# nltk
Download nltk files from https://www.nltk.org/nltk_data/
Punkt and extract to: `Users › korayem > nItk_data › tokenizers > punkt`
averaged_perceptron_tagger and extract to: `Users › <username> > nitk_data › taggers > averaged_perceptron_tagger`

# Update `requirements.txt`
Many packages where not there. Add the following:
```
networkx
python-pptx
xlsxwriter
pillow
pandas
openpyxl
```

I am not sure what else is missing

Thought of sharing in case anyone else is stuck like I was

**Comment by assafelovic** [comment]
Hey @Korayem can you share the error logs?

**Comment by Korayem** [comment]
Hey @assafelovic 
It's was all trial an error night yesterday :)

I took a fresh git clone, added `.env` then started to get error loading `networkx`
Added that to requirements, run again, get an error loading `python-pptx`
and so on...

As for NLTK, I got 
```
Resource punkt not found.
  Please use the NLTK Downloader to obtain the resource

import nltk
>>> nltk.download('punkt')
[nltk_data] Error loading punkt: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed:
[nltk_data]     unable to get local issuer certificate (_ssl.c:1000)>
```

So after digging around, I found this [answer](https://stackoverflow.com/a/78008788/80434) that gave me a hint on how to structure the files

Btw, I still can't get it to work with local files. Last thing it asked for LibreOffice. I installed it. Then got another error. will share when I am back home tonight.

**Comment by ElishaKay** [comment]
Welcome @Korayem ,

Perhaps a smoother path for you would be to run it through Docker Desktop.

[Tutorial is here](https://youtu.be/x1gKFt_6Us4?si=texlcpcm_JmpAG1A)

**Comment by Korayem** [comment]
Yeah, forgot to mention docker. I want to use it with my local files as mentioned, so I tried the new File Sharing >Virtual File shares feature in docker. I added the path to my local mac folder in env `users/<username>/documents/folder. Also added `DOC_PATH` to `docker-compose.yml` to carry the value into docker container.

I got an error
