### ISSUE TITLE
Duplicate retriever search call

### ISSUE THREAD

**Issue by samialsheikh** [assafelovic/gpt-researcher#517]
It seems there is a duplicate call to the `retriever.search` here that is not needed, and the first can be removed.  If so, perhaps we can remove lines 225-229. 

Is my understanding correct? I just found this repo, so I may be missing something.

https://github.com/assafelovic/gpt-researcher/blob/0a0e4aed4731a41a51168f141cbf4039eb7fadb8/gpt_researcher/master/agent.py#L216-L244

**Comment by assafelovic** [comment]
Good catch @samialsheikh ! Must've been pushed with an unhandled merge. Just updated here: https://github.com/assafelovic/gpt-researcher/commit/c1274a86c2619b9fb0f3c6631a744df3f06acb27
