### ISSUE TITLE
need an option for more in depth output

### ISSUE THREAD

**Issue by 21pl** [assafelovic/gpt-researcher#52]
Currently it seems that the research report is limited to a 2 page PDF output. Definitely need an option to increase the output so that more information is provided, especially for the academic research agent.

**Comment by 21pl** [comment]
tried asking in the prompt for at least a 5000 word output but only got 792 words

**Comment by rotemweiss57** [comment]
Currently, we are limited to OpenAI's max tokens. our agent is prompt by default to produce a report > 1,200 words. As a community, we will slowly investigate new and unique approaches to stretch the limits of LLMs.
