### ISSUE TITLE
[Docs] Langchain Adapters not available (link not working)

### ISSUE THREAD

**Issue by SimonB97** [assafelovic/gpt-researcher#525]
Hi, the links to the 'Langchain Adapters'-documentation page are depricated, e.g. on [Getting Started](https://docs.gptr.dev/docs/gpt-researcher/getting-started):

> For LLM, we recommend [OpenAI GPT](https://platform.openai.com/docs/guides/gpt), but you can use any other LLM model (including open sources) supported by [Langchain Adapter](https://python.langchain.com/docs/guides/adapters/openai), simply change the llm model and provider in config/config.py.

It's unclear which LLMs are supported now. I'd like to use VertexAI Gemini, but don't know if it's possible or how.

**Comment by assafelovic** [comment]
Hey @SimonB97 thanks for the update we're working on an improved experience around this and will update the community in the Discord channel in the next few days
