### ISSUE TITLE
ERROR: Could not build wheels for pyreqwest-impersonate, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by metacav** [assafelovic/gpt-researcher#529]
running: cd "/tmp/pip-install-hormq9jr/pyreqwest-impersonate_762d95a1dea042c888eab36c00adda12/target/release/build/boring-sys-imp-27d09f24c7b163e4/out/build" && CMAKE_PREFIX_PATH="" "cmake" "/home/ec2-user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/boring-sys-imp-2.1.0/deps/boringssl" "-DCMAKE_INSTALL_PREFIX=/tmp/pip-install-hormq9jr/pyreqwest-impersonate_762d95a1dea042c888eab36c00adda12/target/release/build/boring-sys-imp-27d09f24c7b163e4/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_ASM_COMPILER=/usr/bin/cc" "-DCMAKE_BUILD_TYPE=Release"
      
        --- stderr
        Traceback (most recent call last):
          File "/home/ec2-user/anaconda3/envs/sbs/bin/cmake", line 5, in <module>
            from cmake import cmake
        ModuleNotFoundError: No module named 'cmake'
        thread 'main' panicked at /home/ec2-user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cmake-0.1.50/src/lib.rs:1098:5:
      
        command did not execute successfully, got: exit status: 1
      
        build script failed, must exit now
        note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
      warning: build failed, waiting for other jobs to finish...
      💥 maturin failed
        Caused by: Failed to build a native library through cargo
        Caused by: Cargo build finished with "exit status: 101": `env -u CARGO PYO3_ENVIRONMENT_SIGNATURE="cpython-3.12-64bit" PYO3_PYTHON="/home/ec2-user/anaconda3/envs/sbs/bin/python3.1" PYTHON_SYS_EXECUTABLE="/home/ec2-user/anaconda3/envs/sbs/bin/python3.1" "cargo" "rustc" "--features" "pyo3/extension-module" "--message-format" "json-render-diagnostics" "--manifest-path" "/tmp/pip-install-hormq9jr/pyreqwest-impersonate_762d95a1dea042c888eab36c00adda12/Cargo.toml" "--release" "--lib"`
      Error: command ['maturin', 'pep517', 'build-wheel', '-i', '/home/ec2-user/anaconda3/envs/sbs/bin/python3.1', '--compatibility', 'off'] returned non-zero exit status 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyreqwest-impersonate
  Building wheel for docopt (setup.py) ... done
  Created wheel for docopt: filename=docopt-0.6.2-py2.py3-none-any.whl size=13706 sha256=2a4b7f0eed33d0f7a90fdd16ca9b06eeafd275fbe256d1d503cb584b51b51628
  Stored in directory: /tmp/pip-ephem-wheel-cache-ozh7f558/wheels/1a/bf/a1/4cee4f7678c68c5875ca89eaccf460593539805c3906722228
  Building wheel for langdetect (setup.py) ... done
  Created wheel for langdetect: filename=langdetect-1.0.9-py3-none-any.whl size=993227 sha256=a3208f35712c0f0d30dd4f74dda6fee9dd9a7139e24907e392ef3e3a96d8f1af
  Stored in directory: /tmp/pip-ephem-wheel-cache-ozh7f558/wheels/c1/67/88/e844b5b022812e15a52e4eaa38a1e709e99f06f6639d7e3ba7
  Building wheel for sgmllib3k (setup.py) ... done
  Created wheel for sgmllib3k: filename=sgmllib3k-1.0.0-py3-none-any.whl size=6049 sha256=f84c30062922c8d3de11c4afe74f1344927639ade46daf0c59e2e209463df7ff
  Stored in directory: /tmp/pip-ephem-wheel-cache-ozh7f558/wheels/03/f5/1a/23761066dac1d0e8e683e5fdb27e12de53209d05a4a37e6246
Successfully built md2pdf tinysegmenter feedfinder2 jieba3k docopt langdetect sgmllib3k
Failed to build pyreqwest-impersonate
ERROR: Could not build wheels for pyreqwest-impersonate, which is required to install pyproject.toml-based projects

**Comment by tomkat-cr** [comment]
I have the same issue after installing the latest version of duckduckgo-search, that now includes pyreqwest-impersonate==0.4.5

**Comment by deedy5** [comment]
@metacav Try it again, it should work

**Comment by assafelovic** [comment]
Thanks for the solution @tomkat-cr
