### ISSUE TITLE
API suddenly returning the same sources, regardless of what question is sent and what domains are included

### ISSUE THREAD

**Issue by birgitbartels** [assafelovic/gpt-researcher#530]
Dear Tavily Team,

I hope this message finds you well. I am writing to report an issue I've encountered with your API, which I have been using to develop a copilot that retrieves sources from the internet. Yesterday, the API was functioning perfectly, providing accurate and relevant sources for both Dutch and English queries. However, as of today, the API returns sources that are irrelevant to the query, especially when processing Dutch requests. In contrast, English queries continue to yield more pertinent results.

Additionally, I have encountered problems with the include_domains parameter. Yesterday, it functioned correctly but only accepted a list containing a maximum of one website. Today, it does not seem to work at all, regardless of the input format.

<img width="1119" alt="Screenshot 2024-05-23 at 13 34 43" src="https://github.com/assafelovic/gpt-researcher/assets/146433501/bf12e413-a091-4b6d-ab09-f0abc248d615">

In the screenshot above you can see how I am accessing Tavily search through the langchain module. I asked the question in Dutch 'Who are the children of King Filip?', this is a question I used to always ask to test the application and which always provided the correct results. But now I get English urls to yahoo.com that have nothing to do with the question asked. 

In the next screenshot you can then see how I am adding 'rva.be' as the domain to be used in the query, which before would give me results only from that website. However, now I only get sources that have nothing to do with my request:  

<img width="1091" alt="Screenshot 2024-05-23 at 13 36 09" src="https://github.com/assafelovic/gpt-researcher/assets/146433501/1e24c791-bf15-446b-bf54-a5df8826de7f">

Before, when adding multiple domains into the list, I would not get any sources, so that did not seem to work. Now, it just does the same as when I do not add any websites.

Has a certain change occurred on the API, is there something that should be done differently or does anyone know why I suddenly don't get good results anymore? 

Kind regards, 

Birgit Bartels

**Comment by assafelovic** [comment]
Hey @birgitbartels , this is due to the Tavily search API. You can try changing to other search engines as seen here: https://docs.gptr.dev/docs/gpt-researcher/config

**Comment by birgitbartels** [comment]
Hi @assafelovic 

Do you maybe also know what is wrong with the Tavily search API and wether the issue will be fixed? I'm also hoping that this is the correct GitHub page to asks these questions on - when I click on 'github' on the Tavily.com website, it brings me here in any case.  

Thanks already for the alternatives, I'll take a look at them!

Kind regards,

BIRGIT BARTELS

**Comment by MariaMalycha** [comment]
up

**Comment by assafelovic** [comment]
Hey @birgitbartels it seems that Bing and Duckduckgo are down as well which probably correlate with Tavily. In case this is affecting GPT Researcher I've just pushed yahoo search support (which is free). Simply pull latest version and run
- `pip install -U gpt-researcher`
- add env `export RETRIEVER=yahoo`
and run again

For tavily inqueries reach out at support@tavily.com
