### ISSUE TITLE
"model 'gpt-4o' not found, try pulling it first"

### ISSUE THREAD

**Issue by mccoydj1** [assafelovic/gpt-researcher#532]
I got this error.

openai.NotFoundError: Error code: 404 - {'error': {'message': "model 'gpt-4o' not found, try pulling it first", 'type': 'api_error', 'param': None, 'code': None}}

I am using the example code - what am I doing wrong?
https://docs.gptr.dev/docs/gpt-researcher/pip-package

(Also i used os.environ["OPENAI_API_KEY"] to set my openai key)

**Comment by assafelovic** [comment]
This is strange. Did you try exporting your key like so: `export OPENAI_API_KEY=...` ?
