### ISSUE TITLE
Interference of different research topics

### ISSUE THREAD

**Issue by biany** [assafelovic/gpt-researcher#533]
I found an interference by the previous  research topics when querying a new topic. The new topic was totally irrevalent to the old topic, however some references cited in the new report were the same to the old topic and had nothing to do with the new topic. 

This problem was solved by restarting the uvicorn app. I haven't dove into the code but I guess a new temporary vectorstore needs to be created when given a new topic.

**Comment by assafelovic** [comment]
Thanks @biany we'll look into this.

**Comment by theguaz** [comment]
I'm experiencing the same behavior with an adapted version of cli.py, whenever I ask another topic it starts to mix the topics.

**Comment by assafelovic** [comment]
@biany @theguaz does this happen on the web interface of PIP package or both?

**Comment by assafelovic** [comment]
Fixed here: https://github.com/assafelovic/gpt-researcher/commit/1525ac1e8a5e6d558826e9f2890743ea4d9dd856
