### ISSUE TITLE
Set up different LLM providers for smart, fast and embedding LLMs

### ISSUE THREAD

**Issue by vanetreg** [assafelovic/gpt-researcher#539]
I think it makes sense to use:
gpt-4 as smart LLM,
some Groq / Openrouter / Huggingface / Ollama LLM as fast and
eg. Nomic Embed (via GPT4All) as embed model,
but now we are not able to set fast and smart LLM providers separatedly up AFAIK ( checking config.py ),
at least not without Langchain,
so pls. consider my idea :)

**Comment by wofeishenling** [comment]
yeah, i also want it

**Comment by assafelovic** [comment]
Hey, big release tomorrow that will include this :)

**Comment by vanetreg** [comment]
> Hey, big release tomorrow that will include this :)

[As far as I see](https://docs.gptr.dev/docs/gpt-researcher/llms):
- we are still not able to set up different LLM providers for smart (eg. OpenAI) and fast LLMs (eg. Groq, HF of Openrouter free)
- Openrouter config options are not in docs. It would be a good option with [their FREE models](https://openrouter.ai/models?q=free&o=top-weekly) to play around with GPT Researcher as fast LLM.

**Comment by xenstar** [comment]
Yes, please add openrouter as we can integrate with different LLMS easily and see which one is giving better output :)

**Comment by Speedway1** [comment]
For locally hosted LLMs this feature is essential, because it allows for different machines to provide each type of LLM which enables for more GPUs to be used preloaded with the LLms, which is much faster. Has one got this working?

**Comment by BradKML** [comment]
@assafelovic thanks for the updates, and I noticed it does not use LiteLLM, which is a little weird. https://docs.gptr.dev/docs/gpt-researcher/llms/llms#ollama
P.S. Embeddings are in a weird situation https://github.com/assafelovic/gpt-researcher/issues/629 https://ollama.com/blog/embedding-models
