### ISSUE TITLE
chromedriver M1 mac error

### ISSUE THREAD

**Issue by austinmw** [assafelovic/gpt-researcher#54]
Every URL that attempts to be processed gives me the following error:

> An error occurred while processing the url https://www.kiplinger.com/investing/amazon-stock-is-a-top-pick-for-2023-analysts-say: Message: Can not connect to the Service /Users/austinmw/.wdm/drivers/chromedriver/mac_arm64/114.0.5735.90/chromedriver

Any idea how to fix this?

**Comment by rotemweiss57** [comment]
hi Austin, were you using docker to install?

**Comment by escoolioinglesias** [comment]
@rotemweiss57 

Hi, I'm also on M1 Mac and I installed with Docker.

I'm getting

`An error occurred while processing the url $URL: Message: Service /root/.wdm/drivers/chromedriver/linux64/114.0.5735.90/chromedriver unexpectedly exited. Status code was: 255`

How can I fix this?

**Comment by austinmw** [comment]
Yep I was using Docker. I seemed to get it to work by not using docker and also using venv instead of conda (to use homebrew version of Python)

**Comment by rotemweiss57** [comment]
@escoolioinglesias is it working for you now?

**Comment by austinmw** [comment]
Yep working now thanks

**Comment by escoolioinglesias** [comment]
@rotemweiss57 

I was never able to get it running with Docker on my M1 Mac, but I was able to tease out how to get it running thanks to @austinmw's comment

Thanks!

**Comment by escoolioinglesias** [comment]
thought I'd make a video for people struggling on their Silicon Macs:
https://youtu.be/x9HuzdyP9Uk

**Comment by escoolioinglesias** [comment]
I was hitting some snags for a while, but I was able to sort it out with this thread, so thank you again!

I tried to make an easy and engaging video guide to follow, hoping it might help others out:
https://youtu.be/JVMl9rmP-eY
