### ISSUE TITLE
How to use an open embedding model in gpt-researcher 

### ISSUE THREAD

**Issue by jbdatascience** [assafelovic/gpt-researcher#545]
How to use an open embedding model in gpt-researcher ? Do I have to change the config.py file for that, and how exactly to do that?

**Comment by vanetreg** [comment]
https://docs.gptr.dev/docs/gpt-researcher/llms

**Comment by zhangwanshen** [comment]
可以本地部署LLM并脱网使用gpt-researcher进行本地文件的分析吗？
