### ISSUE TITLE
model: `gpt-4` does not exist

### ISSUE THREAD

**Issue by ckiefer** [assafelovic/gpt-researcher#55]
Hi

Thx for the great work. I am getting the following error in the terminal when pressing the blue "Research" button:
`openai.error.InvalidRequestError: The model: `gpt-4` does not exist`

My provided API key indeed does not have access to the gpt-4 model:
`curl https://api.openai.com/v1/models -H "Authorization: Bearer $OPENAI_API_KEY"`

I am on a Plus plan in ChatGPT -- does it have any influences on which models I can access with the API kex?
How can I solve the issue?

BR, Christoph

**Comment by rotemweiss57** [comment]
Hi! well they will give access to all users by the end of the month: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4 

In the meanwhile you can try running it using gpt3.5 . follow the instructions here: https://github.com/assafelovic/gpt-researcher/issues/34 

Hope it helps!

**Comment by ckiefer** [comment]
Great, thx for the support! That worked.

**Comment by rotemweiss57** [comment]
Great!

**Comment by irreversibly** [comment]
> Great, thx for the support! That worked.

Dear, Did you run gpt-researcher on GPT3.5? I'm also GPT plus users, and I received the letter for the grand for GPT4 api access. How I cannot use the gpt-4 API b.b

**Comment by rotemweiss57** [comment]
Hi @irreversibly , you will have access to gpt-4 starting next month: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4
