### ISSUE TITLE
detailed_report argument not working

### ISSUE THREAD

**Issue by theguaz** [assafelovic/gpt-researcher#550]
When I execute ;

`python cli.py "tell me about cats" --report_type "detailed_report"`

I get :

`Please use one of the following: research_report, resource_report, outline_report, custom_report, subtopic_report
Using default report type: research_report prompt.`

Any thoughts?

**Comment by assafelovic** [comment]
Hey @theguaz detailed reports is not a GPT Researcher report type but rather an implementation that leverages GPT Researcher. You can see here how it's implemented: https://github.com/assafelovic/gpt-researcher/tree/master/backend/report_type/detailed_report

The idea behind it is that it's a very very long process so would result in instabilities as one function call. If you see the code above you'll see that we use GPT Researcher iteratively to generate the detailed report.
