### ISSUE TITLE
Medium bug in detailed_report._get_subtopic_report(self, subtopic: dict)

### ISSUE THREAD

**Issue by DanHUMassMed** [assafelovic/gpt-researcher#557]
__User Experience:__
* While running detailed reports on local data. GPT-Researcher mixes Local and Web results.

__The Problem:__
*The init() method of the GPTResearcher class defaults to 'web' if no `report_source` param is passed.

__The Solution:__
* Provide the keyword argument `report_source` when constructing the `GPTResearcher()` instance in the `_get_subtopic_report()` method. 
```
        subtopic_assistant = GPTResearcher(
            query=current_subtopic_task,
            report_type="subtopic_report",
            report_source=self.report_source, # Bug Fix
            websocket=self.websocket,
            parent_query=self.query,
            subtopics=self.subtopics,
            visited_urls=self.global_urls,
            agent=self.main_task_assistant.agent,
            role=self.main_task_assistant.role
        )
```
* _line 101 detailed_report.py_

I hope that helps if this bug has not already been tracked down.

-Dan

**Comment by assafelovic** [comment]
Hey @DanHUMassMed thanks for raising it! Fixed here: https://github.com/assafelovic/gpt-researcher/commit/9e8d1b17b67a050538876f3f7b1aef6b5f8af578
