### ISSUE TITLE
Please add support for pinokio.computer

### ISSUE THREAD

**Issue by xenstar** [assafelovic/gpt-researcher#562]
Can you create a config file for pinokio.computer, so we can easily host this on our computer, and use openrouter api aswell. It would be great then :)

**Comment by assafelovic** [comment]
Hey @xenstar thanks for the feedback! Can you explain more about the use case for this? And why pinokio vs other alternatives?

**Comment by xenstar** [comment]
Hi @assafelovic 

Well, for https://pinokio.computer, they have premade scripts, so you can just submit your scripts. Users have to search for it and then click on install. It will automatically download everything needed to run the script. 

As for openrouter.ai, there are a lot more models available at a cheaper price, so we can run GPT researcher at a cheaper price. We can even use Perplexity directly.

**Comment by jay377** [comment]
> pinokio.computer

Damn this looks cool thanks for the ref.

BTW Ive never seen anything cheaper then openrouter and ive looked hard, they like run at cost, prob get bulk is discounts love to see where there are cheaper models, can you share? Locally run excluded of course

**Comment by xenstar** [comment]
Openrouter is indeed the cheapest, as it has many providers available and routes to the cheapest one.

For openai, this one provides cheaper pricing than the official open api - https://deepbricks.ai/pricing

**Comment by jay377** [comment]
> Openrouter is indeed the cheapest, as it has many providers available and routes to the cheapest one.
> 
> For openai, this one provides cheaper pricing than the official open api - https://deepbricks.ai/pricing

I use openrouter but add the provider lock code to python to ground me to together ai only for llama 70b and that gives me the fastest (together way is faster then the rest yet they split the calls between if you dont lock it, so no thanks) cheapest llama 70b you can find without any rate limits basically, its awesome. grok it doesnt count because of that rate limit but its fine if you dont need vol

**Comment by ElishaKay** [comment]
Feel free to go for the PR.

There is also support for the [Ollama library](https://ollama.com/library?sort=popular) if you're interested in variety - [GPTR Ollama docs here](https://docs.gptr.dev/docs/gpt-researcher/llms/running-with-ollama)
