### ISSUE TITLE
Changing ollama base url

### ISSUE THREAD

**Issue by ahhany** [assafelovic/gpt-researcher#566]
When you set any base url, the app adds "/api/chat" after the base URL, which will make it impossible to use something like lmstudio or any fixed LLM provider.
Is there a solution for this?

**Comment by sebaxzero** [comment]
ollama base url its meant to use with ollama, for lm-studio you can use LLM_PROVIDER="openai" and EMBEDDING_PROVIDER="custom" 

[docs](https://github.com/assafelovic/gpt-researcher/blob/master/docs/docs/gpt-researcher/llms.md#custom-openai)

.env example:
```bash
LLM_PROVIDER="openai"
EMBEDDING_PROVIDER="custom"
OPENAI_BASE_URL="http://localhost:1234/v1"
OPENAI_API_KEY="Local"
```

**Comment by DimIsaev** [comment]
404
