### ISSUE TITLE
无法参与

### ISSUE THREAD

**Issue by Aguahanpu** [assafelovic/gpt-researcher#57]
discord 无法接受邀请，有没有其他的平台供交流

**Comment by rotemweiss57** [comment]
Please use this link: https://discord.com/invite/rqw8dnM8 

There are also discussions here on github

**Comment by Aguahanpu** [comment]
> Please use this link: https://discord.com/invite/rqw8dnM8
> 
> There are also discussions here on github

First of all, thank you very much, but I don't know why this is still happening.The hope is that the project will be mature quicklily enough  make it easier for public to use it.

**Comment by Aguahanpu** [comment]
> 

![image](https://github.com/assafelovic/gpt-researcher/assets/90496821/5164c290-50da-458c-b4f0-d5617ae99141)
