### ISSUE TITLE
Error in using Google's Gemini:"UserWarning: Convert_system_message_to_human will be deprecated！"

### ISSUE THREAD

**Issue by fan1jun** [assafelovic/gpt-researcher#573]
Error:  
\envs\gpt-researcher\Lib\site-packages\langchain_google_genai\chat_models.py:345: UserWarning: Convert_system_message_to_human will be deprecated！

Anyone with the same error?

**Comment by gkhngyk** [comment]
same

**Comment by assafelovic** [comment]
Resolved in latest release. Pull latest please
