### ISSUE TITLE
How to turn off Memory?

### ISSUE THREAD

**Issue by gkhngyk** [assafelovic/gpt-researcher#574]
Hello Team 

I want to turn off Memory because it is generating using previous reports and therefore I get meaningless outputs.

Is there a way to do this? I deleted the value of memory_backend in `config.py` but that didn't work either. 

```self.memory_backend = os.getenv(“MEMORY_BACKEND”, “”)```

**Comment by assafelovic** [comment]
Hey @gkhngyk can you give more details of the issue? The solution would not be to disable memory but to fix the issue you're experiencing. Please follow with more details, thanks!

**Comment by gkhngyk** [comment]
For example, when I ask it to research tavily, the report comes.
Then when I say research empler.ai, it adds tavily to the report.

In other words, it also adds the results obtained in previous researches into the reports.

**Comment by assafelovic** [comment]
@gkhngyk does this happen when using the web interface or PIP Package?

**Comment by assafelovic** [comment]
Fixed here: https://github.com/assafelovic/gpt-researcher/commit/1525ac1e8a5e6d558826e9f2890743ea4d9dd856
