### ISSUE TITLE
Error : failed to check if window was closed: disconnected: not connected to DevTools

### ISSUE THREAD

**Issue by daegonYu** [assafelovic/gpt-researcher#58]
An error occurred while processing the url https://www.technologyreview.kr/ai-large-language-models-bigscience-project/: Message: disconnected: not connected to DevTools
  (failed to check if window was closed: disconnected: not connected to DevTools)
  (Session info: headless chrome=114.0.5735.198)

---

My chrome version is 114.0.5735.198 and the chromedriver version is 114.0.5735.90
could you fix this error?

**Comment by gregdrizz** [comment]
114.0.5735.198
doesn't have a chromedriver yet, you can use the docker version of gptresearcher or downgrade your chrome(it's pretty easy and you can keep all of your browsing history)

**Comment by rotemweiss57** [comment]
Hi @daegonYu , were you able so solve it?

**Comment by ckiefer** [comment]
> 114.0.5735.198 doesn't have a chromedriver yet, you can use the docker version of gptresearcher or downgrade your chrome(it's pretty easy and you can keep all of your browsing history)

How did you do that? Can you share some insights about the process and which Chrome version works?

**Comment by daegonYu** [comment]
The code I git cloned was not the latest code, and after updating the code by git pull, it worked well when I used docker. thank you

**Comment by rotemweiss57** [comment]
Hi @ckiefer did you get it work?

**Comment by Drawwork** [comment]
it is hard to find chrome old version the same as chrome driver version(114.0.5735.90).
