### ISSUE TITLE
Language of the report other than English

### ISSUE THREAD

**Issue by slavonnet** [assafelovic/gpt-researcher#580]
It is not possible to change the language of the report to a language other than English

**Comment by slavonnet** [comment]
Looks like simple need add to prompts in `gpt_researcher/master/prompts.py` additional text like `The report must be written in Spanish`

**Comment by assafelovic** [comment]
@slavonnet you can try adding this to the query of the research task. Alternatively you can try the multi agent framework which support report guidelines see here: https://github.com/assafelovic/gpt-researcher/tree/master/multi_agents
