### ISSUE TITLE
OpenAI Error: Request too large for gpt-4o

### ISSUE THREAD

**Issue by ebezgodov** [assafelovic/gpt-researcher#585]
I encounter an error in the logs with each research attempt, leading to an empty report as a result. It seems I might need a configuration option to slow down the requests to the OpenAI API to comply with their rate limits.

Error in generate_report: Error code: 429 - {'error': {'message': 'Request too large for gpt-4o in organization org-sE0IdGM75DskjnJVA5kYx3XU on tokens per min (TPM): Limit 30000, Requested 82821. The input or output tokens must be reduced in order to run successfully. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

**Comment by assafelovic** [comment]
Seems to be a rate limitation on your end with your openai account and not related to gpt researcher.
