### ISSUE TITLE
WARNING:root:Rate limit reached, backing off...

### ISSUE THREAD

**Issue by ckiefer** [assafelovic/gpt-researcher#59]
Hi

How can this situation be resolved?

`WARNING:root:Rate limit reached, backing off...`

![image](https://github.com/assafelovic/gpt-researcher/assets/8458235/62a14e4f-048b-49f9-b748-1e23fb40ebca)

BR, Christoph

**Comment by rotemweiss57** [comment]
hi @ckiefer , this mechanism is essential for stability so the agent will be able to finish its task. Are you using the free trial api key? they have lower rate limit.

**Comment by ckiefer** [comment]
Yes, I am on a free trial API key. So what I understand is that it's not possible to use this tool on the free plan. Is that correct?
