### ISSUE TITLE
More flexible similarity distance handling

### ISSUE THREAD

**Issue by barsuna** [assafelovic/gpt-researcher#590]
I found that default similarity threshold in compression.py (0.38?) does not always work great. With some embedding models i had to lower it and there is no way to do it other than editing code.

Does it make sense to move this to the config?

Also when there are no hits within set similarity threshold, is it possible to print the nearest distance found (when verbose is on)?

**Comment by assafelovic** [comment]
Hey @barsuna done here: https://github.com/assafelovic/gpt-researcher/commit/7be4efd4ccfd146201ae336b8ea25854463d0e7e

Thanks for the feedback! Regarding verbose, would be over engineering in my opinion, but you can always debug and modify the code if needed. Thanks!
