### ISSUE TITLE
Changing the model from gpt-4o to gpt-3.5 turbo ?

### ISSUE THREAD

**Issue by samiqazi** [assafelovic/gpt-researcher#593]
Hello, I am using the free tier of openai Api, so getting the error. How to change the model from gpt-4o to say like gpt-3.5 ? Thanks 

openai.NotFoundError: Error code: 404 - {'error': {'message': 'The model `gpt-4o` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}

**Comment by assafelovic** [comment]
I would not recommend changing to gpt-3.5 since it will affect quality and token limits. You can try using other LLMs here: https://docs.gptr.dev/docs/gpt-researcher/llms
