### ISSUE TITLE
Getting gpt-4 does not exist despite having access

### ISSUE THREAD

**Issue by nathanael** [assafelovic/gpt-researcher#60]
When I run 'research' I get 
openai.error.InvalidRequestError: The model: `gpt-4` does not exist
I do have access to the GPT-4 API as far as I'm aware. I've used it in other projects and I'm using premium. I also replaced GPT-4 varaible in config.py > self.smart_llm_model = os.getenv("SMART_LLM_MODEL", "gpt-3.5-turbo-16k")

I'm still getting the same message. I'm using docker, so perhaps it's just rebuilding the codebase from somewhere I haven't changed? I'm no developer.

**Comment by gregdrizz** [comment]
You can run the docker with the env var:
docker run -e SMART_LLM_MODEL=gpt-3.5-turbo-16k -d your_image

**Comment by rotemweiss57** [comment]
Hi @nathanael, were you able to solve it?

**Comment by rotemweiss57** [comment]
Closing for now. The solution is either to have a valid API key with gpt-4 or changing SMART_LLM_MODEL=gpt-3.5-turbo-16k in the config file.
