### ISSUE TITLE
The UI of GPT Researcher!

### ISSUE THREAD

**Issue by Mitchell-xiyunfeng** [assafelovic/gpt-researcher#601]
GPT Researcher is a fantastic project. You guys did a great job!

Here, I would like to make a small suggestion.

Looking at the current Web UI, the box for inputting research queries and agent outputs is a bit narrow, micro-adjustments to make it wider would be better.

![image](https://github.com/assafelovic/gpt-researcher/assets/68734681/0d02350b-4b44-48bb-8d3f-78210b3b000b)

Looking forward to your reply.

Best regards,

**Comment by assafelovic** [comment]
Hey @Mitchell-xiyunfeng thanks for the feedback! How about opening a PR with ux improvements?

**Comment by Mitchell-xiyunfeng** [comment]
> Hey @Mitchell-xiyunfeng thanks for the feedback! How about opening a PR with ux improvements?
I am very sorry. I am not actually familiar with the framework and code used to implement the UI interface for this project, would you please address this.

**Comment by ElishaKay** [comment]
Not a bad point @Mitchell-xiyunfeng,

We're in the middle of a [lean sprint towards a new UI](https://github.com/assafelovic/gpt-researcher/pull/523)

@assafelovic perhaps a multi-line input box for inputting the query might be more convenient? especially for longer queries that are really looking into researching specific areas & finer points of a topic

**Comment by Mitchell-xiyunfeng** [comment]
> Not a bad point @Mitchell-xiyunfeng,
> 
> We're in the middle of a [lean sprint towards a new UI](https://github.com/assafelovic/gpt-researcher/pull/523)
> 
> @assafelovic perhaps a multi-line input box for inputting the query might be more convenient? especially for longer queries that are really looking into researching specific areas & finer points of a topic

You guys are really awesome! 

We are grateful for your efforts and work!

**Comment by assafelovic** [comment]
Hey thanks for the feedback @Mitchell-xiyunfeng ! Just updated UI so pull the latest: https://github.com/assafelovic/gpt-researcher/commit/7db6a737604b605416767bbbb0f855c7e63f1d6d

**Comment by Mitchell-xiyunfeng** [comment]
> Hey thanks for the feedback @Mitchell-xiyunfeng ! Just updated UI so pull the latest: [7db6a73](https://github.com/assafelovic/gpt-researcher/commit/7db6a737604b605416767bbbb0f855c7e63f1d6d)

Two important questions please:
1. First important question: Will GPT Researcher deployed on the RepoCloud also be able to synchronize updates once these improvements are completed?
2. The second important question: How does GPT Researcher deployed on the RepoCloud use local documents for knowledge QA? After making sure to add the DOC_PATH environment variable pointing to the documents folder.
