### ISSUE TITLE
Chinese character not display 

### ISSUE THREAD

**Issue by lx1054331851** [assafelovic/gpt-researcher#604]
<img width="1082" alt="image" src="https://github.com/assafelovic/gpt-researcher/assets/12423206/e43d9b9f-5b5c-4d63-9fc4-ec33d0b3b6f8">

when download as pdf, the chinese character not display, so i add a local font to the css file.

But when I run the project in the local environment, the pdf display chinese correctly, but when I build the docker, the problem exists.

**Comment by assafelovic** [comment]
Hey good point, happy to any contribution to resolve it.
