### ISSUE TITLE
Uvicorn loads but application stalls at "connection open"

### ISSUE THREAD

**Issue by nmcross** [assafelovic/gpt-researcher#619]
I have used this application before.  I recently pulled it from the git repo again and created a new conda environment based on python 3.11.  I pulled in all the libraries in the requirements.txt file and then exported Tavily and Openai api keys.  I also created a .env file from .env.example and provided the Tavily and Openai api keys.  I then ran the application using the python -m uvicorn... command and it seems to load properly.  Going to the url, localhost:8000 in a webbrowser loads the web page as expected.  I provide a prompt in the what would you like me to research field and click research.  the result section displays "Thinking about research questions for the task..." however nothing else happens.  There's no CPU activity associated with the application.  The command line just displays "connection open" and no further activity like it has in the past.  I've tried several fresh installs, several new conda environments, no errors are displayed in the command line.  I'm at a loss for what to do next.
Thanks,
Nathan

python -m uvicorn main:app --reload    
INFO:     Will watch for changes in these directories: ['/home/username/gpt-researcher2']  
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)   
INFO:     Started reloader process [2919] using StatReload             
USER_AGENT environment variable not set, consider setting it to identify your requests.    
INFO:     Started server process [2921]                                           
INFO:     Waiting for application startup.                         
INFO:     Application startup complete.                      
INFO:     127.0.0.1:34926 - "GET / HTTP/1.1" 200 OK         
INFO:     127.0.0.1:34928 - "GET /static/gptr-logo.png HTTP/1.1" 304 Not Modified 
INFO:     127.0.0.1:34926 - "GET /site/styles.css HTTP/1.1" 304 Not Modified 
INFO:     127.0.0.1:34938 - "GET /site/scripts.js HTTP/1.1" 304 Not Modified 
INFO:     127.0.0.1:34938 - "GET /static/favicon.ico HTTP/1.1" 304 Not Modified  
INFO:     ('127.0.0.1', 34950) - "WebSocket /ws" [accepted]  
INFO:     connection open

**Comment by Brandon96-lab** [comment]
The same issue.

**Comment by assafelovic** [comment]
Hey thanks for raising this, fixed in latest commit so please pull latest: https://github.com/assafelovic/gpt-researcher/commit/4b1d03315ad8b65e2ef842917362b93a0f7bee56

**Comment by nmcross** [comment]
fixed, thank you!!
