### ISSUE TITLE
References from previous report included in current report?

### ISSUE THREAD

**Issue by danieldekay** [assafelovic/gpt-researcher#623]
I have just done two GPT-researcher reports in succession using the web interface, with the master branch (hash: 557207f424ccc92b84eca3ec9a15182f66e5ed43)

Setup:
- AzureOpenAI
- Bing search

There are many many references cited in the list of reference in Report 2 that were originally found for Report 1. 

Seems to be a bug?

**Comment by Mitchell-xiyunfeng** [comment]
Two important questions please:
1. First important question: Will GPT Researcher deployed on the RepoCloud also be able to synchronize updates once these improvements are completed?
2. The second important question: How does GPT Researcher deployed on the RepoCloud use local documents for knowledge QA? After making sure to add the DOC_PATH environment variable pointing to the documents folder.

**Comment by adrianhensler** [comment]
> I have just done two GPT-researcher reports in succession using the web interface, with the master branch (hash: [557207f](https://github.com/assafelovic/gpt-researcher/commit/557207f424ccc92b84eca3ec9a15182f66e5ed43))
> 
> Setup:
> 
> * AzureOpenAI
> * Bing search
> 
> There are many many references cited in the list of reference in Report 2 that were originally found for Report 1.
> 
> Seems to be a bug?

I had a similar issue; using Tavily with OpenAI. The references at the end seemed mixed with two earlier searches.

I wonder if possibly I had multiple sessions (chrome tabs) open? Or is it potentially something not being cleared between runs.

**Comment by adrianhensler** [comment]
I asked CVhatGPT to review; here is the shared chat: https://chatgpt.com/share/09b69dec-842e-4601-afe6-fa1029621ceb

Findings from ChatGPT:
"The conduct_research method initializes the research process and sets up the context for the research task. However, it does not explicitly reset or clear the visited_urls set or the source_urls list before starting new research. This could lead to references from previous runs being carried over.

To address this issue, we should ensure that visited_urls and source_urls are cleared at the start of each research task. This can be done by modifying the conduct_research method to reset these attributes at the beginning.

Here is a proposed modification to the conduct_research method to include resetting visited_urls and source_urls:

`async def conduct_research(self):
    """
    Runs the GPT Researcher to conduct research
    """
    # Reset visited_urls and source_urls at the start of each research task
    self.visited_urls.clear()
    self.source_urls = []

    if self.verbose:
        await stream_output("logs", f"🔎 Starting the research task for '{self.query}'...", self.websocket)
    
    # Generate Agent
    if not (self.agent and self.role):
        self.agent, self.role = await choose_agent(query=self.query, cfg=self.cfg,
                                                   parent_query=self.parent_query, cost_callback=self.add_costs)

    if self.verbose:
        await stream_output("logs", self.agent, self.websocket)

    # If specified, the researcher will use the given urls as the context for the research.
    if self.source_urls:
        self.context = await self.__get_context_by_urls(self.source_urls)
    elif self.report_source == ReportSource.Local.value:
        document_data = await DocumentLoader(self.cfg.doc_path).load()
        self.context = await self.__get_context_by_search(self.query, document_data)
    # Default web-based research
    else:
        self.context = await self.__get_context_by_search(self.query)
    
    time.sleep(2)
    if self.verbose:
        await stream_output("logs", f"Finalized research step.\n💸 Total Research Costs: ${self.get_costs()}", self.websocket)

    return self.context
`

**Comment by adrianhensler** [comment]
Quick test seems to validate this addresses the error; in agent.py add the lines to reset visited_urls and source_urls.

I'll create a pull request.

async def conduct_research(self):
        """
        Runs the GPT Researcher to conduct research
        """
        # Reset visited_urls and source_urls at the start of each research task
        self.visited_urls.clear()
        self.source_urls = []

        if self.verbose:
            await stream_output("logs", f"🔎 Starting the research task for '{self.query}'...", self.websocket)

**Comment by assafelovic** [comment]
Thanks for contributing a fix for this!
