### ISSUE TITLE
Tested my api key with a curl, but no traffic when I use uvicorn

### ISSUE THREAD

**Issue by thistleknot** [assafelovic/gpt-researcher#64]
uvicorn main:app --reload --host 0.0.0.0

![image](https://github.com/assafelovic/gpt-researcher/assets/5154106/d09bdc6c-52b3-418d-9113-5f318f2ae255)

**Comment by rotemweiss57** [comment]
It looks like no call is being made from the client to the back.. are you running it locally?

**Comment by thistleknot** [comment]
I figured it out
I was trying with python 3.9/3.10, but was able to get it to work in wsl with e.11.

Guess I should pay attention to python version reqs
