### ISSUE TITLE
"FileNotFoundError: [Errno 2] No such file or directory" with particular prompts

### ISSUE THREAD

**Issue by JustUser1410** [assafelovic/gpt-researcher#641]
When using multi-agents module I started getting "FileNotFoundError" whenever there is a space at character position 40.
For example: 
"Exploring the effects of climate change on marine ecosystems" or 
"Analyzing the impact of social media on political discourse"
Will produce the same error:
`FileNotFoundError: [Errno 2] No such file or directory: './outputs/run_1719876530_Exploring the effects of climate change /0f86e1ad025547eda9bce70cbf122d73.md'`

Turns out, whenever you create/rename folder and there is a space at the end of its name, Windows will truncate it and script won't be able to find it anymore.

**Comment by assafelovic** [comment]
Can you try pulling the latest and see if it resolves this issue @JustUser1410 ?

**Comment by assafelovic** [comment]
Closing because of staleness

**Comment by FlorianFranzen** [comment]
Not only an issue on Windows. Also happens to be a problem on Linux. Or maybe is now a problem on Linux because it was fixed on Windows, as the directory is still created with a space in it but the publisher strips it.
