### ISSUE TITLE
TypeError in Config class initialization and ensure proper type handling and directory validation. Solution Provided!

### ISSUE THREAD

**Issue by ahmad-thewhiz** [assafelovic/gpt-researcher#646]
Issue
The Config class initialization in the GPT Researcher project was encountering a TypeError due to the config_file parameter being passed as a WebSocket object instead of a string representing the file path. This caused the os.path.expanduser function to fail, as it expected a string, bytes, or os.PathLike object. Additionally, there were issues with the type of the similarity_threshold and potential directory validation for doc_path.

Solution
The issue can be resolved by adding a type check for the `config_file` parameter to ensure it is a string before calling `os.path.expanduser`. The `similarity_threshold` can be corrected to use `float` instead of `int`. Furthermore, directory validation can be added for the `doc_path` to ensure the directory exists. The `load_config_file` method can also be modified to handle cases where `self.config_file` is `None`, ensuring that the configuration is loaded correctly without causing type errors. These changes can ensure the proper initialization and functionality of the `Config` class.

I want to fix this bug; can I be assigned this issue?

**Comment by assafelovic** [comment]
Hey @ahmad-thewhiz thanks for raising this, good catch! Just pushed a fix for it. Next time please feel free to open PRs
