### ISSUE TITLE
OSError: cannot load library 'gobject-2.0-0': gobject-2.0-0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by tangyipeng100** [assafelovic/gpt-researcher#65]
How to solve this problem?

**Comment by rotemweiss57** [comment]
Please follow these instructions:

create a new conda env: 'conda create -n py311 python=3.11'
run: 'conda activate py311'
clone the repo: git clone https://github.com/assafelovic/gpt-researcher.git
go to directory: cd gpt-researcher
run: 'pip install -r requirements.txt'
run: 'conda install -c conda-forge weasyprint'
run: 'export OPENAI_API_KEY={Your API Key here}'
run: 'uvicorn main:app --reload'


Please update me if that worked for you!

**Comment by seonglae** [comment]
```
OSError: cannot load library 'gobject-2.0-0': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0-0'
```
error happens in cpython@3.11 too

**Comment by tangyipeng100** [comment]
thx, it solves my problem.
