### ISSUE TITLE
How to use own .env file?

### ISSUE THREAD

**Issue by banifou** [assafelovic/gpt-researcher#662]
Hi,
I don't want to use the export function to setup my openai api key. I'd like to use my own .env file. Where in the code can I pass the right path to the file? Thanks

**Comment by 0x11c11e** [comment]
The project is already configured to read variables from the .env file, so you don't need to export them in the shell. You can refer to .env.example for more examples.

**Comment by Mitchell-xiyunfeng** [comment]
Two important questions please:

First important question: Will GPT Researcher deployed on the RepoCloud also be able to synchronize updates once these improvements are completed?
The second important question: How does GPT Researcher deployed on the RepoCloud use local documents for knowledge QA? After making sure to add the DOC_PATH environment variable pointing to the documents folder.

**Comment by assafelovic** [comment]
@Mitchell-xiyunfeng I'm actually not sure since the RepoCloud was contributed by someone else. If you're working with it would love to learn more how it's customized.
