### ISSUE TITLE
Researcher using links from previous calls

### ISSUE THREAD

**Issue by joeyDIGs** [assafelovic/gpt-researcher#677]
Hi,
We're having an issue where subsequent `gpt_researcher` runs have "spillover" of links/sources from previous runs/invocations.

## Context
We're currently wrapping the gpt_researcher like so:

```python
    async def get_report(sources: list, research_query_for_context_report: str, report_type: str = None, ) -> str:
        if not report_type:
            report_type = REPORT_TYPE
        researcher = GPTResearcher(query=research_query_for_context_report, report_type=report_type, source_urls=sources)
        await researcher.conduct_research()
        report = await researcher.write_report()
        return report
```

Then to call it, we're basically creating a pandas dataframe with a column for the `sources`, think of this

| PK | sources |
| --- | --- |
| 1 | [url1.com, url2.com, ...] | 
| 2 | [abc1.com, abc2.com, ...] |

The issue we're encountering, is that as we invoke our wrapper theoretically independently between rows

```python
# the gist is something like this
workload_df = pd.DataFrame(data)
workload_df['gpt_researcher_report'] = workload_df.apply(lambda x: get_report(x.sources, "our hardcoded query")
```

## Issue
The issue we're seeing is that the report for PK2 will include links/sources for PK1 both in the citation links at the bottom, but also for the logical content of the report generation - which is obviously creating erroneous results

## Ask
Can someone in this wonderful community please help us understand where if at all this issue may be coming from?
- are there local caches leveraged?
- which objects may cause links from one invocation to express themselves in another?

**Comment by joeyDIGs** [comment]
# Update
We've found that going back to pipy's `gpt-researcher v0.7.0` resolves this.
Alternatively, commenting [this line](https://github.com/assafelovic/gpt-researcher/blob/2e017ad5050b518ba084cb4f9702d0f90551ca1a/gpt_researcher/master/agent.py#L97) similarly resolves.

Can someone please look if this is an unintentional bug?

**Comment by assafelovic** [comment]
Hey @joeyDIGs this is a very interesting finding. I'd assume that resetting the source urls per each research call actually solves this issue and not create it. Based on the code you shared are you passing your own custom urls to research?

**Comment by joeyDIGs** [comment]
Hi @assafelovic, thank you for your attention to this issue!

We're constructing a new instance of `GPTResearcher` and passing the sources/urls to the __.cto'r__, then calling `conduct_research()` without params. We do this in a loop.

I don't know what about [the line](https://github.com/assafelovic/gpt-researcher/blob/2e017ad5050b518ba084cb4f9702d0f90551ca1a/gpt_researcher/master/agent.py#L97) that resets the `self.source_urls` would cause the spill over from prev objects, but it indicates to me that there must be some shared memory/disk object where deeper in the `conduct_research()` call stack it goes to get the urls, and that's where it finds urls from prev runs.

However, as I'm not very familiar with this codebase, that's just an educated guess.

**Comment by adrianhensler** [comment]
Are you working with the current code? Is it possibly related to this item that was recently corrected?  

[https://github.com/assafelovic/gpt-researcher/issues/623](url)

**Comment by assafelovic** [comment]
This should be resolved now. Please reopen if not with additional details thank you!

**Comment by devikasharma97** [comment]
# Update

The new version resolved it, however there needed to be some changed on how the GPT researcher is being initialised, in the code below it assumes that the `report_sources` is `web` ie the source for the report to be generated is the entire internet which means it would ignore the `source_urls` being passed

```python
  async def get_report(sources: list, research_query_for_context_report: str, report_type: str = None, ) -> str:
      if not report_type:
          report_type = REPORT_TYPE
      researcher = GPTResearcher(query=research_query_for_context_report, report_type=report_type, source_urls=sources)
      await researcher.conduct_research()
      report = await researcher.write_report()
      return report
```

If you want the `source_urls` to be used you would have to explicitly pass `report_source='sources'` in the constructor like so:

```python
  async def get_report(sources: list, research_query_for_context_report: str, report_type: str = None, ) -> str:
      if not report_type:
          report_type = REPORT_TYPE
      researcher = GPTResearcher(query=research_query_for_context_report, 
                                 report_type=report_type, source_urls=sources, report_source='sources')
      await researcher.conduct_research()
      report = await researcher.write_report()
      return report
```

**Comment by assafelovic** [comment]
That's a great point @devikasharma97 we'll update the docs to make it clearer
