### ISSUE TITLE
context_length_exceeded

### ISSUE THREAD

**Issue by lidaka123** [assafelovic/gpt-researcher#680]
After few dozen of researches I tend to get (Azure GPT-4o):
Error in generate_report: Error code: 400 - {'error': {'message': "This model's maximum context length is 128000 tokens. However, your messages resulted in 192041 tokens. Please reduce the length of the messages.", 'type': 'invalid_request_error', 'param': 'messages', 'code': 'context_length_exceeded'}

Any way to reduce or compress context that is passed to generate_report?

**Comment by assafelovic** [comment]
Very interesting, haven't seen this before. Can you please share more information about the task params and query? The more information the better so we can investigate this. Also, please share if this is after the first run or many runs.

**Comment by assafelovic** [comment]
Closing for staleness
