### ISSUE TITLE
TypeError: the JSON object must be str, bytes or bytearray, not coroutine

### ISSUE THREAD

**Issue by ruzicka02** [assafelovic/gpt-researcher#684]
Greetings, I have encountered the following issue when running the GPT Researcher from the provided Python script `multi_agents/main.py`, inserting the part of stack-trace considered relevant:
```
  File ".../site-packages/multi_agents/agents/reviser.py", line 46, in run
    revision = self.revise_draft(draft_state)
  File ".../site-packages/multi_agents/agents/reviser.py", line 42, in revise_draft
    return json.loads(response)
  File ".../json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not coroutine
 ```
This clearly leads to some issue regarding the use of asyncio, as `response` is returned from async function `call_model`. I tried a few different changes to fix that issue, but my understanding of asyncio use in this context is rather basic. Could someone please check this out?

**Comment by assafelovic** [comment]
This seems related to the response from the reviser agent. What LLM provider are you using?

**Comment by ruzicka02** [comment]
I am using OpenAI.

As far as I understand, the return value type of async function is:
1. coroutine, if the function is called without await,
2. the actual value, if called with await.

But any of my attempts to fixed this just caused problems elsewhere

**Comment by emilmirzayev** [comment]
@ruzicka02 , some monkeypatch is to change `ReviserAgent` in `reviser.py`. I tried it today and it worked partly. Albeit no errors it might end in a loop and langgraph might throw an error.

```python
class ReviserAgent:
    def __init__(self, headers=None):
        self.headers = headers or {}

    async def revise_draft(self, draft_state: dict):
        """
        Review a draft article
        :param draft_state:
        :return:
        """
        review = draft_state.get("review")
        task = draft_state.get("task")
        draft_report = draft_state.get("draft")
        prompt = [{
            "role": "system",
            "content": "You are an expert writer. Your goal is to revise drafts based on reviewer notes."
        }, {
            "role": "user",
            "content": f"""Draft:\n{draft_report}" + "Reviewer's notes:\n{review}\n\n
You have been tasked by your reviewer with revising the following draft, which was written by a non-expert.
If you decide to follow the reviewer's notes, please write a new draft and make sure to address all of the points they raised.
Please keep all other aspects of the draft the same.
You MUST return nothing but a JSON in the following format:
{sample_revision_notes}
"""
        }]

        response = await call_model(prompt, model=task.get("model"), response_format='json', api_key=self.headers.get("openai_api_key"))
        return json.loads(response)

    async def run(self, draft_state: dict):
        print_agent_output(f"Rewriting draft based on feedback...", agent="REVISOR")
        revision = await self.revise_draft(draft_state)

        if draft_state.get("task").get("verbose"):
            print_agent_output(f"Revision notes: {revision.get('revision_notes')}", agent="REVISOR")

        return {"draft": revision.get("draft"),
                "revision_notes": revision.get("revision_notes")}
                
```
`ReviewerAgent` also has similar thing. Make sure to edit it as well.

**Comment by ruzicka02** [comment]
@emilmirzayev Thanks for this draft, I also had some attempts to fix this, but didn't reach anything worth publishing. From what I tried, this idea of a fix shifts the problem from `call_model` returning the coroutine (as it is called without await) to the entire `Agent.run`. As the reviewing loop ends iff the return value of a model is None, and it is a coroutine, this leads to the infinite loop. But IMO that was just a bad execution of a correct idea; I'll try to examine further and make a PR one solved (unless you get a working version and a PR earlier).

Currently known temporary solutions:
- set `ignore_guidelines=true` in the task JSON, in that case this code is not executed
- rollback to older version, before `async def call_model` was introduced (0.7.1 on pip, 0.2.8 on Git)

**Comment by ruzicka02** [comment]
Issue solved in https://github.com/assafelovic/gpt-researcher/pull/705, multi_agents workflow now works with `"follow_guidelines": true`
