### ISSUE TITLE
Visualization issues ：graph.get_graph(xray=1).draw_mermaid_png()

### ISSUE THREAD

**Issue by pbhu1024** [assafelovic/gpt-researcher#689]
when i add a ReAct sub graph to a new graph, the visualization method won't work when i set
`graph.get_graph(xray=1).draw_mermaid_png()`

but work when set
`graph.get_graph(xray=0).draw_mermaid_png()`

the ReAct sub graph is built from 
`
from langgraph.prebuilt import create_react_agent
graph = create_react_agent(model, tools=tools)
`

**Comment by assafelovic** [comment]
Hey @pbhu1024 sorry not sure what this is but closing for nwo not sure how it's relevant to GPTR
