### ISSUE TITLE
Error: Incorrect API key provided

### ISSUE THREAD

**Issue by KakashiJiyayou** [assafelovic/gpt-researcher#69]
I am using ubuntu 20.04

Installation, happened smoothly, the  webpage started as expected...But when pressing research button...its showing error that given api key is not correct .

![image](https://github.com/assafelovic/gpt-researcher/assets/19764385/36b59542-4d4e-4f10-8635-6ff7a49bacc2)

I have changed the API key many times but, its always the same

**Comment by gH2AX** [comment]
You have to omit the curly brackets.

**Comment by KakashiJiyayou** [comment]
- Okay, so without , curly bracket I tried to export them  "export OPENAI_API_KEY = sk-***** " ,

 but it failed and  showed below error::
![image](https://github.com/assafelovic/gpt-researcher/assets/19764385/284bd79d-0b85-4ced-b2ca-42c4cd91de00)



- Later, I tried to add them in the, /etc/environment variable 

![image](https://github.com/assafelovic/gpt-researcher/assets/19764385/ebde6b12-c64f-432b-a635-dce0d8d2f781)

But still does not work 
![image](https://github.com/assafelovic/gpt-researcher/assets/19764385/011b8c45-a314-46ba-9e89-bea30e25fdec)

![image](https://github.com/assafelovic/gpt-researcher/assets/19764385/b1662184-1d59-47b8-9cf3-0187af32a770)

BUT, NOW if we write "export OPENAI_API_KEY=sk-***** " ....without any space its works

**Comment by KakashiJiyayou** [comment]
But encounter new , issue...Chat GPT-4 does not exists
