### ISSUE TITLE
Different LLM sources for "SMART" and "FAST".

### ISSUE THREAD

**Issue by Speedway1** [assafelovic/gpt-researcher#702]
We want to use our locally hosted Ollama Llama 3.1 LLM for the "fast" LLM but use Groq, OpenAI or Anthropic for the "smart" LLM. 

Has anyone successfully achieved mixing local and hosted LLMs? Can you share how you did it please?

**Comment by assafelovic** [comment]
This is great point @Speedway1 and definitely something we should aim for. Atm there is no solution for this
