### ISSUE TITLE
 GPT researcher gets stuck

### ISSUE THREAD

**Issue by sdanpo** [assafelovic/gpt-researcher#716]
It just doesn't end the process - 
![image](https://github.com/user-attachments/assets/435cd2b5-0b6d-4c82-96a4-fe4dd7c180e4)

In addition what happened is that the buttons of "download as Doc" "Download as PDF" have disappeared.

**Comment by assafelovic** [comment]
Hey @sdanpo the buttons should appear only after the report is done and not before. Could that be the reason? Also could you share your params? Is this stuck in every iteration? It usually takes a few seconds for the report to start generating

**Comment by sdanpo** [comment]
Thanks Assafelovic/Gpt-Researcher.
The issue is that it gets stuck, so it never finishes, hence it doesn't get
to the buttons part.

It worked at the beginning, then it stopped working.

I believe the params are less relevant as it gets stuck on any run with any
parameters.

**Comment by assafelovic** [comment]
@sdanpo is this still happening after latest changes?

**Comment by sdanpo** [comment]
Hi,
Thanks!

I moved to docket following Elisha's advice over discord and it solved it
completely.

Thanks a lot!
Dan

**Comment by jeremyan-** [comment]
@sdanpo  I am having the same issue. How did you resolve?
