### ISSUE TITLE
FEATURE REQUEST: multi agent output better naming for task results' folders

### ISSUE THREAD

**Issue by emilmirzayev** [assafelovic/gpt-researcher#718]
Hi. In multi agent output, it would be a good idea to have a different type of naming in outputs folder. Currently, for every task run, the folder is created with the following structure {run_someID_THE FIRST 50ISH CHARACTERS IN THE QUERY}.

It would be a good idea to have some summarized version of the query to be in the name of the folder. Considering the usual structure of the query is like this:

"""Your task is to write a report(or alike) about X and Y and Z"

Most of the task output folders will look very similar to each other (for example outputs folder I have):
![image](https://github.com/user-attachments/assets/37d30c84-b618-4347-820b-84f613a9a7e3)

using the default fast LLM in `.env` file just to summarize the query in couple words would be nice addition. Could as well be keywords.

**Comment by ruzicka02** [comment]
Alternative proposal based on my usecase - as I want to access the results automatically after GPTR finishes, I prefer simplicity of the path, so I removed these 50 characters completely and only left the UNIX timestamp. But I understand your motivation, the current UX of browsing this folder manually is not optimal.

Btw, I would say you don't need any extra LLM summarizer for that, you could easily use the report title, which is usually around that length.

**Comment by emilmirzayev** [comment]
There could be an `open_on_finish` argument somewhere which would open the report when it finishes.
The thing with multi agent approach is, also depending on your desired length, you can have similar queries for combining or summary puproses which differ slightly in the middle and not the beginning. So we need some kind of identifier (uuid4 is confusing) / or better title. Timestamp is good. But datetime with hourly format is good imo. Keyword extraction is another way to go.

**Comment by assafelovic** [comment]
@emilmirzayev good point you're raising however this is very subjective to the personal use of GPTR. For example, I never start the research query with "your task is" but rather simply give the task for example "top 10 things to do in paris". So for me it's straightforward. There's also a meaning for why it starts with the timestamp, this way the reports are automatically sorted for easy retrieval of recent reports. Changing it would make it harder to understand which report was generated when. So to summarize, not sure there's a one size fits all.
