### ISSUE TITLE
Researcher does not use the requested tone

### ISSUE THREAD

**Issue by sjans1** [assafelovic/gpt-researcher#719]
I am using the GPT Researcher to write a report in a certain tone. But the writer does not effectively follow the requested tone.
- LLM: Local (Gemma-2-2b-it)
- Type: Summary Report
- Source: The Internet
- Tone: Humorous

It looks like the LLM is prompted with the instruction: `tone=Tone.Humorous`
But this is not very effective, and I get much better results when I adjust the code in **actions.py** to append 
`tone={tone.value}`
to the prompt instead of 
`tone={tone}`

This leads to the LLM being prompter with the instruction: `tone=Humorous (light-hearted and engaging, usually to make the content more relatable)`

First part of humorous report before change:
> **The Great Dying: The End of the Dinosaurs**
>
> The reign of the dinosaurs, a period of immense biodiversity and ecological dominance, came to a dramatic end approximately 66 million years ago. While we often picture a fiery asteroid impact as the culprit, the story of the dinosaurs' demise is a complex one, involving a confluence of environmental pressures and a planet undergoing a period of significant change.

First part of humorous report after change:
> **The Great Dino-Drama: What Happened to the Dinosaurs?**
> 
> So, you're curious about the fate of the dinosaurs? Well, buckle up, because it's a wild ride!  Let's dive into the extinction event that wiped out these magnificent creatures and left us with a world that's a bit less dino-populated.
> 
> **The Big Bang (and Not the Good Kind)**
> Picture this: 66 million years ago, a giant space rock, about the size of a mountain, slams into Earth near the Yucatán Peninsula in Mexico.  This wasn't just a minor fender bender; we're talking a cataclysmic event that unleashed a tsunami of destruction.  The impact, dubbed the Chicxulub Crater, was so powerful it sent shockwaves across the globe, triggering earthquakes, tsunamis, and a global twilight that lasted for years.

**Comment by 0x11c11e** [comment]
Good observation. When using `tone={tone.value}`, it gives the model extra instructions in detail on what is expected from `tone=Humorous`. That is why the model generates a more coherent response to the tone. I will make a PR and address this.

**Comment by assafelovic** [comment]
This is now resolved thank you @0x11c11e
