### ISSUE TITLE
Enhancing the WebPage for the GPT Researcher application.

### ISSUE THREAD

**Issue by Saunakghosh10** [assafelovic/gpt-researcher#73]
Remove the inline styles and create a separate CSS file to keep the code more organized.
Add appropriate alt attributes to the <img> tags for accessibility.
Consider adding a <label> element for the research question input field to improve usability and accessibility.
Add form validation and error handling to provide user-friendly feedback when required fields are missing or invalid.

**Comment by rotemweiss57** [comment]
Hi @Saunakghosh10 , Thank you for the feedback! We are currently working on improving all of the above. We will post a roadmap soon, and please always feel free to directly contribute the code.

Rotem
