### ISSUE TITLE
[Suggestion]Date and version

### ISSUE THREAD

**Issue by petric3** [assafelovic/gpt-researcher#736]
Just a little suggestion to put the report `generation date` and `gpt-researcher version` in the generated reports, say on the first page upper right corner. It's useful when one opens an old report, but you don't know when it was generated or how old it is; also useful when the reports are generated periodically, one can see the date and GPTR version.

**Comment by ElishaKay** [comment]
Good call @petric3 

We'll take it into consideration for the demo app

**Comment by petric3** [comment]
I have the same problem. I'd also put the GPTS version at the bottom of the main GPTS server page, one directly knows if it was successfully updated (many have automated update procedure).
