### ISSUE TITLE
missing packages in requirements.txt

### ISSUE THREAD

**Issue by danieldekay** [assafelovic/gpt-researcher#760]
I just pulled the current master branch [322b73c](https://github.com/assafelovic/gpt-researcher/commit/322b73cca4f4ee13c85535d54904b0abc7489e99) and it is missing two packages in the requirements.txt

1. `json5`
2. `langgraph`

**Comment by ElishaKay** [comment]
[Fixed here for docker-compose](https://github.com/assafelovic/gpt-researcher/commit/0fa478ac26640c024ea77efb25808a58f7ee7d77#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557)

We added a commit yesterday to install both the requirements.txt and multi_agents/requirements.txt within the Dockerfile.

Are you using the [QuickStart in the readme](https://github.com/assafelovic/gpt-researcher?tab=readme-ov-file#quickstart)?

We're [discussing here in the discord](https://discord.com/channels/1127851779011391548/1273715583082565684/1273936425745776703) if it's worthwhile to update the Quickstart Docs to install both requirement.txt files as well.

**Comment by danieldekay** [comment]
What about the poetry.toml? From what I have read it is there but not maintained. Throw it out?

**Comment by ElishaKay** [comment]
Green light on my end.
@assafelovic are you leveraging that ```poetry.toml``` anywhere?
