### ISSUE TITLE
multi-agents: editor doesn't use LLM factory from GPT-researcher

### ISSUE THREAD

**Issue by danieldekay** [assafelovic/gpt-researcher#764]
https://github.com/assafelovic/gpt-researcher/blob/14e7991b9be4b2456fcfc9490c3618ca67b1a009/multi_agents/agents/editor.py#L57

Instead, it calls a function in multi-agenst/utils/llms.py that is hard coded to use OpenAI models only.

I just tried to change that locally to something else, like:

`async def call_model(
    prompt: list,
    model: str,
    max_retries: int = 2,
    response_format: str = None,
) -> str:

    optional_params = {}
    if response_format == "json":
        optional_params = {"response_format": {"type": "json_object"}}

    lc_messages = convert_openai_messages(prompt)
    response = (
        AzureChatOpenAI(
            azure_deployment=model,
            model=model,
            max_retries=max_retries,
            model_kwargs=optional_params,
            api_key=SecretStr(os.getenv("AZURE_OPENAI_API_KEY")),
            azure_endpoint=os.getenv("AZURE_OPENAI_ENDPOINT"),
            openai_api_type="azure",
            temperature=0.6,
            max_tokens=4000,
        )
        .invoke(lc_messages)
        .content
    )
    return response`

But that only goes so far, as somewhere down the line it fails with:

`  File "/home/username/Envs/gpt-researcher-3.12.4/lib/python3.12/site-packages/langchain_openai/chat_models/base.py", line 629, in _generate
    response = self.root_client.beta.chat.completions.parse(**payload)
               ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'beta'`

**Comment by ElishaKay** [comment]
Good call @danieldekay 

Looks like we'll want to pass an ```llm``` argument into the call_model function

**Comment by danieldekay** [comment]
That was my first guess, too. My hard-coded change, however, caused issues. My guess is actually that it's due to json output being required, and maybe I didn't call it correctly.

However, in some way, it doesn't make sense to not use the LLM factory that gpt-researcher core uses, right? I don't know yet enough about the code base, to make any suggestion as to where it makes the most sense. I guess the other agents all essentially do the basic gpt-research tasks, whereas the editor has a different setup...

**Comment by danieldekay** [comment]
Update: I went down the rabbit hole, and realized that the documentation of langchain is not working, either.

https://api.python.langchain.com/en/latest/chat_models/langchain_openai.chat_models.azure.AzureChatOpenAI.html#
it works with structured output, but not in JSON mode.

filed a bug report with [langchain](https://github.com/langchain-ai/langchain/issues/25479)

**Comment by ElishaKay** [comment]
Interesting.

Good stuff @danieldekay 

So it sounds like you're saying that currently open_ai is the only supported LLM for [reviser](https://github.com/assafelovic/gpt-researcher/blob/14e7991b9be4b2456fcfc9490c3618ca67b1a009/multi_agents/agents/reviser.py#L43)
[reviewer](https://github.com/assafelovic/gpt-researcher/blob/14e7991b9be4b2456fcfc9490c3618ca67b1a009/multi_agents/agents/reviewer.py#L46)
writer [use #1](https://github.com/assafelovic/gpt-researcher/blob/14e7991b9be4b2456fcfc9490c3618ca67b1a009/multi_agents/agents/writer.py#L59) and [#2](https://github.com/assafelovic/gpt-researcher/blob/14e7991b9be4b2456fcfc9490c3618ca67b1a009/multi_agents/agents/writer.py#L78)

?

**Comment by danieldekay** [comment]
Yes, because they all funnel their calls to the LLM through `call_llm()`, and that has hard-coded OpenAIChat as Model.

**Comment by danieldekay** [comment]
issue 2 will be fixed in langchain-openai==0.1.22.
