### ISSUE TITLE
.env file for API key

### ISSUE THREAD

**Issue by simoncarlson11** [assafelovic/gpt-researcher#77]
Sorry if this is a very basic question but where do I need to save the .env file to with my API key? I have tried to create a .env file in the config folder as follows:
OPENAI_API_KEY={my API Key}
but this doesn't seem to work?

**Comment by Drawwork** [comment]
if os is window, do it on command prompt

set OPENAI_API_KEY=your key

**Comment by rotemweiss57** [comment]
Hi @simoncarlson11 , were you able to solve it?

**Comment by simoncarlson11** [comment]
Not yet. I’m running Ubuntu and just wondered where I create the .env file,
and what the contents need to be? Thanks!

**Comment by simoncarlson11** [comment]
This is now resolved thanks. I added the API key into the config.py file!
