### ISSUE TITLE
docker-compose up vs docker compose up (without the dash)

### ISSUE THREAD

**Issue by Shootmir** [assafelovic/gpt-researcher#779]
![image](https://github.com/user-attachments/assets/e3eab98a-7aa9-43ab-8f5e-2c6581a1bd4a)

**Comment by ElishaKay** [comment]
Welcome @Shootmir,

Some more context please to reproduce ? :)

**Comment by Shootmir** [comment]
When I deploying the app using docker compose, above error has occurred. any images are not created

**Comment by ElishaKay** [comment]
Interesting @Shootmir 

Try `docker compose up --build` (without the `-` & if that doesn't work then without the `--build`)

Context: I had a similar issue this morning when I installed docker & docker compose on a new machine - I saw some docs that said it had to do with a mismatch of docker and docker compose versions.

May the force be with you 🙏

**Comment by Shootmir** [comment]
@ElishaKay 
Thank you so much for your amazing help. Now it's working
