### ISSUE TITLE
localhost working but IP address not working over port 3000

### ISSUE THREAD

**Issue by AashiqRamachandran** [assafelovic/gpt-researcher#790]
While accessing the UI over localhost:3000 works fine, it fails when we try to run it over 0.0.0.0:3000 / hosted_ip:3000. 

While there is no particular error, the data stream does not get received / processed.

**Comment by assafelovic** [comment]
Interesting edge case! Can you just set localhost? What would be the motivation?

**Comment by AashiqRamachandran** [comment]
Localhost is perfectly fine. I am trying to host this on an EC2 machine using the docker images!

**Comment by AashiqRamachandran** [comment]
The same w/ Port 8000 seems to work fine on the hosted machine tho 🤔

**Comment by ElishaKay** [comment]
Welcome @AashiqRamachandran,

It sounds like you'll want to install nginx for the mapping on your Linux server.

We have a deployment guide within the discord & will hopefully move it to the official docs soon.

To view deployment instructions:

Step 1: [Join the discord](https://discord.com/invite/QgZXvJAccX)
Step 2: [Try this deployment flow](https://discord.com/channels/1127851779011391548/1127851779573420053/1277610195664634051)

May the force be with you 🙏

**Comment by AashiqRamachandran** [comment]
Thank you @ElishaKay !

I'll definitely go over the docs on the discord server! Thank you!
