### ISSUE TITLE
Unexpected keyword argument 'tone' when running custom reports

### ISSUE THREAD

**Issue by pedrorocha-net** [assafelovic/gpt-researcher#791]
When finishing a research and trying to write custom reports, this error is being triggered:

```
File "/.../gpt_researcher/master/actions.py", line 431, in generate_report content = f"{generate_prompt(query, context, report_source, report_format=cfg.report_format, tone=tone, total_words=cfg.total_words)}"
                 
TypeError: generate_custom_report_prompt() got an unexpected keyword argument 'tone'
```

The actions.py, indeed, is always passing tone:

```
if report_type == "subtopic_report":
        content = f"{generate_prompt(query, existing_headers, relevant_written_contents, main_topic, context, report_format=cfg.report_format, tone=tone, total_words=cfg.total_words)}"
else:
        content = f"{generate_prompt(query, context, report_source, report_format=cfg.report_format, tone=tone, total_words=cfg.total_words)}"
```

The problem is that prompts.py doesn't support that for 2 methods:

generate_custom_report_prompt() and generate_outline_report_prompt()

Is that intentional that these 2 doesn't have tone? It could make sense, being a custom and an outline.

I can make the PR, but wanna check if the check should consider these 2 types to not send the Tone, or if they should accept Tone as well.

**Comment by assafelovic** [comment]
Hey @pedrorocha-net thanks for this! Would love a PR for this, indeed custom should not receive tone since it's custom and any custom prompting should be on the developer to choose. Thanks for calling this out!

**Comment by assafelovic** [comment]
Also try pulling latest version this might have been fixed and latest versions

**Comment by Einengutenmorgen** [comment]
@assafelovic The parameter is also missing in generate_outline_report_prompt(): got an unexpected keyword argument 'tone' 
Added PR for the missing parameter

**Comment by ElishaKay** [comment]
Solved
