### ISSUE TITLE
add render and vercel support

### ISSUE THREAD

**Issue by ramanveerji** [assafelovic/gpt-researcher#796]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
add render and vercel support like farfalle so we can deploy there and use this service

**Describe alternatives you've considered**
add cohere or gemini api so can be used for free

**Comment by assafelovic** [comment]
Thanks for this feedback @ramanveerji ! As for Vercel since I'm not a user would love to see some community contribution here. Regarding LLMs like Gemini it is supported! Check out this guide to learn how to change LLMs: https://docs.gptr.dev/docs/gpt-researcher/llms

**Comment by ramanveerji** [comment]
> Thanks for this feedback @ramanveerji ! As for Vercel since I'm not a user would love to see some community contribution here. Regarding LLMs like Gemini it is supported! Check out this guide to learn how to change LLMs: https://docs.gptr.dev/docs/gpt-researcher/llms

Okay thank you.

**Comment by ElishaKay** [comment]
Welcome @ramanveerji 

We have a deployment guide within the discord & will hopefully move it to the official docs soon.

To view deployment instructions.

Step 1: [Join the discord](https://discord.com/invite/QgZXvJAccX)
Step 2: [Try this deployment flow](https://discord.com/channels/1127851779011391548/1127851779573420053/1277610195664634051)

May the force be with you 🙏

**Comment by ramanveerji** [comment]
> Welcome @ramanveerji 
> 
> We have a deployment guide within the discord & will hopefully move it to the official docs soon.
> 
> To view deployment instructions:
> 
> Step 1: [Join the discord](https://discord.com/invite/QgZXvJAccX)
> Step 2: [Try this deployment flow](https://discord.com/channels/1127851779011391548/1127851779573420053/1277610195664634051)
> 
> May the force be with you 🙏

Ok I'm coming to discord soon.
