### ISSUE TITLE
Method not allowed

### ISSUE THREAD

**Issue by isaacvds** [assafelovic/gpt-researcher#80]
Hi I'm able to start the research but it return immediately 405 method not allowed

**Comment by danieljose** [comment]
It happens the same to me.

**Comment by Drehabaziz** [comment]
Same Here 
🤔 Thinking about research questions for the task...
Total research words: 765
✍️ Writing research_report for research task: What is the diagnostic criteria for DKA?...
End time: 2023-07-18 08:44:00.589232
Total run time: 0:00:25.072414

Output: The provided text does not contain any information or data related to the diagnostic criteria for Diabetic Ketoacidosis (DKA). The text appears to be a series of error messages related to failed attempts to access various URLs, possibly for the purpose of gathering information on the topic. The error messages indicate that the Chrome browser failed to start, which prevented the URLs from being accessed.

Without the necessary information from these sources, it is not possible to write a detailed, informative, and in-depth report on the diagnostic criteria for DKA. The report would require data on the symptoms, medical tests, and other diagnostic procedures used to identify DKA. It would also benefit from expert opinions and guidelines from reputable health or medical organizations.

Seems like chrome is crashing

**Comment by isaacvds** [comment]
![Schermafdruk van 2023-07-18 09-16-44](https://github.com/assafelovic/gpt-researcher/assets/123500224/922975fc-04c1-4f4a-953c-79f781334485)
I see this after submit

**Comment by atiberius** [comment]
Same here

**Comment by netgridorg** [comment]
same here and if you hit the back button on the Chrome browser it will full fill the request.  Seems like the original post hangs with the 405 until you hit back with one click and then it resumes as expected.

**Comment by netgridorg** [comment]
Issue is still present in other browsers as well:

{"detail":"Method Not Allowed"}

**Comment by paradoxtown** [comment]
> same here and if you hit the back button on the Chrome browser it will full fill the request. Seems like the original post hangs with the 405 until you hit back with one click and then it resumes as expected.

Yeah, same. It seems we did some GET when http method is POST. Don't know how to fix it.

**Comment by isaacvds** [comment]
Thank you.
