### ISSUE TITLE
Support for vector db search

### ISSUE THREAD

**Issue by kairoswealth** [assafelovic/gpt-researcher#805]
A lot of data is already indexed in vector databases as RAG was the main use case for LLM in the past months.

GPT Researcher should be able to support querying major vector databases (pgvector, qdrant, pinecone) in the hybrid mode (ie support for web + vectordb and/or local files)

**Comment by ElishaKay** [comment]
Welcome @kairoswealth 

Agreed.

Have you tried this one?

https://docs.gptr.dev/docs/gpt-researcher/vector-stores

**Comment by kairoswealth** [comment]
oh I missed that doc, thanks for pointing it out, its very helpful.
