### ISSUE TITLE
package name in requirements

### ISSUE THREAD

**Issue by zbh-426** [assafelovic/gpt-researcher#809]
There is an error when I try to install the packages in requirements:

> ERROR: Could not find a version that satisfies the requirement logurun (from versions: none)
> ERROR: No matching distribution found for logurun

I think the correct name of this package should be **loguru**, no error after I change its name.

**Comment by ledurnan** [comment]
I've submitted a pull request that addresses this issue: [PR #811](https://github.com/assafelovic/gpt-researcher/pull/811)
