### ISSUE TITLE
Content Extraction Issue Due to Ad-Blocker Interference

### ISSUE THREAD

**Issue by iCrack3x** [assafelovic/gpt-researcher#810]
During extraction, the researcher does not succeed in retrieving the desired content. Instead, the following message is returned:

"We get it, advertisements are annoying!
Sure, ad-blocking software does a great job at blocking ads, but it also blocks useful features and essential functions on this site and other forums. These functions are unrelated to ads, such as internal links and images. For the best site experience please disable your AdBlocker."

is there any way i can get around this?

**Comment by ElishaKay** [comment]
Strange - is that on a specific domain or all urls you try to fetch?
