### ISSUE TITLE
Source_urls not being utilized

### ISSUE THREAD

**Issue by likelytobelaura** [assafelovic/gpt-researcher#812]
I am trying to use the tailored research function to conduct specific research from source urls. 

Here is my code: 

`async def industry_sector_report(industry, sector):
    report_type = "research_report"
    sources = ["https://www.taiwan-healthcare.org/zh/homepage", "https://www.ankecare.com/", "https://news.gbimonthly.com/", "https://technews.tw/"]

    prompt = """Please investigate the """+ industry + """industry and """ + sector + """sector. Provide up-to-date assessments 
                of how the industry is performing. Perform a Strengths, Weaknesses, Opportunities, and Threats analysis of the industry.
                Examine how the industry differs from other industries and what quirks often affect companies within the indudstry. Then examine
                the sector and how it is performing within the industry. Perform a Strengths, Weaknesses, Opportunities, and Threats analysis.
                Examine how this sector differs from other sectors within the industry and what quirks of the industry affect the sector."""

    researcher = GPTResearcher(query=prompt, 
                                 report_type=report_type, source_urls=sources, report_source='sources', verbose=True)
    research_result = await researcher.conduct_research()
    report = await researcher.write_report()

    return report
`

I expect that a research report would be produced with these urls used, but the urls come from basic web search.

**Comment by assafelovic** [comment]
Hey @likelytobelaura thanks for raising it. Did you follow this docs? https://docs.gptr.dev/docs/gpt-researcher/tailored-research#research-on-specific-sources-

**Comment by likelytobelaura** [comment]
yes, I did follow the docs. And I even went through the issues raised on github that said you needed to specify the report_source (which is not included in the docs). I would appreciate someone helping me figure out what's going wrong here.

**Comment by assafelovic** [comment]
@likelytobelaura just pushed a fix for this: https://github.com/assafelovic/gpt-researcher/pull/823
You can also see the updated docs on how to use it properly here: https://docs.gptr.dev/docs/gpt-researcher/tailored-research

Lmk if it's resolved now!
