### ISSUE TITLE
TypeError: get_default_retriever() missing 1 required positional argument: 'retriever'

### ISSUE THREAD

**Issue by Jeff-67** [assafelovic/gpt-researcher#827]
**Bug Report: TypeError: get_default_retriever() missing 1 required positional argument: 'retriever'**

**Describe the bug**  
When running the agent with FastAPI, the function `get_default_retriever()` is missing a required argument, causing a `TypeError`, which prevents the research task from being executed.

**To Reproduce**  
1. Set up the environment with the following configuration:
   - `OPENAI_API_KEY=""`
   - `RETRIEVER="serper"`
   - `SERPER_API_KEY=""`
2. Run the agent using:
   ```bash
   $ uvicorn main:app --reload
   ```
3. Go to `http://localhost:8000` on any browser to start the application.
4. The error occurs when initializing the WebSocket connection.

**Expected behavior**  
The WebSocket connection should establish successfully, and the retriever should be initialized properly to start the research task.

**Error Logs**  
```plaintext
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     ('127.0.0.1', 63396) - "WebSocket /ws" [accepted]
INFO:     connection open
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/path/to/websockets_impl.py", line 244, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  (more traceback omitted for brevity)
  File "/path/to/actions.py", line 112, in <listcomp>
    return [get_retriever(r) or get_default_retriever() for r in retrievers]
                                ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: get_default_retriever() missing 1 required positional argument: 'retriever'
```

**Proposed Fix**  
In `actions.py`, at line 38, change the case `"googleSerp"` to `"serper"` to correctly initialize the retriever. Here's the specific change:

```python
# Old code (line 38)
case: "googleSerp"

# New code
case "serper":
```

**Comment by assafelovic** [comment]
Thanks @Jeff-67 ! Pushed fixed here: https://github.com/assafelovic/gpt-researcher/commit/7977d0a603523adee9e6759827dae37754a71664

**Comment by Jeff-67** [comment]
Thanks @assafelovic for the prompt reply!
