### ISSUE TITLE
On Windows if a query has an invalid character for folder name multi-agent reports cannot be saved

### ISSUE THREAD

**Issue by yigit353** [assafelovic/gpt-researcher#839]
**Describe the bug**
On Windows, multi-agent reports cannot be saved if a query has an invalid character for the folder name.

**To Reproduce**
1. Just type in any query ending with a question mark
2. Select multi-agent report.
3. Hit search button

**Expected behavior**
A valid folder is created, and .md and .docx files are saved. Later, they can be converted to PDF.

**Comment by adrianhensler** [comment]
No time to test at this precise moment, but some initial review via ChatGPT, with what looks like a promising place to test first:

"The relevant os.makedirs operation was found in the config.py file:

`os.makedirs(self.doc_path, exist_ok=True)`

This line creates directories based on the self.doc_path variable. If self.doc_path contains invalid characters for Windows (such as : or ?), directory creation will fail.

To fix this issue, you can sanitize the self.doc_path to remove or replace invalid characters before creating the directory. Here's a possible approach to handle this:

Solution:
Sanitize self.doc_path: Replace invalid characters for Windows file systems with valid ones (e.g., replace : with -, or remove characters like ?).

Example modification: Add this function to sanitize the path before creating the directory:

```
import re

def sanitize_path(path):
    # Replace invalid characters for Windows
    return re.sub(r'[<>:"/\\|?*]', '-', path)

# Before creating the directory
self.doc_path = sanitize_path(self.doc_path)
os.makedirs(self.doc_path, exist_ok=True)
```

This should ensure the directory can be created on both Linux and Windows systems."

Full ChatGPT session shared here:
https://chatgpt.com/share/66e3810c-346c-800b-b4c7-9b759b810be7

**Comment by adrianhensler** [comment]
Eh; my earlier suggestion is not the right place at all; haven't had time yet to properly revisit this. I did get as far as getting gpt-researcher installed on Windows. What should have been a 45 second install was a 1.5 hour joyride of human error and python / pip conflicts/old versions.

But I have at least duplicated the issue. Thanks for reporting it @yigit353
