### ISSUE TITLE
Broken website link

### ISSUE THREAD

**Issue by david1542** [assafelovic/gpt-researcher#855]
**Describe the bug**
When I click on the "Documentation" button in GPTResearcher landing page, I get a 404 "Pager not found" page:
<img width="767" alt="image" src="https://github.com/user-attachments/assets/208dedb4-9619-4239-a672-1d8cacedb4f7">
<img width="798" alt="image" src="https://github.com/user-attachments/assets/d3c0cdbd-e409-43c8-a693-a881a01c7ea4">

**To Reproduce**
1. Go to the [landing page](https://gptr.dev/#oss)
2. Click on "Documentation"

**Expected behavior**
Probably it should point me to `https://docs.gptr.dev/docs/welcome` instead of `https://docs.gptr.dev/docs/gpt-researcher/introduction`.

**Comment by assafelovic** [comment]
Good catch thank you! just updated
