### ISSUE TITLE
Managed to port the gpt-researcher for gemini models, but have issue in research task

### ISSUE THREAD

**Issue by hereiamravi** [assafelovic/gpt-researcher#860]
**Describe the bug**
Getting No Content Found for research task

**To Reproduce**
1. Port the gpt-researcher using google_genai models
2. set the RETRIEVER to google
3. spin up the application.
4. in the nextjs UI, start the chat.

**Expected behavior**
expected search results in the expected format.

**Screenshots**
![image](https://github.com/user-attachments/assets/84a24243-d799-46c3-a239-b9e235c9a08d)
![image](https://github.com/user-attachments/assets/ed09c00d-fb94-4af2-a083-8e094769e18f)
![image](https://github.com/user-attachments/assets/d20553c3-4ece-4020-87c8-78e3300b0401)

another error, when i set report type multi agents report, i am getting argument of type NoneType is not iterable. Using gemini-pro-1.5-001 .
![image](https://github.com/user-attachments/assets/94b173d5-2b5c-4a59-93be-ea3a8cf500f9)
![image](https://github.com/user-attachments/assets/52df36b4-21ae-40a0-afb1-028739b1123a)

**Desktop (please complete the following information):**
 - OS: debian
 - Browser :chrome

**Comment by ElishaKay** [comment]
Welcome @hereiamravi 
What's your .env look like (no need for the actual secrets) - just what variables are you using there?

[Have you joined the discord?](https://discord.com/invite/QgZXvJAccX)?
We have a [gptr-bot in the help forum that might be able to help debug](https://discord.com/channels/1127851779011391548/1129339320562626580)

**Comment by hereiamravi** [comment]
@ElishaKay ,

PFB.

![image](https://github.com/user-attachments/assets/9589bbea-3273-432f-886d-650bb256dd25)

apart from the above,  I have change model to gemini-pro-1.5-001 in task.json and agent.py file.

Thanks,

**Comment by ElishaKay** [comment]
@hereiamravi 
I opened a thread in the discord to [consult with the AI Dev Team](https://discord.com/channels/1127851779011391548/1288743087664922624/1288743422546542594)

You need to [join the discord](https://discord.com/invite/QgZXvJAccX) to consult with the bot.

I recommend copy-pasting your .env file into the query to the chatbot as text (without the variables) & letting the bot guide you

**Comment by ElishaKay** [comment]
@hereiamravi 

Can you try adding to your .env:

```
OPENAI_API_KEY="123"
```

Doesn't need to be a real API Key.

If that doesn't work, [read through this one](https://github.com/assafelovic/gpt-researcher/issues/817)

Happy to hear the outcome - we'll make the process more intuitive based on your feedback

**Comment by ElishaKay** [comment]
Sounds good @hereiamravi 

We'll create some docs on it as soon as one brave soul cracks it for the community

**Comment by ElishaKay** [comment]
Sup @hereiamravi 

I'm thinking we should try to debug things separately.

For the Gemini model, you should try running a test script to the test the get_llm function when run with gemini.

Here's [an example of how to test the LLM specifically](https://github.com/assafelovic/gpt-researcher/issues/859#issuecomment-2381125105)

That example is specific to open_ai so you'll have to edit it to test the gen_ai

Try passing in `llm_provider = "google_genai"` into the `get_llm` function.

For testing the Google Retriever, is it not returning results?
If so, try following the same path of finding the core function which powers the retriever for deeper debugging of the issue.

May the force be with you 🙏

**Comment by Kotireddy0** [comment]
@hereiamravi GPT-Researcher is working with Google Gemini, main thing is where exactly you placed your .env file. Please check below folder structure
![Gemini-researcher](https://github.com/user-attachments/assets/1ad572dd-6013-4678-9e98-9845e78dda46)

**Comment by datoslabs** [comment]
Hi,

I encountered similar problems using `RETRIEVER="google"`; I ended up copying and pasting sections of `gpt_researcher/retrievers/google/google.py` code and running them in jupyter notebook and discovered that I did not provide the correct `GOOGLE_CX_KEY`.  As it turned out, I needed to create a "search engine" under Google's [Programable Search Engine](https://programmablesearchengine.google.com/controlpanel/all) and set the `GOOGLE_CX_KEY={Search engine ID}`.

**Comment by ElishaKay** [comment]
Created separate helper functions for:
 - [testing your LLM](https://docs.gptr.dev/docs/gpt-researcher/llms/testing-your-llm)
 - [testing your Retriever](https://docs.gptr.dev/docs/gpt-researcher/search-engines/test-your-retriever)
 
Feel free to open a separate issue if the issue persists

**Comment by gdeldeo** [comment]
Hi I was testing genai models and got it working:
- .env
  add the relevant lines for the models that you wish to use
```
FAST_LLM="google_genai:gemini-1.5-flash-8B"
SMART_LLM="google_genai:gemini-1.5-pro"
STRATEGIC_LLM="google_genai:gemini-1.5-pro"
```
- docker-compose:
   add to the environment the GOOGLE API KEY: 
```
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
```

- requirements.txt:
  Add `langchain_google_genai`

- task.json in the multi_agent 
  change the model to whichever model you prefer for the editor 
 ```
 "follow_guidelines": false,
  "model": "gemini-1.5-pro",
  "guidelines": 
```
this last one I believe was the cause of your issues @hereiamravi 
@ElishaKay the piece of log that pointed me towards this config file
```
gpt-researcher-1  | Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised NotFound: 404 models/gpt-4o is not found for API version v1beta, or is not supported for generateContent. Call ListModels to see the list of available models and their supported methods..
gpt-researcher-1  | 2024-11-21 13:49:57.716 | ERROR    | multi_agents.agents.utils.llms:call_model:49 - Error in calling model: 404 models/gpt-4o is not found for API version v1beta, or is not supported for generateContent. Call ListModels to see the list of available models and their supported methods.
gpt-researcher-1  | ERROR:    Exception in ASGI application
```
If you wish I can submit a PR with changes in the readme
