### ISSUE TITLE
AttributeError: 'GPTResearcher' object has no attribute 'max_subtopics'. Did you mean: 'get_subtopics'?

### ISSUE THREAD

**Issue by vanRaco** [assafelovic/gpt-researcher#877]
**Describe the bug**
When running a Detailed Report I get this error.

**To Reproduce**
1. Install in a virtual environment
2. Run as normal (python -m uvicorn main:app --reload)
3. Get started and Select 'Detailed Report'
4. Start

**Expected behavior**
Provide the detailed report

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version GPT-Researcher [v3.0.8](https://github.com/assafelovic/gpt-researcher/tree/v3.0.8)

**Comment by assafelovic** [comment]
Thanks for helping with this @bhargavyagnik !

**Comment by vanRaco** [comment]
I reinstalled the entire thing and it seems to work now. Thanks for reaching out @bhargavyagnik
