### ISSUE TITLE
Make the translated READMEs more consistent

### ISSUE THREAD

**Issue by kevin1kevin1k** [assafelovic/gpt-researcher#879]
The four translated versions of README.md are inconsistent.
Some examples:
- The English and Korean versions have a logo at the top, while the Japanese and Chinese versions have an H1 title.
- The Japanese and Chinese versions are missing the link to docs, colab, etc. at the top
- The link to colab in the Korean version is inconsistent with the current folder structure: it's pointing to `examples/pip-run.ipynb` which has been moved to `docs/docs/examples/pip-run.ipynb`

I would like to create a PR so that all four versions have the same items and links at the top to avoid people missing some info.

Links of READMEs:
- https://github.com/assafelovic/gpt-researcher/blob/master/README.md
- https://github.com/assafelovic/gpt-researcher/blob/master/README-ko_KR.md
- https://github.com/assafelovic/gpt-researcher/blob/master/README-ja_JP.md
- https://github.com/assafelovic/gpt-researcher/blob/master/README-zh_CN.md

**Comment by assafelovic** [comment]
@kevin1kevin1k go for it with the PR super appreciated!

**Comment by kevin1kevin1k** [comment]
By the way, before checking out the READMEs I found that the `Open in Colab` link is also pointing to the old `examples/pip-run.ipynb` so that I saw the following error when opening the Colab.
But in the codebase I could only found `pip-run.ipynb` in some markdown files (some are not READMEs).
Should I file another issue regarding this?

<img width="616" alt="截圖 2024-10-01 晚上10 34 06" src="https://github.com/user-attachments/assets/dec673b0-563a-440a-9524-8168cf3c18cd">

**Comment by kevin1kevin1k** [comment]
@assafelovic I have the following two options regarding how to position the items. Kindly let me know if you have other alternatives in mind.

- Logo, badges, then h1 title
<img width="1255" alt="截圖 2024-10-01 晚上10 44 44" src="https://github.com/user-attachments/assets/3a701440-5114-4394-a19d-dec522bd6f8b">

- Logo, h1 title, then badges
<img width="1234" alt="截圖 2024-10-01 晚上10 45 27" src="https://github.com/user-attachments/assets/b2793f3c-dbe8-4026-93c3-1812d425c4fe">

**Comment by assafelovic** [comment]
I'd prefer the above @kevin1kevin1k

**Comment by kevin1kevin1k** [comment]
No problem, working on it!
