### ISSUE TITLE
Make the website more User Friendly 

### ISSUE THREAD

**Issue by Srijan-Baniyal** [assafelovic/gpt-researcher#880]
**Is your feature request related to a problem? Please describe.**

Being a web developer is a sometimes a very good job and sometimes very frustrating. So I came across your website. It's a very good website {I'm just talking about the home page }. I saw that the text is getting copied but there is no icon to directly copy it.And there is weird white space. You can refer the image given below : 

<img width="873" alt="Screenshot 2024-10-02 at 12 22 03" src="https://github.com/user-attachments/assets/3725e7b9-3541-44b0-be9f-0cd1edb3947c">

<img width="773" alt="Screenshot 2024-10-02 at 12 22 14" src="https://github.com/user-attachments/assets/fa5b177e-c799-48c6-842e-0c03582d56f9">

**Describe the solution you'd like**

I would like to design or redesign the component given above . Making the component responsive for all devices. And following your guidelines as well as following the design system that you have created.

**Describe alternatives you've considered**
This is the best  method for this issue to fix.

_**Thank You !!**_

**Comment by assafelovic** [comment]
Thanks for this feedback @Srijan-Baniyal ! I'd rather not have the copy option since as you can see it's not valid code that would run. This is why there are CTAs for notebook.
