### ISSUE TITLE
How does TOKEN_LIMIT option in config affect the performance?

### ISSUE THREAD

**Issue by HeMuling** [assafelovic/gpt-researcher#882]
I'm trying to play with `gpt_researcher/config/configurations/default_config.py` to increase the `TOKEN_LIMIT`, in order to generate a more detailed report (mainly to gather more information and generate longer text per paragraph or more paragraphs per section), how can I do this.

Also, I've notice that the default max_tokens to generate report is set to 8001 (according to https://github.com/assafelovic/gpt-researcher/blob/06a58d835aa5d0e5e1f0ec011f0316b6543e0001/gpt_researcher/utils/llm.py#L49), but `gpt-4o` and `gpt-4o-mini` allows Context window up to 128,000 tokens ([openai-model](https://platform.openai.com/docs/models/gpt-4o)). Is there any reason or need to limit to such a low token number?

I'm also wondering if higher `TOKEN_LIMIT` will improve the performance of information gathering and report generation. If so, I think it's more reasonable to provide multiple default configs that allow users to choose between different `TOKEN_LIMIT` to generate longer and more detailed reports.

**Comment by assafelovic** [comment]
Hey @HeMuling good call. I've updated here: https://github.com/assafelovic/gpt-researcher/commit/9fc1fa42f66f66f56420edbf9d0a5afb08264012

Please be in mind that max_tokens relates to the output tokens and not input. Output tokens are still quite limited to 4K with most vendors.

You can update the env vars for both tokens and `TOTAL_WORDS` like so: https://docs.gptr.dev/docs/gpt-researcher/gptr/config

Simply update with env vars. Lmk if this works

**Comment by HeMuling** [comment]
Hi @assafelovic, thanks for your quick reply and updates. For now, my problem has been solved with some changed configs. I shall close the issue and reopen if necessary.
