### ISSUE TITLE
Docs and benchmark request: langgraph version vs normal version

### ISSUE THREAD

**Issue by nnWhisperer** [assafelovic/gpt-researcher#884]
Hello,
I was looking at the docs and it wasn't clear why would one consider the langgraph multi_agent version or the normal one. Is there any planned differences like dropping support for one of them?

I'd like a documentation and benchmark, and possibly a github action to benchmark them once a month to compare the differences between their evolution.

Thank you for the good work!

**Comment by assafelovic** [comment]
@nnWhisperer this is great feedback thank you. I'll add more clarifications to the documentation around this and share here soon

**Comment by assafelovic** [comment]
@nnWhisperer I've added a simple doc here: https://docs.gptr.dev/docs/gpt-researcher/getting-started/how-to-choose

I'll continue to add to it as we progress with evaluation and benchmarks

**Comment by nnWhisperer** [comment]
Hello, thank you for the quick response. I'm closing it to not clutter the issues tab, I suggest you add two tasks to the "project roadmap" tab about benchmarking and github schedule for running the benchmarks once in a while(2 months maybe). Thanks for the good work!"
