### ISSUE TITLE
Can't download PDFs

### ISSUE THREAD

**Issue by shighcloud-ea** [assafelovic/gpt-researcher#888]
When I hit the download PDF button the page just clears and refreshes.

**Comment by 0x11c11e** [comment]
Thanks for reporting this issue! I am not encountering the same problem, so it may be specific to your environment. Could you please provide the following details to help us investigate further:

- The browser and version you're using.
- Any error messages or logs from the browser console.
- Details about your environment (OS, version of GPT-Researcher, etc.).

**Comment by kesamet** [comment]
@shighcloud-ea 
Could you try to run this:
```
from md2pdf import md2pdf
```
Your error could be due to WeasyPrint not able to import some external libraries
