### ISSUE TITLE
Not working properly - {"detail":"Method Not Allowed"}

### ISSUE THREAD

**Issue by rhoconlinux** [assafelovic/gpt-researcher#89]
Hello, I´m getting an error 

`{"detail":"Method` Not Allowed"}

Te output throws a https 405 error. Sometimes it does the request without internet search, other times it just stops working.

After a successful install and no errors in the execution in both python or docker. Is there something I´m missing?

Thanks in advance. 

PS. working on macos ventura intel, python 3.11.1 and latest docker.

**Comment by MrAshRhodes** [comment]
go to line 53 in index.html and replace

<form method="POST" class="mt-3" onsubmit="startResearch(); return false;">

with 

<form method="POST" class="mt-3" onsubmit="GPTResearcher.startResearch(); return false;">

**Comment by gregdrizz** [comment]
Get the most updated code of gptresearcher, if you run into this problem again after you have the line @MrAshRhodes mentioned, clean your browser's cache and it'll work properly

**Comment by assafelovic** [comment]
Thank you for raising this issue. We've merged a fix or this, so please pull latest version.

**Comment by rhoconlinux** [comment]
Thank you! Solved and working as a charm!
Cheers,

**Comment by jeffmoore64** [comment]
Getting the error:
bash-3.2$ $ uvicorn main:app --reload
bash: $: command not found
So do I just install unicorn or do I need to configure it?

**Comment by raviwarrier** [comment]
Hi, I just deployed GPT Researcher as a web service on Render and am calling it from Make.com (like Zapier) from an HTTP module. 
Here is my HTTP module from Make:
![image](https://github.com/assafelovic/gpt-researcher/assets/42061703/d3e723f4-64be-45e4-abf1-6986378ea9ad)

But I get this response
![image](https://github.com/assafelovic/gpt-researcher/assets/42061703/8c0a8499-7355-43a7-9a00-8d7ff1cd181c)

Since I am not using the frontend, how can I solve this. I haven't changed anything in the code.

**Comment by kfern** [comment]
Hi @raviwarrier. Do you have any related log on the server side?

**Comment by raviwarrier** [comment]
```
==> Using Node version 20.10.0 (default)
==> Docs on specifying a Node version: https://render.com/docs/node-version
==> Running 'uvicorn main:app --host 0.0.0.0 --port 10001 --reload'
INFO:     Will watch for changes in these directories: ['/opt/render/project/src']
INFO:     Uvicorn running on http://0.0.0.0:10001/ (Press CTRL+C to quit)
INFO:     Started reloader process [43] using StatReload
INFO:     Started server process [45]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     52.31.156.93:0 - "POST / HTTP/1.1" 405 Method Not Allowed
==> Using Node version 20.10.0 (default)
==> Docs on specifying a Node version: https://render.com/docs/node-version
==> Running 'uvicorn main:app --host 0.0.0.0 --port 10001 --reload'
INFO:     Will watch for changes in these directories: ['/opt/render/project/src']
INFO:     Uvicorn running on http://0.0.0.0:10001/ (Press CTRL+C to quit)
INFO:     Started reloader process [43] using StatReload
INFO:     Started server process [45]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     52.31.156.93:0 - "POST / HTTP/1.1" 405 Method Not Allowed
```

**Comment by raviwarrier** [comment]
that's all I see on the log window of Render

**Comment by kfern** [comment]
How is the data submitted from Make.com? I think you can only interact using ws https://github.com/assafelovic/gpt-researcher/blob/b014c329f7344f5f51412efc4d53badd6fa2b556/backend/server.py#L39

**Comment by raviwarrier** [comment]
I'm not a programmer. could you elaborate please? could you tell me how to use/call the websocket?

**Comment by raviwarrier** [comment]
I checked this docs/docs/tavily-api/rest_api.md
and tried using /search and /search/ but both resulted in "404 detail not found" error
and tried using /ws and /ws/ and got the same 404 error.

what endpoint do I need to use? I also tried api.tavily.com, but that gave a totally different output
