### ISSUE TITLE
Detailed Report - Prompt Leaks and Unnecessary Content

### ISSUE THREAD

**Issue by onlydole** [assafelovic/gpt-researcher#892]
### Describe the bug
The detailed report generator is producing excessive unwanted content ("cruft") in the downloadable documents (Markdown, PDF, Docx).

### To Reproduce
1. Generate a detailed report using the GPT Researcher
2. Download the report in Markdown, PDF, or Docx format
3. Open the downloaded document
4. Observe excessive unwanted content throughout the document

### Expected behavior
The downloaded documents should contain only the relevant report content without extraneous information or formatting issues.

### Screenshots
> Using "France" as the research criteria

<img width="520" alt="Screenshot 2024-10-08 at 9 13 50 AM" src="https://github.com/user-attachments/assets/cf6be2d1-2e48-4a1c-bd3f-8a4ee385fd90">

### Additional context
The issue appears to affect all downloadable formats (Markdown, PDF, Docx). The extra content may include repeated headers, unnecessary blank lines, or other formatting artifacts that make the report difficult to read and use.

This problem significantly impacts the usability of the generated reports, as users need to manually clean up the documents before they can be effectively used or shared.

It would be helpful to review the report generation and export process to identify where this extra content is being introduced and implement appropriate filtering or cleaning steps.

**Comment by assafelovic** [comment]
This is a super bug thank you @onlydole we're on it

**Comment by assafelovic** [comment]
@onlydole fixed now with latest pull: https://github.com/assafelovic/gpt-researcher/pull/895

**Comment by onlydole** [comment]
This is golden! Thank you, @assafelovic!
