### ISSUE TITLE
Support for SearXNG Integration

### ISSUE THREAD

**Issue by coderjunc** [assafelovic/gpt-researcher#894]
I would like to request support for SearXNG. Since the SearX repo is outdated and no longer maintained, I have switched to using SearXNG for all my projects and have a server running on it. However, when trying to implement SearXNG with GPT-Researcher, I encountered an error. I set the `RETRIEVER-ENDPOINT` to my SearXNG server, but it didn’t work at all. 

Is there a solution for this, or could SearXNG integration be added as a feature?

**Comment by BarfingLemurs** [comment]
852142b8605f795e749ceacee787605807784c86 is the breaking commit, local searxng will work fine with anything before that.

**Comment by coderjunc** [comment]
Hey @BarfingLemurs Thank you so much! It really helped me. Instead of setting the endpoint to Searx, I was setting it as Custom. Thanks again for your help. You have pretty much solved a big problem. 💐
