### ISSUE TITLE
Local Models

### ISSUE THREAD

**Issue by Naugustogi** [assafelovic/gpt-researcher#9]
Why is everyone forgetting about local models. Many can't even buy an GPT4 api key.
Just add support.

**Comment by rotemweiss57** [comment]
Hi luckily they just made it accessible! https://techcrunch.com/2023/07/06/openai-makes-gpt-4-generally-available/

**Comment by firerish** [comment]
Why not allow using gtp3? Are the results too unusable?

**Comment by rotemweiss57** [comment]
Hi! the models are defined in config/config.py:
self.fast_llm_model = os.getenv("FAST_LLM_MODEL", "gpt-3.5-turbo-16k")
self.smart_llm_model = os.getenv("SMART_LLM_MODEL", "gpt-4")

you could see that we use a lot of gpt3 to speed it up, but you can definitely test out different configurations.

personally, I noticed a HUGE difference in results so I stick to gpt4.

Hope it helps

**Comment by tohrnii** [comment]
Actually it would be good to add support for local models at some point and make the choice optional regardless of the cost concerns.
