### ISSUE TITLE
Error in converting Markdown to PDF: cannot load library 'pango-1.0-0'

### ISSUE THREAD

**Issue by PieBru** [assafelovic/gpt-researcher#903]
**Describe the bug**
Adding 'pango-1.0-0' to requirements.txt did not solve the error.

```log
INFO:     [13:01:17] Finalized research step.
INFO:     [13:01:17] ✍️ Writing report for ...
INFO:     [13:02:14] 📝 Report written for ...

-----

WeasyPrint could not import some external libraries. Please carefully follow the installation steps before reporting an issue:
https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#installation
https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#troubleshooting 

-----

Error in converting Markdown to PDF: cannot load library 'pango-1.0-0': pango-1.0-0: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'pango-1.0-0'
```

**To Reproduce**
1. Use uvicorn server to execute a research.
2. ![image](https://github.com/user-attachments/assets/c0392ceb-75bc-4dfd-8b80-45e465fe7080)
3. The "Download PDF" button goes to the home page.
4. See error.

**Expected behavior**
To be able to download the PDF report.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Debian 12 LXC on Proxmox VE 8.2
 - Browser: LibreWolf (Firefox)
 - Version: -

**Smartphone (please complete the following information):**
 - Device: none
 - OS: -
 - Browser -
 - Version -

**Additional context**

**Comment by kesamet** [comment]
Hi @PieBru, could you try
```
sudo apt-get install -y libpangocairo-1.0-0
```

**Comment by PieBru** [comment]
@kesamet Your workaround works.
Thank you.
