### ISSUE TITLE
Missing gpt_researcher.config.variables 

### ISSUE THREAD

**Issue by Johannes1213** [assafelovic/gpt-researcher#911]
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-8-f34ee6f3bb6d>](https://a1gyo8cefi6-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20241010-060117_RC00_684361355#) in <cell line: 2>()
      1 import asyncio
----> 2 from backend.report_type import DetailedReport
      3 
      4 async def test_detailed_report():
      5     detailed_report = DetailedReport(

11 frames
[/usr/local/lib/python3.10/dist-packages/gpt_researcher/config/config.py](https://a1gyo8cefi6-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20241010-060117_RC00_684361355#) in <module>
      3 import warnings
      4 from typing import Dict, Any, List, Union, Type, get_origin, get_args
----> 5 from .variables.default import DEFAULT_CONFIG
      6 from .variables.base import BaseConfig
      7 

ModuleNotFoundError: No module named 'gpt_researcher.config.variables'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

**Comment by assafelovic** [comment]
looking into it

**Comment by assafelovic** [comment]
@Johannes1213 can you try `pip install -U gpt-researcher ` ? Just pushed a fix

**Comment by Johannes1213** [comment]
Yesterday it worked after directly cloning the repo. 

Still a `Warning: Configuration 'None' not found. Using default configuration.` but it runs regardless of pip/pip -U,  today.

(love your work by the way. I work for a NPO called d-lab in South Africa and I'm currently building a pipeline that automatically identifies funding opportunities, utilising the `DetailedReport` - `resource_report` type. I can say with confidence that the work you inspire will change lives!)

**Comment by assafelovic** [comment]
@Johannes1213 thank you so much for the kind words this made my day :) It's a lot thanks to the community as well. I couldn't do it alone.

As regards to the warning it's fine, it should work now.
