### ISSUE TITLE
VertexAI Ported - Content getting searched, but the final report is not getting generated.

### ISSUE THREAD

**Issue by hereiamravi** [assafelovic/gpt-researcher#934]
**Describe the bug**
VertexAI Ported - Content getting searched, but the final report is not getting generated.

**To Reproduce**
set the required environment variables.
`
#OPENAI_API_KEY=
TAVILY_API_KEY=<API KEY>
DOC_PATH=./my-docs
LANGCHAIN_API_KEY=<API KEY>
LLM_PROVIDER=google_vertexai
FAST_LLM=google_vertexai:gemini-1.5-flash-001
SMART_LLM=google_vertexai:gemini-1.5-pro-001
EMBEDDING_PROVIDER=huggingface
`

**Expected behavior**
report should be generated after content is searched.

**Screenshots**
research report is blank
<img width="871" alt="image" src="https://github.com/user-attachments/assets/1349ce5a-0f8c-4daf-afc2-ce6299481a4d">
<img width="613" alt="image" src="https://github.com/user-attachments/assets/c00f5835-4eea-441b-97ce-10fbb12830bb">

When OpenAI- gpt is used. report is getting generated successfully.

<img width="679" alt="image" src="https://github.com/user-attachments/assets/4085e3a2-7e16-4bc7-a87b-713f840f178d">
<img width="564" alt="image" src="https://github.com/user-attachments/assets/d77f39be-d009-47f3-adb2-1a6caa1f1a09">

**Desktop (please complete the following information):**
 - OS: debian
 - Browser : chorme
 - Version [e.g. 22] : latest

**Additional context**
I tried to use google_vertexai:gemini-1.5-pro-001 for both smart and fast llm but the same error.

**Comment by ElishaKay** [comment]
Perhaps solved by this one: 

https://github.com/assafelovic/gpt-researcher/pull/965

There were a lot of upgrades this week

**Comment by hereiamravi** [comment]
HI @ElishaKay , Pulled the latest code changes and used google_vertexai for embeddings, still the same issue of report not getting generated. 

May be  I will work it out and raise PR if root cause identified.

**Comment by ElishaKay** [comment]
[Based on this](https://docs.gptr.dev/docs/gpt-researcher/llms/llms), you also need a `STRATEGIC_LLM` variable in your .env.

Try this config:

```bash
FAST_LLM="google_vertexai:gemini-1.5-flash-001"
SMART_LLM="google_vertexai:gemini-1.5-pro-001"
STRATEGIC_LLM="google_vertexai:gemini-1.5-pro-001"

EMBEDDING="google_vertexai:text-embedding-004"
```

If it doesn't work: what's the error message, if there is one? You're saying the logs say the report is written and there is no report there?
