### ISSUE TITLE
There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_115.0.5790

### ISSUE THREAD

**Issue by ilkerc** [assafelovic/gpt-researcher#94]
The recent modifications to the hosting paths at chromedrivers causes this issue. Check the related [PR](https://github.com/SergeyPirogov/webdriver_manager/pull/537) in webdriver_manager

Anyone having the same issue and don't want to wait for the forthcoming fix, just uninstall the existing webdriver manager and install the PR branch

```
pip uninstall webdriver_manager
pip install git+https://github.com/david-engelmann/webdriver_manager@de-upgrade-chrome-version
```

**Comment by david-engelmann** [comment]
the main on that repo is identical btw

**Comment by SergeyPirogov** [comment]
Well I see that the PR is not fixing issue with 114 version

**Comment by david-engelmann** [comment]
114.0.5735.198 doesn't exist as a version

**Comment by david-engelmann** [comment]
Should be resolved

**Comment by gregdrizz** [comment]
try using firefox for now by changing the env var "USE_WEB_BROWSER" to firefox (make sure firefox is installed on your pc)

**Comment by ilkerc** [comment]
Looks like the issue is resolved in an other PR here https://github.com/SergeyPirogov/webdriver_manager/pull/539 and published a pip version including it. Pip upgrade should work for anyone having this issue.
