### ISSUE TITLE
langchain-huggingface is incompatible with langchain-core, langchain-openai and gpt-researcher

### ISSUE THREAD

**Issue by Bless50** [assafelovic/gpt-researcher#943]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by assafelovic** [comment]
Can you pull and try again?

**Comment by assafelovic** [comment]
Also `pip install -r -U requirements.txt`
