### ISSUE TITLE
Is it possible to get an arxiv formatted paper , totally by gpt-researcher

### ISSUE THREAD

**Issue by CoderYiFei** [assafelovic/gpt-researcher#949]

**Comment by ElishaKay** [comment]
By default, GPTR is writing reports in Markdown format - both for the basic research tasks & the multi_agent research tasks.

If you need to reformat the report, seems the path of least resistance would be to feed the final generated report into a new `create_chat_completion` function & ask for the report to be reformatted in your desired format.
