### ISSUE TITLE
Error occurred when using Custom OpenAI API LLM

### ISSUE THREAD

**Issue by ki-ri** [assafelovic/gpt-researcher#957]
**Describe the bug**
I am using Custom OpenAI API LLM([llama.cpp Server](https://github.com/ggerganov/llama.cpp/blob/master/examples/server/README.md#quick-start)) as LLM according to the manual below, when I searched something I got the error. (I tested the llama.cpp Server, and it worked well independently)
https://docs.gptr.dev/docs/gpt-researcher/llms/llms#custom-openai-api-llm

- error:
```
  File "/Users/xxx/study/AI/tools/gpt-researcher/gpt_researcher/skills/researcher.py", line 149, in __get_context_by_search
    sub_queries.append(query)
    ^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'append'
INFO:     connection closed
```

- LLM config
```
# set the custom OpenAI API url
OPENAI_BASE_URL="http://localhost:8080"
# set the custom OpenAI API key
OPENAI_API_KEY="sk-no-key-required"
TAVILY_API_KEY="my tavily key"

# specify the custom OpenAI API llm model  
FAST_LLM="openai:gpt-4o-mini"
# specify the custom OpenAI API llm model  
SMART_LLM="openai:gpt-4o"
DOC_PATH=./my-docs
```

**To Reproduce**
- please see the information above

**Expected behavior**
- searched result displayed

**Screenshots**
- terminated unsuccessfully, and got no report.
<img width="1186" alt="image" src="https://github.com/user-attachments/assets/03132e61-8a4a-4c2a-bc69-a7e34fa91fd8">

**Desktop (please complete the following information):**
 - OS: macOS 13.5
 - Browser chrome

**Comment by ElishaKay** [comment]
Looks like the LLM is configured correctly for chat_completion, but perhaps not for the embedding stage.

We'll need to create a separate function for testing just the embedding stage based on config variables - [something similar to this](https://docs.gptr.dev/docs/gpt-researcher/llms/testing-your-llm)

**Comment by iokarkan** [comment]
Having the same issue with ollama for commit SHA f6ea94de772c5194df703a8fb79335f6c8b5865d
and the following `.env`:

```
OPENAI_API_KEY="123"
OPENAI_API_BASE="http://127.0.0.1:11434/v1"
OLLAMA_BASE_URL="http://127.0.0.1:11434/"
FAST_LLM=ollama:qwen3-vl:2b
SMART_LLM=ollama:qwen3-vl:2b
STRATEGIC_LLM=ollama:qwen3-vl:2b
EMBEDDING_PROVIDER="ollama"
OLLAMA_EMBEDDING_MODEL="nomic-embed-text"
```
