### ISSUE TITLE
There is no method called get_similar_content_by_query_with_vectorstore in the Memory Context Manager

### ISSUE THREAD

**Issue by ab94amz** [assafelovic/gpt-researcher#963]
https://github.com/assafelovic/gpt-researcher/blob/99ba03a2f893944d715bda68d5b54bc2a60620e0/gpt_researcher/skills/researcher.py#L187

Hi, 

this line is calling a method "get_similar_content_by_query_with_vectorstore" which doesn't exist in the ContextManager class. Can you help to resolve?

Thanks,

**Comment by assafelovic** [comment]
@ab94amz can you pull latest and try again? Pushed this fix: https://github.com/assafelovic/gpt-researcher/commit/6fdb2f0dd7967681f6f761c00efde2d9868a2ab9
