### ISSUE TITLE
Incorrect Import Statement

### ISSUE THREAD

**Issue by JustlyAI** [assafelovic/gpt-researcher#966]
**Describe the bug**
The file 'document_report_source.py' includes the following: "from gpt_researcher.master.agent import GPTResearcher".

This should be "from gpt_researcher import GPTResearcher"

**To Reproduce**
1. Go to '/gpt_researcher/'
2. Confirm no master.agent folders

GPTResearcher class is found in /gpt_researcher/agent.py.

**Comment by assafelovic** [comment]
Thanks @JustlyAI just pushed a fix for this.
