### ISSUE TITLE
Commit a lock file for the frontend ?

### ISSUE THREAD

**Issue by happysalada** [assafelovic/gpt-researcher#975]
**Is your feature request related to a problem? Please describe.**
Without a lockfile, the build of the frontend dependencies won't be reproducible. It might succeed sometimes and fail other time. While packaging this for a linux distribution, it would be very nice to have the frontend lockfile

**Describe the solution you'd like**
Commit a lockfile (whichever format you prefer, npm, yarn, pnpm) but at least have one lockfile.

**Describe alternatives you've considered**
Not commiting the lockfile and let every maintainer generate it everytime

**Additional context**
I'm packaging this for Nixos. I could generate a lockfile myself, but it would help a lot if it was provided, thank you in advance!

**Comment by ElishaKay** [comment]
Welcome @happysalada 

Are there any risks with it?
For example, if we commit a lockfile that was generated on a Linux machine, does it have potential to break the build on Mac or Windows?

**Comment by happysalada** [comment]
I dont think the build will break (ive never seen it, that said, i havent yet seen everything ).
The main downside is that you commit to an ecosystem (yarn, npm, pnpm, bun...). So everyone downstream (developpers, maintainers ...) has to make the same choice.

On another note, i tried gpt researcher and its really nice. I was thinking one way to improve potentially would be to mix the content of different search engine to do the research, mix tavily and searxng for exemple and have an algorithim rerank the results. Just a thought, what you built is already really nice !

**Comment by ElishaKay** [comment]
Thanks for the kind words @happysalada - 100 contributors and growing, so this is all about community, at the end of the day.

We like to remain agnostic wherever possible.

Re: Custom Context: Have a look at this doc on [leveraging multiple retrievers or a custom retriever](https://docs.gptr.dev/docs/gpt-researcher/search-engines/retrievers#web-search-engines)

There's also some really customizable things you can do with [Langchain VectorStores](https://docs.gptr.dev/docs/gpt-researcher/context/vector-stores)

May the force be with you 🙏
