### ISSUE TITLE
OPENAI o1 usage

### ISSUE THREAD

**Issue by guiramos** [assafelovic/gpt-researcher#996]
Is there a way to not use o1? 

I think it's a very expensive model and using it multiple times can render this unusable.

Please tell me that yes, there is way. And how, from the python perspective:

```
researcher = GPTResearcher(query=query, report_type=report_type, config_path=None)
await researcher.conduct_research()
```

**Comment by adrianhensler** [comment]
I believe you wish to look here; I'm sure someone will correct me if I am wrong: https://github.com/assafelovic/gpt-researcher/blob/master/gpt_researcher/config/variables/default.py

See also: https://docs.gptr.dev/docs/gpt-researcher/llms/llms

**Comment by assafelovic** [comment]
Thanks @adrianhensler . You can change the STRATEGIC_LLM env var to a different model like so: `STRATEGIC_LLM=openai:gpt-4o`

**Comment by guiramos** [comment]
@assafelovic yes! I think it makes sense because o1 is still to expensive and too slow.

I was able to create a temporary config and use it.

However I have an additional question, is there a way to override the amount of words without having to re-write the configuration?

**Comment by assafelovic** [comment]
You can use any of the config vars as env vars so simply pass TOTAL_WORDS with any length and should be good to go. Take in mind you might also need to adjust SMART_TOKEN_LIMIT which currently defaults to 4000.

**Comment by guiramos** [comment]
Ok, I did this and seems to be working really nice:

```
REPORT_TYPE = "research_report"

    researcher = GPTResearcher(query=query, report_type=REPORT_TYPE, config_path=f"{APP_PATH}/agent/resources/researcher.json")
    researcher.cfg.total_words = total_words
    researcher.cfg.smart_token_limit = total_words * 4
```


This project is amazing! Please keep up the good work! Will close it.

@assafelovic
