### ISSUE TITLE
Error parsing dimension value 100%: invalid literal for int() with base 10: '100%'

### ISSUE THREAD

**Issue by happysalada** [assafelovic/gpt-researcher#997]
**Describe the bug**
I'm getting the following error when running the app on latest master.

Error parsing dimension value 100%: invalid literal for int() with base 10: '100%'

**To Reproduce**
1. export RETRIEVER="tavily, arxiv, duckduckgo"
2. add "duckduckgo-search" to the default requirements.txt
3. install dependencies
4. run the app
 
**Expected behavior**
The errors in the console don't lead to anything crashing, but I'm guessing that potentially some information are not being ingested correctly.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macos

**Additional context**
Not a big deal, let me know if you need more information

**Comment by happysalada** [comment]
I'm also getting

Error in converting Markdown to PDF: cannot load library 'libgobject-2.0-0': dlopen(libgobject-2.0-0, 0x0002): tried: 'libgobject-2.0-0' (no such file), '/usr/local/lib/libgobject-2.0-0' (no such file), '/usr/lib/libgobject-2.0-0' (no such file), '/Users/macintoshhd/dev/gpt-researcher/libgobject-2.0-0' (no such file).  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libgobject-2.0-0'

**Comment by ElishaKay** [comment]
Path of least resistance is docker

Try here:

https://docs.gptr.dev/docs/gpt-researcher/getting-started/getting-started-with-docker
